version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "bun"
    directory: "/frontend"
    open-pull-requests-limit: 3
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "zod"
      - dependency-name: "playwright"
    groups:
      frontend-bun-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/backend"
    open-pull-requests-limit: 3
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      backend-go-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
