// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: querylane/console/v1alpha1/errors.proto

package consolev1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PostgreSqlErrorDetail with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PostgreSqlErrorDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PostgreSqlErrorDetail with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PostgreSqlErrorDetailMultiError, or nil if none found.
func (m *PostgreSqlErrorDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *PostgreSqlErrorDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sqlstate

	// no validation rules for SqlstateClass

	// no validation rules for ConditionName

	// no validation rules for Operation

	// no validation rules for ServerFields

	// no validation rules for Kind

	// no validation rules for RetryGuidance

	if len(errors) > 0 {
		return PostgreSqlErrorDetailMultiError(errors)
	}

	return nil
}

// PostgreSqlErrorDetailMultiError is an error wrapping multiple validation
// errors returned by PostgreSqlErrorDetail.ValidateAll() if the designated
// constraints aren't met.
type PostgreSqlErrorDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PostgreSqlErrorDetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PostgreSqlErrorDetailMultiError) AllErrors() []error { return m }

// PostgreSqlErrorDetailValidationError is the validation error returned by
// PostgreSqlErrorDetail.Validate if the designated constraints aren't met.
type PostgreSqlErrorDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PostgreSqlErrorDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PostgreSqlErrorDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PostgreSqlErrorDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PostgreSqlErrorDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PostgreSqlErrorDetailValidationError) ErrorName() string {
	return "PostgreSqlErrorDetailValidationError"
}

// Error satisfies the builtin error interface
func (e PostgreSqlErrorDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPostgreSqlErrorDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PostgreSqlErrorDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PostgreSqlErrorDetailValidationError{}
