// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: querylane/console/v1alpha1/extension.proto

package consolev1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Extension with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Extension) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Extension with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ExtensionMultiError, or nil
// if none found.
func (m *Extension) ValidateAll() error {
	return m.validate(true)
}

func (m *Extension) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for DisplayName

	// no validation rules for Schema

	// no validation rules for DefaultVersion

	// no validation rules for InstalledVersion

	// no validation rules for Comment

	// no validation rules for Installed

	if len(errors) > 0 {
		return ExtensionMultiError(errors)
	}

	return nil
}

// ExtensionMultiError is an error wrapping multiple validation errors returned
// by Extension.ValidateAll() if the designated constraints aren't met.
type ExtensionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExtensionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExtensionMultiError) AllErrors() []error { return m }

// ExtensionValidationError is the validation error returned by
// Extension.Validate if the designated constraints aren't met.
type ExtensionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExtensionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExtensionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExtensionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExtensionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExtensionValidationError) ErrorName() string { return "ExtensionValidationError" }

// Error satisfies the builtin error interface
func (e ExtensionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExtension.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExtensionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExtensionValidationError{}

// Validate checks the field values on ListExtensionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListExtensionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListExtensionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListExtensionsRequestMultiError, or nil if none found.
func (m *ListExtensionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListExtensionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Parent

	// no validation rules for PageSize

	// no validation rules for PageToken

	// no validation rules for Filter

	// no validation rules for OrderBy

	if len(errors) > 0 {
		return ListExtensionsRequestMultiError(errors)
	}

	return nil
}

// ListExtensionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListExtensionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListExtensionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListExtensionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListExtensionsRequestMultiError) AllErrors() []error { return m }

// ListExtensionsRequestValidationError is the validation error returned by
// ListExtensionsRequest.Validate if the designated constraints aren't met.
type ListExtensionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListExtensionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListExtensionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListExtensionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListExtensionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListExtensionsRequestValidationError) ErrorName() string {
	return "ListExtensionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListExtensionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListExtensionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListExtensionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListExtensionsRequestValidationError{}

// Validate checks the field values on ListExtensionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListExtensionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListExtensionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListExtensionsResponseMultiError, or nil if none found.
func (m *ListExtensionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListExtensionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetExtensions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListExtensionsResponseValidationError{
						field:  fmt.Sprintf("Extensions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListExtensionsResponseValidationError{
						field:  fmt.Sprintf("Extensions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListExtensionsResponseValidationError{
					field:  fmt.Sprintf("Extensions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListExtensionsResponseMultiError(errors)
	}

	return nil
}

// ListExtensionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListExtensionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListExtensionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListExtensionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListExtensionsResponseMultiError) AllErrors() []error { return m }

// ListExtensionsResponseValidationError is the validation error returned by
// ListExtensionsResponse.Validate if the designated constraints aren't met.
type ListExtensionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListExtensionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListExtensionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListExtensionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListExtensionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListExtensionsResponseValidationError) ErrorName() string {
	return "ListExtensionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListExtensionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListExtensionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListExtensionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListExtensionsResponseValidationError{}
