// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: querylane/console/v1alpha1/onboarding.proto

package consolev1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StepState represents the lifecycle state of a single setup step.
type StepState int32

const (
	// Default value, should not be used.
	StepState_STEP_STATE_UNSPECIFIED StepState = 0
	// The step has not started yet.
	StepState_STEP_STATE_PENDING StepState = 1
	// The step is currently executing.
	StepState_STEP_STATE_IN_PROGRESS StepState = 2
	// The step completed successfully.
	StepState_STEP_STATE_SUCCEEDED StepState = 3
	// The step failed. See `SetupProgressEvent.error` for details.
	StepState_STEP_STATE_FAILED StepState = 4
)

// Enum value maps for StepState.
var (
	StepState_name = map[int32]string{
		0: "STEP_STATE_UNSPECIFIED",
		1: "STEP_STATE_PENDING",
		2: "STEP_STATE_IN_PROGRESS",
		3: "STEP_STATE_SUCCEEDED",
		4: "STEP_STATE_FAILED",
	}
	StepState_value = map[string]int32{
		"STEP_STATE_UNSPECIFIED": 0,
		"STEP_STATE_PENDING":     1,
		"STEP_STATE_IN_PROGRESS": 2,
		"STEP_STATE_SUCCEEDED":   3,
		"STEP_STATE_FAILED":      4,
	}
)

func (x StepState) Enum() *StepState {
	p := new(StepState)
	*p = x
	return p
}

func (x StepState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepState) Descriptor() protoreflect.EnumDescriptor {
	return file_querylane_console_v1alpha1_onboarding_proto_enumTypes[0].Descriptor()
}

func (StepState) Type() protoreflect.EnumType {
	return &file_querylane_console_v1alpha1_onboarding_proto_enumTypes[0]
}

func (x StepState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepState.Descriptor instead.
func (StepState) EnumDescriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{0}
}

// SetupStep identifies a phase in the database setup pipeline.
// The frontend uses these values to match UI elements to progress events.
type SetupStep int32

const (
	// Default value, should not be used.
	SetupStep_SETUP_STEP_UNSPECIFIED SetupStep = 0
	// Starting the embedded PostgreSQL instance.
	SetupStep_SETUP_STEP_STARTING_EMBEDDED SetupStep = 1
	// Connecting to the PostgreSQL server.
	SetupStep_SETUP_STEP_CONNECTING SetupStep = 2
	// Running database migrations.
	SetupStep_SETUP_STEP_MIGRATING SetupStep = 3
	// Initializing application services.
	SetupStep_SETUP_STEP_INITIALIZING_SERVICES SetupStep = 4
	// Persisting the configuration to disk.
	SetupStep_SETUP_STEP_PERSISTING_CONFIG SetupStep = 5
	// Waiting for an external configuration change (manual YAML edit).
	SetupStep_SETUP_STEP_WAITING_FOR_CONFIG SetupStep = 6
	// An external configuration change was detected.
	SetupStep_SETUP_STEP_CONFIG_DETECTED SetupStep = 7
)

// Enum value maps for SetupStep.
var (
	SetupStep_name = map[int32]string{
		0: "SETUP_STEP_UNSPECIFIED",
		1: "SETUP_STEP_STARTING_EMBEDDED",
		2: "SETUP_STEP_CONNECTING",
		3: "SETUP_STEP_MIGRATING",
		4: "SETUP_STEP_INITIALIZING_SERVICES",
		5: "SETUP_STEP_PERSISTING_CONFIG",
		6: "SETUP_STEP_WAITING_FOR_CONFIG",
		7: "SETUP_STEP_CONFIG_DETECTED",
	}
	SetupStep_value = map[string]int32{
		"SETUP_STEP_UNSPECIFIED":           0,
		"SETUP_STEP_STARTING_EMBEDDED":     1,
		"SETUP_STEP_CONNECTING":            2,
		"SETUP_STEP_MIGRATING":             3,
		"SETUP_STEP_INITIALIZING_SERVICES": 4,
		"SETUP_STEP_PERSISTING_CONFIG":     5,
		"SETUP_STEP_WAITING_FOR_CONFIG":    6,
		"SETUP_STEP_CONFIG_DETECTED":       7,
	}
)

func (x SetupStep) Enum() *SetupStep {
	p := new(SetupStep)
	*p = x
	return p
}

func (x SetupStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetupStep) Descriptor() protoreflect.EnumDescriptor {
	return file_querylane_console_v1alpha1_onboarding_proto_enumTypes[1].Descriptor()
}

func (SetupStep) Type() protoreflect.EnumType {
	return &file_querylane_console_v1alpha1_onboarding_proto_enumTypes[1]
}

func (x SetupStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetupStep.Descriptor instead.
func (SetupStep) EnumDescriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{1}
}

// SetupMethod describes a way to configure the application database.
type SetupMethod int32

const (
	// Default value, should not be used.
	SetupMethod_SETUP_METHOD_UNSPECIFIED SetupMethod = 0
	// Configure PostgreSQL connection via the UI form. Requires a writable
	// filesystem to persist the generated config file.
	SetupMethod_SETUP_METHOD_UI_CONFIGURED SetupMethod = 1
	// Edit the YAML config file manually. Always available.
	SetupMethod_SETUP_METHOD_MANUAL_YAML SetupMethod = 2
	// Use an embedded PostgreSQL instance managed by querylane. Requires a
	// writable filesystem for the data directory.
	SetupMethod_SETUP_METHOD_EMBEDDED SetupMethod = 3
)

// Enum value maps for SetupMethod.
var (
	SetupMethod_name = map[int32]string{
		0: "SETUP_METHOD_UNSPECIFIED",
		1: "SETUP_METHOD_UI_CONFIGURED",
		2: "SETUP_METHOD_MANUAL_YAML",
		3: "SETUP_METHOD_EMBEDDED",
	}
	SetupMethod_value = map[string]int32{
		"SETUP_METHOD_UNSPECIFIED":   0,
		"SETUP_METHOD_UI_CONFIGURED": 1,
		"SETUP_METHOD_MANUAL_YAML":   2,
		"SETUP_METHOD_EMBEDDED":      3,
	}
)

func (x SetupMethod) Enum() *SetupMethod {
	p := new(SetupMethod)
	*p = x
	return p
}

func (x SetupMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetupMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_querylane_console_v1alpha1_onboarding_proto_enumTypes[2].Descriptor()
}

func (SetupMethod) Type() protoreflect.EnumType {
	return &file_querylane_console_v1alpha1_onboarding_proto_enumTypes[2]
}

func (x SetupMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetupMethod.Descriptor instead.
func (SetupMethod) EnumDescriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{2}
}

// SetupProgressEvent reports the state of a single step in the database setup
// pipeline. Both streaming RPCs return the same event type.
//
// Stream protocol:
//  1. First batch: all steps for the flow are sent with STEP_STATE_PENDING so
//     the frontend can render the full list upfront.
//  2. Subsequent messages: individual step state transitions
//     (IN_PROGRESS → SUCCEEDED or FAILED).
type SetupProgressEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. Identifies which setup step this event refers to.
	StepId SetupStep `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3,enum=querylane.console.v1alpha1.SetupStep" json:"step_id,omitempty"`
	// Output-only. Human-readable label for display.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Output-only. Current state of this step.
	State StepState `protobuf:"varint,3,opt,name=state,proto3,enum=querylane.console.v1alpha1.StepState" json:"state,omitempty"`
	// Output-only. Error details when state is STEP_STATE_FAILED, empty otherwise.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupProgressEvent) Reset() {
	*x = SetupProgressEvent{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupProgressEvent) ProtoMessage() {}

func (x *SetupProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupProgressEvent.ProtoReflect.Descriptor instead.
func (*SetupProgressEvent) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{0}
}

func (x *SetupProgressEvent) GetStepId() SetupStep {
	if x != nil {
		return x.StepId
	}
	return SetupStep_SETUP_STEP_UNSPECIFIED
}

func (x *SetupProgressEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SetupProgressEvent) GetState() StepState {
	if x != nil {
		return x.State
	}
	return StepState_STEP_STATE_UNSPECIFIED
}

func (x *SetupProgressEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// EmbeddedSetupConfig holds optional overrides for the embedded PostgreSQL
// setup method.
type EmbeddedSetupConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Port for the embedded PostgreSQL instance. Defaults to 5433.
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Optional. Data persistence mode: "persistent" (default) or "ephemeral".
	Mode          string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddedSetupConfig) Reset() {
	*x = EmbeddedSetupConfig{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedSetupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedSetupConfig) ProtoMessage() {}

func (x *EmbeddedSetupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedSetupConfig.ProtoReflect.Descriptor instead.
func (*EmbeddedSetupConfig) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddedSetupConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EmbeddedSetupConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetOnboardingStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnboardingStateRequest) Reset() {
	*x = GetOnboardingStateRequest{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingStateRequest) ProtoMessage() {}

func (x *GetOnboardingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingStateRequest.ProtoReflect.Descriptor instead.
func (*GetOnboardingStateRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{2}
}

type GetOnboardingStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. Whether a database configuration already exists.
	IsConfigured bool `protobuf:"varint,1,opt,name=is_configured,json=isConfigured,proto3" json:"is_configured,omitempty"`
	// Output-only. Current status of the application database.
	AppDatabaseStatus *AppDatabaseStatus `protobuf:"bytes,2,opt,name=app_database_status,json=appDatabaseStatus,proto3" json:"app_database_status,omitempty"`
	// Output-only. Absolute path to the querylane home directory (~/.querylane).
	HomePath string `protobuf:"bytes,3,opt,name=home_path,json=homePath,proto3" json:"home_path,omitempty"`
	// Output-only. Whether the home directory is writable.
	IsHomeWritable bool `protobuf:"varint,4,opt,name=is_home_writable,json=isHomeWritable,proto3" json:"is_home_writable,omitempty"`
	// Output-only. Setup methods available in the current environment.
	AvailableMethods []SetupMethod `protobuf:"varint,5,rep,packed,name=available_methods,json=availableMethods,proto3,enum=querylane.console.v1alpha1.SetupMethod" json:"available_methods,omitempty"`
	// Output-only. Absolute path to the configuration file.
	ConfigFilePath string `protobuf:"bytes,6,opt,name=config_file_path,json=configFilePath,proto3" json:"config_file_path,omitempty"`
	// Output-only. Absolute path to the embedded PostgreSQL data directory.
	EmbeddedDataPath string `protobuf:"bytes,7,opt,name=embedded_data_path,json=embeddedDataPath,proto3" json:"embedded_data_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOnboardingStateResponse) Reset() {
	*x = GetOnboardingStateResponse{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingStateResponse) ProtoMessage() {}

func (x *GetOnboardingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingStateResponse.ProtoReflect.Descriptor instead.
func (*GetOnboardingStateResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{3}
}

func (x *GetOnboardingStateResponse) GetIsConfigured() bool {
	if x != nil {
		return x.IsConfigured
	}
	return false
}

func (x *GetOnboardingStateResponse) GetAppDatabaseStatus() *AppDatabaseStatus {
	if x != nil {
		return x.AppDatabaseStatus
	}
	return nil
}

func (x *GetOnboardingStateResponse) GetHomePath() string {
	if x != nil {
		return x.HomePath
	}
	return ""
}

func (x *GetOnboardingStateResponse) GetIsHomeWritable() bool {
	if x != nil {
		return x.IsHomeWritable
	}
	return false
}

func (x *GetOnboardingStateResponse) GetAvailableMethods() []SetupMethod {
	if x != nil {
		return x.AvailableMethods
	}
	return nil
}

func (x *GetOnboardingStateResponse) GetConfigFilePath() string {
	if x != nil {
		return x.ConfigFilePath
	}
	return ""
}

func (x *GetOnboardingStateResponse) GetEmbeddedDataPath() string {
	if x != nil {
		return x.EmbeddedDataPath
	}
	return ""
}

type SetupAppDatabaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The setup configuration — either external PostgreSQL connection
	// details or embedded PostgreSQL settings.
	//
	// Types that are valid to be assigned to Setup:
	//
	//	*SetupAppDatabaseRequest_PostgresConfig
	//	*SetupAppDatabaseRequest_EmbeddedConfig
	Setup         isSetupAppDatabaseRequest_Setup `protobuf_oneof:"setup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupAppDatabaseRequest) Reset() {
	*x = SetupAppDatabaseRequest{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupAppDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupAppDatabaseRequest) ProtoMessage() {}

func (x *SetupAppDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupAppDatabaseRequest.ProtoReflect.Descriptor instead.
func (*SetupAppDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{4}
}

func (x *SetupAppDatabaseRequest) GetSetup() isSetupAppDatabaseRequest_Setup {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *SetupAppDatabaseRequest) GetPostgresConfig() *PostgresConfig {
	if x != nil {
		if x, ok := x.Setup.(*SetupAppDatabaseRequest_PostgresConfig); ok {
			return x.PostgresConfig
		}
	}
	return nil
}

func (x *SetupAppDatabaseRequest) GetEmbeddedConfig() *EmbeddedSetupConfig {
	if x != nil {
		if x, ok := x.Setup.(*SetupAppDatabaseRequest_EmbeddedConfig); ok {
			return x.EmbeddedConfig
		}
	}
	return nil
}

type isSetupAppDatabaseRequest_Setup interface {
	isSetupAppDatabaseRequest_Setup()
}

type SetupAppDatabaseRequest_PostgresConfig struct {
	// Configure using an external PostgreSQL connection.
	PostgresConfig *PostgresConfig `protobuf:"bytes,1,opt,name=postgres_config,json=postgresConfig,proto3,oneof"`
}

type SetupAppDatabaseRequest_EmbeddedConfig struct {
	// Configure using the embedded PostgreSQL instance.
	EmbeddedConfig *EmbeddedSetupConfig `protobuf:"bytes,2,opt,name=embedded_config,json=embeddedConfig,proto3,oneof"`
}

func (*SetupAppDatabaseRequest_PostgresConfig) isSetupAppDatabaseRequest_Setup() {}

func (*SetupAppDatabaseRequest_EmbeddedConfig) isSetupAppDatabaseRequest_Setup() {}

type SetupAppDatabaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. The progress event for the current step.
	Event         *SetupProgressEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupAppDatabaseResponse) Reset() {
	*x = SetupAppDatabaseResponse{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupAppDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupAppDatabaseResponse) ProtoMessage() {}

func (x *SetupAppDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupAppDatabaseResponse.ProtoReflect.Descriptor instead.
func (*SetupAppDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{5}
}

func (x *SetupAppDatabaseResponse) GetEvent() *SetupProgressEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type WatchConfigChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigChangesRequest) Reset() {
	*x = WatchConfigChangesRequest{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigChangesRequest) ProtoMessage() {}

func (x *WatchConfigChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigChangesRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigChangesRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{6}
}

type WatchConfigChangesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. The progress event for the current step.
	Event         *SetupProgressEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigChangesResponse) Reset() {
	*x = WatchConfigChangesResponse{}
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigChangesResponse) ProtoMessage() {}

func (x *WatchConfigChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_onboarding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigChangesResponse.ProtoReflect.Descriptor instead.
func (*WatchConfigChangesResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP(), []int{7}
}

func (x *WatchConfigChangesResponse) GetEvent() *SetupProgressEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_querylane_console_v1alpha1_onboarding_proto protoreflect.FileDescriptor

const file_querylane_console_v1alpha1_onboarding_proto_rawDesc = "" +
	"\n" +
	"+querylane/console/v1alpha1/onboarding.proto\x12\x1aquerylane.console.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a(querylane/console/v1alpha1/console.proto\x1a)querylane/console/v1alpha1/instance.proto\"\xde\x01\n" +
	"\x12SetupProgressEvent\x12C\n" +
	"\astep_id\x18\x01 \x01(\x0e2%.querylane.console.v1alpha1.SetupStepB\x03\xe0A\x03R\x06stepId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x03\xe0A\x03R\vdisplayName\x12@\n" +
	"\x05state\x18\x03 \x01(\x0e2%.querylane.console.v1alpha1.StepStateB\x03\xe0A\x03R\x05state\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tB\x03\xe0A\x03R\x05error\"u\n" +
	"\x13EmbeddedSetupConfig\x12&\n" +
	"\x04port\x18\x01 \x01(\x05B\x12\xe0A\x01\xbaH\f\xd8\x01\x01\x1a\a\x18\xff\xff\x03(\x80\bR\x04port\x126\n" +
	"\x04mode\x18\x02 \x01(\tB\"\xe0A\x01\xbaH\x1c\xd8\x01\x01r\x17R\n" +
	"persistentR\tephemeralR\x04mode\"\x1b\n" +
	"\x19GetOnboardingStateRequest\"\xc5\x03\n" +
	"\x1aGetOnboardingStateResponse\x12(\n" +
	"\ris_configured\x18\x01 \x01(\bB\x03\xe0A\x03R\fisConfigured\x12b\n" +
	"\x13app_database_status\x18\x02 \x01(\v2-.querylane.console.v1alpha1.AppDatabaseStatusB\x03\xe0A\x03R\x11appDatabaseStatus\x12 \n" +
	"\thome_path\x18\x03 \x01(\tB\x03\xe0A\x03R\bhomePath\x12-\n" +
	"\x10is_home_writable\x18\x04 \x01(\bB\x03\xe0A\x03R\x0eisHomeWritable\x12f\n" +
	"\x11available_methods\x18\x05 \x03(\x0e2'.querylane.console.v1alpha1.SetupMethodB\x10\xe0A\x03\xbaH\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01R\x10availableMethods\x12-\n" +
	"\x10config_file_path\x18\x06 \x01(\tB\x03\xe0A\x03R\x0econfigFilePath\x121\n" +
	"\x12embedded_data_path\x18\a \x01(\tB\x03\xe0A\x03R\x10embeddedDataPath\"\xd5\x01\n" +
	"\x17SetupAppDatabaseRequest\x12U\n" +
	"\x0fpostgres_config\x18\x01 \x01(\v2*.querylane.console.v1alpha1.PostgresConfigH\x00R\x0epostgresConfig\x12Z\n" +
	"\x0fembedded_config\x18\x02 \x01(\v2/.querylane.console.v1alpha1.EmbeddedSetupConfigH\x00R\x0eembeddedConfigB\a\n" +
	"\x05setup\"e\n" +
	"\x18SetupAppDatabaseResponse\x12I\n" +
	"\x05event\x18\x01 \x01(\v2..querylane.console.v1alpha1.SetupProgressEventB\x03\xe0A\x03R\x05event\"\x1b\n" +
	"\x19WatchConfigChangesRequest\"g\n" +
	"\x1aWatchConfigChangesResponse\x12I\n" +
	"\x05event\x18\x01 \x01(\v2..querylane.console.v1alpha1.SetupProgressEventB\x03\xe0A\x03R\x05event*\x8c\x01\n" +
	"\tStepState\x12\x1a\n" +
	"\x16STEP_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STEP_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16STEP_STATE_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14STEP_STATE_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11STEP_STATE_FAILED\x10\x04*\x89\x02\n" +
	"\tSetupStep\x12\x1a\n" +
	"\x16SETUP_STEP_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSETUP_STEP_STARTING_EMBEDDED\x10\x01\x12\x19\n" +
	"\x15SETUP_STEP_CONNECTING\x10\x02\x12\x18\n" +
	"\x14SETUP_STEP_MIGRATING\x10\x03\x12$\n" +
	" SETUP_STEP_INITIALIZING_SERVICES\x10\x04\x12 \n" +
	"\x1cSETUP_STEP_PERSISTING_CONFIG\x10\x05\x12!\n" +
	"\x1dSETUP_STEP_WAITING_FOR_CONFIG\x10\x06\x12\x1e\n" +
	"\x1aSETUP_STEP_CONFIG_DETECTED\x10\a*\x84\x01\n" +
	"\vSetupMethod\x12\x1c\n" +
	"\x18SETUP_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSETUP_METHOD_UI_CONFIGURED\x10\x01\x12\x1c\n" +
	"\x18SETUP_METHOD_MANUAL_YAML\x10\x02\x12\x19\n" +
	"\x15SETUP_METHOD_EMBEDDED\x10\x032\xa9\x03\n" +
	"\x11OnboardingService\x12\x85\x01\n" +
	"\x12GetOnboardingState\x125.querylane.console.v1alpha1.GetOnboardingStateRequest\x1a6.querylane.console.v1alpha1.GetOnboardingStateResponse\"\x00\x12\x81\x01\n" +
	"\x10SetupAppDatabase\x123.querylane.console.v1alpha1.SetupAppDatabaseRequest\x1a4.querylane.console.v1alpha1.SetupAppDatabaseResponse\"\x000\x01\x12\x87\x01\n" +
	"\x12WatchConfigChanges\x125.querylane.console.v1alpha1.WatchConfigChangesRequest\x1a6.querylane.console.v1alpha1.WatchConfigChangesResponse\"\x000\x01B\x97\x02\n" +
	"\x1ecom.querylane.console.v1alpha1B\x0fOnboardingProtoP\x01ZZgithub.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1;consolev1alpha1\xa2\x02\x03QCX\xaa\x02\x1aQuerylane.Console.V1alpha1\xca\x02\x1aQuerylane\\Console\\V1alpha1\xe2\x02&Querylane\\Console\\V1alpha1\\GPBMetadata\xea\x02\x1cQuerylane::Console::V1alpha1b\x06proto3"

var (
	file_querylane_console_v1alpha1_onboarding_proto_rawDescOnce sync.Once
	file_querylane_console_v1alpha1_onboarding_proto_rawDescData []byte
)

func file_querylane_console_v1alpha1_onboarding_proto_rawDescGZIP() []byte {
	file_querylane_console_v1alpha1_onboarding_proto_rawDescOnce.Do(func() {
		file_querylane_console_v1alpha1_onboarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_onboarding_proto_rawDesc), len(file_querylane_console_v1alpha1_onboarding_proto_rawDesc)))
	})
	return file_querylane_console_v1alpha1_onboarding_proto_rawDescData
}

var file_querylane_console_v1alpha1_onboarding_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_querylane_console_v1alpha1_onboarding_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_querylane_console_v1alpha1_onboarding_proto_goTypes = []any{
	(StepState)(0),                     // 0: querylane.console.v1alpha1.StepState
	(SetupStep)(0),                     // 1: querylane.console.v1alpha1.SetupStep
	(SetupMethod)(0),                   // 2: querylane.console.v1alpha1.SetupMethod
	(*SetupProgressEvent)(nil),         // 3: querylane.console.v1alpha1.SetupProgressEvent
	(*EmbeddedSetupConfig)(nil),        // 4: querylane.console.v1alpha1.EmbeddedSetupConfig
	(*GetOnboardingStateRequest)(nil),  // 5: querylane.console.v1alpha1.GetOnboardingStateRequest
	(*GetOnboardingStateResponse)(nil), // 6: querylane.console.v1alpha1.GetOnboardingStateResponse
	(*SetupAppDatabaseRequest)(nil),    // 7: querylane.console.v1alpha1.SetupAppDatabaseRequest
	(*SetupAppDatabaseResponse)(nil),   // 8: querylane.console.v1alpha1.SetupAppDatabaseResponse
	(*WatchConfigChangesRequest)(nil),  // 9: querylane.console.v1alpha1.WatchConfigChangesRequest
	(*WatchConfigChangesResponse)(nil), // 10: querylane.console.v1alpha1.WatchConfigChangesResponse
	(*AppDatabaseStatus)(nil),          // 11: querylane.console.v1alpha1.AppDatabaseStatus
	(*PostgresConfig)(nil),             // 12: querylane.console.v1alpha1.PostgresConfig
}
var file_querylane_console_v1alpha1_onboarding_proto_depIdxs = []int32{
	1,  // 0: querylane.console.v1alpha1.SetupProgressEvent.step_id:type_name -> querylane.console.v1alpha1.SetupStep
	0,  // 1: querylane.console.v1alpha1.SetupProgressEvent.state:type_name -> querylane.console.v1alpha1.StepState
	11, // 2: querylane.console.v1alpha1.GetOnboardingStateResponse.app_database_status:type_name -> querylane.console.v1alpha1.AppDatabaseStatus
	2,  // 3: querylane.console.v1alpha1.GetOnboardingStateResponse.available_methods:type_name -> querylane.console.v1alpha1.SetupMethod
	12, // 4: querylane.console.v1alpha1.SetupAppDatabaseRequest.postgres_config:type_name -> querylane.console.v1alpha1.PostgresConfig
	4,  // 5: querylane.console.v1alpha1.SetupAppDatabaseRequest.embedded_config:type_name -> querylane.console.v1alpha1.EmbeddedSetupConfig
	3,  // 6: querylane.console.v1alpha1.SetupAppDatabaseResponse.event:type_name -> querylane.console.v1alpha1.SetupProgressEvent
	3,  // 7: querylane.console.v1alpha1.WatchConfigChangesResponse.event:type_name -> querylane.console.v1alpha1.SetupProgressEvent
	5,  // 8: querylane.console.v1alpha1.OnboardingService.GetOnboardingState:input_type -> querylane.console.v1alpha1.GetOnboardingStateRequest
	7,  // 9: querylane.console.v1alpha1.OnboardingService.SetupAppDatabase:input_type -> querylane.console.v1alpha1.SetupAppDatabaseRequest
	9,  // 10: querylane.console.v1alpha1.OnboardingService.WatchConfigChanges:input_type -> querylane.console.v1alpha1.WatchConfigChangesRequest
	6,  // 11: querylane.console.v1alpha1.OnboardingService.GetOnboardingState:output_type -> querylane.console.v1alpha1.GetOnboardingStateResponse
	8,  // 12: querylane.console.v1alpha1.OnboardingService.SetupAppDatabase:output_type -> querylane.console.v1alpha1.SetupAppDatabaseResponse
	10, // 13: querylane.console.v1alpha1.OnboardingService.WatchConfigChanges:output_type -> querylane.console.v1alpha1.WatchConfigChangesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_querylane_console_v1alpha1_onboarding_proto_init() }
func file_querylane_console_v1alpha1_onboarding_proto_init() {
	if File_querylane_console_v1alpha1_onboarding_proto != nil {
		return
	}
	file_querylane_console_v1alpha1_console_proto_init()
	file_querylane_console_v1alpha1_instance_proto_init()
	file_querylane_console_v1alpha1_onboarding_proto_msgTypes[4].OneofWrappers = []any{
		(*SetupAppDatabaseRequest_PostgresConfig)(nil),
		(*SetupAppDatabaseRequest_EmbeddedConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_onboarding_proto_rawDesc), len(file_querylane_console_v1alpha1_onboarding_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_querylane_console_v1alpha1_onboarding_proto_goTypes,
		DependencyIndexes: file_querylane_console_v1alpha1_onboarding_proto_depIdxs,
		EnumInfos:         file_querylane_console_v1alpha1_onboarding_proto_enumTypes,
		MessageInfos:      file_querylane_console_v1alpha1_onboarding_proto_msgTypes,
	}.Build()
	File_querylane_console_v1alpha1_onboarding_proto = out.File
	file_querylane_console_v1alpha1_onboarding_proto_goTypes = nil
	file_querylane_console_v1alpha1_onboarding_proto_depIdxs = nil
}
