// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: querylane/console/v1alpha1/role.proto

package consolev1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The kind of object a grant applies to, normalized from the catalog
// (pg_database, pg_namespace, and pg_class.relkind).
type GrantObjectType int32

const (
	GrantObjectType_GRANT_OBJECT_TYPE_UNSPECIFIED GrantObjectType = 0
	// A database (pg_database.datacl): CONNECT, CREATE, TEMPORARY.
	GrantObjectType_GRANT_OBJECT_TYPE_DATABASE GrantObjectType = 1
	// A schema (pg_namespace.nspacl): USAGE, CREATE.
	GrantObjectType_GRANT_OBJECT_TYPE_SCHEMA GrantObjectType = 2
	// An ordinary or partitioned table.
	GrantObjectType_GRANT_OBJECT_TYPE_TABLE GrantObjectType = 3
	// A view.
	GrantObjectType_GRANT_OBJECT_TYPE_VIEW GrantObjectType = 4
	// A materialized view.
	GrantObjectType_GRANT_OBJECT_TYPE_MATERIALIZED_VIEW GrantObjectType = 5
	// A sequence.
	GrantObjectType_GRANT_OBJECT_TYPE_SEQUENCE GrantObjectType = 6
	// A foreign table.
	GrantObjectType_GRANT_OBJECT_TYPE_FOREIGN_TABLE GrantObjectType = 7
	// A function, procedure, aggregate, or window function (pg_proc.proacl):
	// EXECUTE.
	GrantObjectType_GRANT_OBJECT_TYPE_FUNCTION GrantObjectType = 8
	// A PostgreSQL large object (pg_largeobject_metadata.lomacl): SELECT, UPDATE.
	GrantObjectType_GRANT_OBJECT_TYPE_LARGE_OBJECT GrantObjectType = 9
)

// Enum value maps for GrantObjectType.
var (
	GrantObjectType_name = map[int32]string{
		0: "GRANT_OBJECT_TYPE_UNSPECIFIED",
		1: "GRANT_OBJECT_TYPE_DATABASE",
		2: "GRANT_OBJECT_TYPE_SCHEMA",
		3: "GRANT_OBJECT_TYPE_TABLE",
		4: "GRANT_OBJECT_TYPE_VIEW",
		5: "GRANT_OBJECT_TYPE_MATERIALIZED_VIEW",
		6: "GRANT_OBJECT_TYPE_SEQUENCE",
		7: "GRANT_OBJECT_TYPE_FOREIGN_TABLE",
		8: "GRANT_OBJECT_TYPE_FUNCTION",
		9: "GRANT_OBJECT_TYPE_LARGE_OBJECT",
	}
	GrantObjectType_value = map[string]int32{
		"GRANT_OBJECT_TYPE_UNSPECIFIED":       0,
		"GRANT_OBJECT_TYPE_DATABASE":          1,
		"GRANT_OBJECT_TYPE_SCHEMA":            2,
		"GRANT_OBJECT_TYPE_TABLE":             3,
		"GRANT_OBJECT_TYPE_VIEW":              4,
		"GRANT_OBJECT_TYPE_MATERIALIZED_VIEW": 5,
		"GRANT_OBJECT_TYPE_SEQUENCE":          6,
		"GRANT_OBJECT_TYPE_FOREIGN_TABLE":     7,
		"GRANT_OBJECT_TYPE_FUNCTION":          8,
		"GRANT_OBJECT_TYPE_LARGE_OBJECT":      9,
	}
)

func (x GrantObjectType) Enum() *GrantObjectType {
	p := new(GrantObjectType)
	*p = x
	return p
}

func (x GrantObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrantObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_querylane_console_v1alpha1_role_proto_enumTypes[0].Descriptor()
}

func (GrantObjectType) Type() protoreflect.EnumType {
	return &file_querylane_console_v1alpha1_role_proto_enumTypes[0]
}

func (x GrantObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrantObjectType.Descriptor instead.
func (GrantObjectType) EnumDescriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{0}
}

// The category of object a default privilege applies to, normalized from
// pg_default_acl.defaclobjtype. Defaults target a category of future objects
// rather than a specific existing object.
type DefaultPrivilegeObjectType int32

const (
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_UNSPECIFIED DefaultPrivilegeObjectType = 0
	// Tables and views ('r').
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_TABLES DefaultPrivilegeObjectType = 1
	// Sequences ('S').
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_SEQUENCES DefaultPrivilegeObjectType = 2
	// Functions and procedures ('f').
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_FUNCTIONS DefaultPrivilegeObjectType = 3
	// Types and domains ('T').
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_TYPES DefaultPrivilegeObjectType = 4
	// Schemas ('n').
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_SCHEMAS DefaultPrivilegeObjectType = 5
	// Large objects ('L').
	DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_LARGE_OBJECTS DefaultPrivilegeObjectType = 6
)

// Enum value maps for DefaultPrivilegeObjectType.
var (
	DefaultPrivilegeObjectType_name = map[int32]string{
		0: "DEFAULT_PRIVILEGE_OBJECT_TYPE_UNSPECIFIED",
		1: "DEFAULT_PRIVILEGE_OBJECT_TYPE_TABLES",
		2: "DEFAULT_PRIVILEGE_OBJECT_TYPE_SEQUENCES",
		3: "DEFAULT_PRIVILEGE_OBJECT_TYPE_FUNCTIONS",
		4: "DEFAULT_PRIVILEGE_OBJECT_TYPE_TYPES",
		5: "DEFAULT_PRIVILEGE_OBJECT_TYPE_SCHEMAS",
		6: "DEFAULT_PRIVILEGE_OBJECT_TYPE_LARGE_OBJECTS",
	}
	DefaultPrivilegeObjectType_value = map[string]int32{
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_UNSPECIFIED":   0,
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_TABLES":        1,
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_SEQUENCES":     2,
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_FUNCTIONS":     3,
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_TYPES":         4,
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_SCHEMAS":       5,
		"DEFAULT_PRIVILEGE_OBJECT_TYPE_LARGE_OBJECTS": 6,
	}
)

func (x DefaultPrivilegeObjectType) Enum() *DefaultPrivilegeObjectType {
	p := new(DefaultPrivilegeObjectType)
	*p = x
	return p
}

func (x DefaultPrivilegeObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultPrivilegeObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_querylane_console_v1alpha1_role_proto_enumTypes[1].Descriptor()
}

func (DefaultPrivilegeObjectType) Type() protoreflect.EnumType {
	return &file_querylane_console_v1alpha1_role_proto_enumTypes[1]
}

func (x DefaultPrivilegeObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultPrivilegeObjectType.Descriptor instead.
func (DefaultPrivilegeObjectType) EnumDescriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{1}
}

// A Role represents a PostgreSQL server-level role in an Instance.
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only identifier. The unique resource name of the role.
	// Format: instances/{instance}/roles/{role}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output-only. The exact PostgreSQL role name (rolname). May contain
	// characters not legal in the resource-name segment, which is why it is
	// surfaced separately from `name`.
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	// Output-only. PostgreSQL role attributes from pg_roles. Whether the role
	// can be used to log in is exposed via `attributes.can_login`.
	Attributes *RoleAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Output-only. Direct parent roles this role is a member of.
	MemberOf []*RoleMembership `protobuf:"bytes,4,rep,name=member_of,json=memberOf,proto3" json:"member_of,omitempty"`
	// Output-only. Whether this appears to be a PostgreSQL-managed system role.
	IsSystemRole bool `protobuf:"varint,5,opt,name=is_system_role,json=isSystemRole,proto3" json:"is_system_role,omitempty"`
	// Output-only. The COMMENT ON ROLE description (pg_shdescription via
	// pg_authid). Empty when the role has no comment.
	Comment       string `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *Role) GetAttributes() *RoleAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Role) GetMemberOf() []*RoleMembership {
	if x != nil {
		return x.MemberOf
	}
	return nil
}

func (x *Role) GetIsSystemRole() bool {
	if x != nil {
		return x.IsSystemRole
	}
	return false
}

func (x *Role) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// PostgreSQL role attributes from pg_roles.
type RoleAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. Whether the role may log in (rolcanlogin).
	CanLogin bool `protobuf:"varint,1,opt,name=can_login,json=canLogin,proto3" json:"can_login,omitempty"`
	// Output-only. Whether the role has superuser privileges (rolsuper).
	IsSuperuser bool `protobuf:"varint,2,opt,name=is_superuser,json=isSuperuser,proto3" json:"is_superuser,omitempty"`
	// Output-only. Whether the role may create new databases (rolcreatedb).
	CanCreateDatabase bool `protobuf:"varint,3,opt,name=can_create_database,json=canCreateDatabase,proto3" json:"can_create_database,omitempty"`
	// Output-only. Whether the role may create new roles (rolcreaterole).
	CanCreateRole bool `protobuf:"varint,4,opt,name=can_create_role,json=canCreateRole,proto3" json:"can_create_role,omitempty"`
	// Output-only. Whether the role may initiate streaming replication
	// and put the system in and out of backup mode (rolreplication).
	CanReplicate bool `protobuf:"varint,5,opt,name=can_replicate,json=canReplicate,proto3" json:"can_replicate,omitempty"`
	// Output-only. Whether the role bypasses every row-level security
	// policy (rolbypassrls).
	BypassesRls bool `protobuf:"varint,6,opt,name=bypasses_rls,json=bypassesRls,proto3" json:"bypasses_rls,omitempty"`
	// Output-only. Whether the role automatically inherits privileges from
	// roles it is a member of (rolinherit).
	InheritsByDefault bool `protobuf:"varint,7,opt,name=inherits_by_default,json=inheritsByDefault,proto3" json:"inherits_by_default,omitempty"`
	// Output-only. Maximum concurrent connections allowed for the role.
	// -1 means no limit (rolconnlimit).
	ConnectionLimit int32 `protobuf:"varint,8,opt,name=connection_limit,json=connectionLimit,proto3" json:"connection_limit,omitempty"`
	// Output-only. The time after which the role's password is no longer valid
	// (rolvaliduntil). Unset when there is no expiry, including when the catalog
	// stores 'infinity'.
	ValidUntil *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	// Output-only. Per-role default run-time configuration settings applied at
	// login (rolconfig), each formatted as "parameter=value"
	// (e.g. "work_mem=64MB").
	ConfigParameters []string `protobuf:"bytes,10,rep,name=config_parameters,json=configParameters,proto3" json:"config_parameters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoleAttributes) Reset() {
	*x = RoleAttributes{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAttributes) ProtoMessage() {}

func (x *RoleAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAttributes.ProtoReflect.Descriptor instead.
func (*RoleAttributes) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleAttributes) GetCanLogin() bool {
	if x != nil {
		return x.CanLogin
	}
	return false
}

func (x *RoleAttributes) GetIsSuperuser() bool {
	if x != nil {
		return x.IsSuperuser
	}
	return false
}

func (x *RoleAttributes) GetCanCreateDatabase() bool {
	if x != nil {
		return x.CanCreateDatabase
	}
	return false
}

func (x *RoleAttributes) GetCanCreateRole() bool {
	if x != nil {
		return x.CanCreateRole
	}
	return false
}

func (x *RoleAttributes) GetCanReplicate() bool {
	if x != nil {
		return x.CanReplicate
	}
	return false
}

func (x *RoleAttributes) GetBypassesRls() bool {
	if x != nil {
		return x.BypassesRls
	}
	return false
}

func (x *RoleAttributes) GetInheritsByDefault() bool {
	if x != nil {
		return x.InheritsByDefault
	}
	return false
}

func (x *RoleAttributes) GetConnectionLimit() int32 {
	if x != nil {
		return x.ConnectionLimit
	}
	return 0
}

func (x *RoleAttributes) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *RoleAttributes) GetConfigParameters() []string {
	if x != nil {
		return x.ConfigParameters
	}
	return nil
}

// A direct role membership edge from pg_auth_members.
type RoleMembership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. Resource name of the parent role this role is a member of.
	// Format: instances/{instance}/roles/{role}
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Output-only. The exact PostgreSQL parent role name (rolname).
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	// Output-only. Whether this role may grant the membership to others.
	AdminOption bool `protobuf:"varint,3,opt,name=admin_option,json=adminOption,proto3" json:"admin_option,omitempty"`
	// Output-only. Whether privileges inherit through this membership by default.
	InheritOption bool `protobuf:"varint,4,opt,name=inherit_option,json=inheritOption,proto3" json:"inherit_option,omitempty"`
	// Output-only. Whether SET ROLE may use this membership.
	SetOption bool `protobuf:"varint,5,opt,name=set_option,json=setOption,proto3" json:"set_option,omitempty"`
	// Output-only. Resource name of the role that granted the membership.
	// Empty when the grantor is unknown.
	// Format: instances/{instance}/roles/{role}
	GrantorRole string `protobuf:"bytes,6,opt,name=grantor_role,json=grantorRole,proto3" json:"grantor_role,omitempty"`
	// Output-only. The exact PostgreSQL role name that granted the membership.
	Grantor       string `protobuf:"bytes,7,opt,name=grantor,proto3" json:"grantor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleMembership) Reset() {
	*x = RoleMembership{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleMembership) ProtoMessage() {}

func (x *RoleMembership) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleMembership.ProtoReflect.Descriptor instead.
func (*RoleMembership) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleMembership) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RoleMembership) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleMembership) GetAdminOption() bool {
	if x != nil {
		return x.AdminOption
	}
	return false
}

func (x *RoleMembership) GetInheritOption() bool {
	if x != nil {
		return x.InheritOption
	}
	return false
}

func (x *RoleMembership) GetSetOption() bool {
	if x != nil {
		return x.SetOption
	}
	return false
}

func (x *RoleMembership) GetGrantorRole() string {
	if x != nil {
		return x.GrantorRole
	}
	return ""
}

func (x *RoleMembership) GetGrantor() string {
	if x != nil {
		return x.Grantor
	}
	return ""
}

// A single object-level privilege grant within a database, derived from catalog
// ACLs. This is a computed value (no resource name). The grantee is implied by
// the RPC that returns it: ListRoleGrants returns privileges held directly by a
// specific role, while ListPublicGrants returns privileges held by PUBLIC.
// Owner-implicit privileges and membership inheritance are never reported here.
type ObjectGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. The kind of object the privilege applies to.
	ObjectType GrantObjectType `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=querylane.console.v1alpha1.GrantObjectType" json:"object_type,omitempty"`
	// Output-only. The schema containing the object. Empty for DATABASE grants;
	// for SCHEMA grants this is the schema itself.
	SchemaName string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// Output-only. The bare object name (relation or sequence name; the database
	// name for DATABASE grants). Empty for SCHEMA grants, where the target is the
	// schema named by `schema_name`.
	ObjectName string `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	// Output-only. The PostgreSQL privilege keyword (e.g. "SELECT", "USAGE").
	Privilege string `protobuf:"bytes,4,opt,name=privilege,proto3" json:"privilege,omitempty"`
	// Output-only. Whether the role may grant this privilege to others
	// (WITH GRANT OPTION).
	WithGrantOption bool `protobuf:"varint,5,opt,name=with_grant_option,json=withGrantOption,proto3" json:"with_grant_option,omitempty"`
	// Output-only. The exact PostgreSQL role name that granted the privilege.
	// Empty when the grantor is unknown.
	Grantor       string `protobuf:"bytes,6,opt,name=grantor,proto3" json:"grantor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectGrant) Reset() {
	*x = ObjectGrant{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGrant) ProtoMessage() {}

func (x *ObjectGrant) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGrant.ProtoReflect.Descriptor instead.
func (*ObjectGrant) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectGrant) GetObjectType() GrantObjectType {
	if x != nil {
		return x.ObjectType
	}
	return GrantObjectType_GRANT_OBJECT_TYPE_UNSPECIFIED
}

func (x *ObjectGrant) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *ObjectGrant) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *ObjectGrant) GetPrivilege() string {
	if x != nil {
		return x.Privilege
	}
	return ""
}

func (x *ObjectGrant) GetWithGrantOption() bool {
	if x != nil {
		return x.WithGrantOption
	}
	return false
}

func (x *ObjectGrant) GetGrantor() string {
	if x != nil {
		return x.Grantor
	}
	return ""
}

// An object owned by a role within a database. Owners implicitly hold every
// privilege on the objects they own, so these are not reported by
// ListRoleGrants. Computed from pg_class/pg_namespace/pg_proc owner columns.
type OwnedObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. The kind of object owned. DATABASE represents ownership of the
	// connected database itself (pg_database.datdba); all other types are objects
	// within that database.
	ObjectType GrantObjectType `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=querylane.console.v1alpha1.GrantObjectType" json:"object_type,omitempty"`
	// Output-only. The schema containing the object. For SCHEMA objects this is
	// the schema itself. Empty for DATABASE.
	SchemaName string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// Output-only. The bare object name (the database name for DATABASE). Empty
	// for SCHEMA objects, where the target is the schema named by `schema_name`.
	// For functions this includes the identity arguments to disambiguate
	// overloads.
	ObjectName    string `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedObject) Reset() {
	*x = OwnedObject{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedObject) ProtoMessage() {}

func (x *OwnedObject) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedObject.ProtoReflect.Descriptor instead.
func (*OwnedObject) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{4}
}

func (x *OwnedObject) GetObjectType() GrantObjectType {
	if x != nil {
		return x.ObjectType
	}
	return GrantObjectType_GRANT_OBJECT_TYPE_UNSPECIFIED
}

func (x *OwnedObject) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *OwnedObject) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

// A default privilege (ALTER DEFAULT PRIVILEGES) that grants access to a role
// on objects of a given category created later by `creator_role`. Computed from
// pg_default_acl; reports the rows where the target role is the grantee.
type RoleDefaultPrivilege struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. Resource name of the role whose newly created objects trigger
	// this default grant — the FOR ROLE in ALTER DEFAULT PRIVILEGES
	// (pg_default_acl.defaclrole). Format: instances/{instance}/roles/{role}
	CreatorRole string `protobuf:"bytes,1,opt,name=creator_role,json=creatorRole,proto3" json:"creator_role,omitempty"`
	// Output-only. The exact PostgreSQL name of the creator role.
	CreatorRoleName string `protobuf:"bytes,2,opt,name=creator_role_name,json=creatorRoleName,proto3" json:"creator_role_name,omitempty"`
	// Output-only. The category of future object the default applies to.
	ObjectType DefaultPrivilegeObjectType `protobuf:"varint,3,opt,name=object_type,json=objectType,proto3,enum=querylane.console.v1alpha1.DefaultPrivilegeObjectType" json:"object_type,omitempty"`
	// Output-only. The schema the default is scoped to. Empty when it applies in
	// every schema (pg_default_acl.defaclnamespace = 0).
	SchemaName string `protobuf:"bytes,4,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// Output-only. The PostgreSQL privilege keyword granted (e.g. "SELECT").
	Privilege string `protobuf:"bytes,5,opt,name=privilege,proto3" json:"privilege,omitempty"`
	// Output-only. Whether the role may grant this privilege onward
	// (WITH GRANT OPTION).
	WithGrantOption bool `protobuf:"varint,6,opt,name=with_grant_option,json=withGrantOption,proto3" json:"with_grant_option,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoleDefaultPrivilege) Reset() {
	*x = RoleDefaultPrivilege{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDefaultPrivilege) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDefaultPrivilege) ProtoMessage() {}

func (x *RoleDefaultPrivilege) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDefaultPrivilege.ProtoReflect.Descriptor instead.
func (*RoleDefaultPrivilege) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{5}
}

func (x *RoleDefaultPrivilege) GetCreatorRole() string {
	if x != nil {
		return x.CreatorRole
	}
	return ""
}

func (x *RoleDefaultPrivilege) GetCreatorRoleName() string {
	if x != nil {
		return x.CreatorRoleName
	}
	return ""
}

func (x *RoleDefaultPrivilege) GetObjectType() DefaultPrivilegeObjectType {
	if x != nil {
		return x.ObjectType
	}
	return DefaultPrivilegeObjectType_DEFAULT_PRIVILEGE_OBJECT_TYPE_UNSPECIFIED
}

func (x *RoleDefaultPrivilege) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *RoleDefaultPrivilege) GetPrivilege() string {
	if x != nil {
		return x.Privilege
	}
	return ""
}

func (x *RoleDefaultPrivilege) GetWithGrantOption() bool {
	if x != nil {
		return x.WithGrantOption
	}
	return false
}

type ListRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parent Instance from which to list roles.
	// Format: instances/{instance}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of roles to return. Server may return fewer.
	// If unspecified or 0, server will choose a reasonable default (typically 50).
	// Maximum value is 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListRoles` call.
	// Provide this to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Reserved for future AIP-160 filtering support.
	// The server currently rejects non-empty filters.
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Ordering expression following AIP-132 syntax.
	// Supported fields: name
	// Default: "name asc"
	//
	// Examples:
	//   - "name asc"
	//   - "name desc"
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{6}
}

func (x *ListRolesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRolesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRolesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of roles found in the instance.
	Roles []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	// A token to retrieve the next page of results.
	// If this field is empty, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{7}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the role to retrieve.
	// Format: instances/{instance}/roles/{role}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved role resource.
	Role          *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListRoleGrantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The Role whose grants to list.
	// Format: instances/{instance}/roles/{role}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The Database to inspect for object privileges. Object privileges
	// are per-database, so a database scope is required. Must belong to the same
	// instance as `parent`.
	// Format: instances/{instance}/databases/{database}
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// Optional. The maximum number of grants to return. Server may return fewer.
	// If unspecified or 0, server will choose a reasonable default (typically 50).
	// Maximum value is 1000.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListRoleGrants` call.
	// Provide this to retrieve the next page of results.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter expression (an AIP-160 subset: `=`, `!=`, the `:`
	// case-insensitive substring operator, combined with `AND`). Values are
	// quoted strings. Filterable fields:
	//   - object_type (`=`/`!=` only, no `:` substring): one of DATABASE, SCHEMA, TABLE, VIEW,
	//     MATERIALIZED_VIEW, SEQUENCE, FOREIGN_TABLE, FUNCTION, LARGE_OBJECT
	//   - object_name, schema_name, privilege, grantor (string; support the
	//     `:` substring operator)
	//
	// Examples:
	//   - object_type = "TABLE"
	//   - privilege = "SELECT" AND schema_name = "public"
	//   - object_name:"orders"
	Filter string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Ordering expression following AIP-132 syntax.
	// Supported fields: schema_name, object_name, privilege
	// Default: "schema_name asc, object_name asc, privilege asc"
	OrderBy       string `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleGrantsRequest) Reset() {
	*x = ListRoleGrantsRequest{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleGrantsRequest) ProtoMessage() {}

func (x *ListRoleGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListRoleGrantsRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleGrantsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListRoleGrantsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ListRoleGrantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleGrantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoleGrantsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRoleGrantsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListRoleGrantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of grants held by the role in the database.
	Grants []*ObjectGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	// A token to retrieve the next page of results.
	// If this field is empty, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleGrantsResponse) Reset() {
	*x = ListRoleGrantsResponse{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleGrantsResponse) ProtoMessage() {}

func (x *ListRoleGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleGrantsResponse.ProtoReflect.Descriptor instead.
func (*ListRoleGrantsResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoleGrantsResponse) GetGrants() []*ObjectGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *ListRoleGrantsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListRoleOwnedObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The Role whose owned objects to list.
	// Format: instances/{instance}/roles/{role}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The Database to inspect for owned objects. Ownership is
	// per-database, so a database scope is required. Must belong to the same
	// instance as `parent`.
	// Format: instances/{instance}/databases/{database}
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// Optional. The maximum number of objects to return. Server may return fewer.
	// If unspecified or 0, server will choose a reasonable default (typically 50).
	// Maximum value is 1000.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListRoleOwnedObjects` call.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter expression (an AIP-160 subset: `=`, `!=`, the `:`
	// case-insensitive substring operator, combined with `AND`). Values are
	// quoted strings. Filterable fields:
	//   - object_type (`=`/`!=` only, no `:` substring): one of DATABASE, SCHEMA, TABLE, VIEW,
	//     MATERIALIZED_VIEW, SEQUENCE, FOREIGN_TABLE, FUNCTION, LARGE_OBJECT
	//   - object_name, schema_name (string; support the `:` substring operator)
	//
	// Examples:
	//   - object_type = "TABLE"
	//   - object_name:"orders"
	//   - object_type = "VIEW" AND object_name:"user"
	Filter string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Ordering expression following AIP-132 syntax.
	// Supported fields: schema_name, object_name
	// Default: "schema_name asc, object_name asc"
	OrderBy       string `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleOwnedObjectsRequest) Reset() {
	*x = ListRoleOwnedObjectsRequest{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleOwnedObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleOwnedObjectsRequest) ProtoMessage() {}

func (x *ListRoleOwnedObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleOwnedObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListRoleOwnedObjectsRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{12}
}

func (x *ListRoleOwnedObjectsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListRoleOwnedObjectsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ListRoleOwnedObjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleOwnedObjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoleOwnedObjectsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRoleOwnedObjectsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListRoleOwnedObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of objects owned by the role in the database.
	OwnedObjects []*OwnedObject `protobuf:"bytes,1,rep,name=owned_objects,json=ownedObjects,proto3" json:"owned_objects,omitempty"`
	// A token to retrieve the next page of results.
	// If this field is empty, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleOwnedObjectsResponse) Reset() {
	*x = ListRoleOwnedObjectsResponse{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleOwnedObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleOwnedObjectsResponse) ProtoMessage() {}

func (x *ListRoleOwnedObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleOwnedObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListRoleOwnedObjectsResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{13}
}

func (x *ListRoleOwnedObjectsResponse) GetOwnedObjects() []*OwnedObject {
	if x != nil {
		return x.OwnedObjects
	}
	return nil
}

func (x *ListRoleOwnedObjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListRoleDefaultPrivilegesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The Role that receives the default privileges.
	// Format: instances/{instance}/roles/{role}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The Database to inspect. Default privileges are per-database, so a
	// database scope is required. Must belong to the same instance as `parent`.
	// Format: instances/{instance}/databases/{database}
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// Optional. The maximum number of rows to return. Server may return fewer.
	// If unspecified or 0, server will choose a reasonable default (typically 50).
	// Maximum value is 1000.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token from a previous `ListRoleDefaultPrivileges` call.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter expression (an AIP-160 subset: `=`, `!=`, the `:`
	// case-insensitive substring operator, combined with `AND`). Values are
	// quoted strings. Filterable fields:
	//   - object_type (`=`/`!=` only, no `:` substring): one of TABLES, SEQUENCES, FUNCTIONS,
	//     TYPES, SCHEMAS, LARGE_OBJECTS
	//   - privilege, schema_name, creator_role_name (string; support the `:`
	//     substring operator)
	//
	// Examples:
	//   - object_type = "TABLES"
	//   - privilege = "SELECT" AND schema_name:"public"
	Filter string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Ordering expression following AIP-132 syntax.
	// Supported fields: creator_role_name, schema_name, object_type, privilege
	// Default: "creator_role_name asc, schema_name asc, object_type asc, privilege asc"
	OrderBy       string `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleDefaultPrivilegesRequest) Reset() {
	*x = ListRoleDefaultPrivilegesRequest{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleDefaultPrivilegesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleDefaultPrivilegesRequest) ProtoMessage() {}

func (x *ListRoleDefaultPrivilegesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleDefaultPrivilegesRequest.ProtoReflect.Descriptor instead.
func (*ListRoleDefaultPrivilegesRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{14}
}

func (x *ListRoleDefaultPrivilegesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListRoleDefaultPrivilegesRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ListRoleDefaultPrivilegesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleDefaultPrivilegesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoleDefaultPrivilegesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRoleDefaultPrivilegesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListRoleDefaultPrivilegesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of default privileges that grant access to the role.
	DefaultPrivileges []*RoleDefaultPrivilege `protobuf:"bytes,1,rep,name=default_privileges,json=defaultPrivileges,proto3" json:"default_privileges,omitempty"`
	// A token to retrieve the next page of results.
	// If this field is empty, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleDefaultPrivilegesResponse) Reset() {
	*x = ListRoleDefaultPrivilegesResponse{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleDefaultPrivilegesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleDefaultPrivilegesResponse) ProtoMessage() {}

func (x *ListRoleDefaultPrivilegesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleDefaultPrivilegesResponse.ProtoReflect.Descriptor instead.
func (*ListRoleDefaultPrivilegesResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{15}
}

func (x *ListRoleDefaultPrivilegesResponse) GetDefaultPrivileges() []*RoleDefaultPrivilege {
	if x != nil {
		return x.DefaultPrivileges
	}
	return nil
}

func (x *ListRoleDefaultPrivilegesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListPublicGrantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The Database whose PUBLIC grants to list. PUBLIC grants are
	// per-database and apply to every role.
	// Format: instances/{instance}/databases/{database}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of grants to return. Server may return fewer.
	// If unspecified or 0, server will choose a reasonable default (typically 50).
	// Maximum value is 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListPublicGrants` call.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter expression (an AIP-160 subset: `=`, `!=`, the `:`
	// case-insensitive substring operator, combined with `AND`). Values are
	// quoted strings. Filterable fields:
	//   - object_type (`=`/`!=` only, no `:` substring): one of DATABASE, SCHEMA, TABLE, VIEW,
	//     MATERIALIZED_VIEW, SEQUENCE, FOREIGN_TABLE, FUNCTION, LARGE_OBJECT
	//   - object_name, schema_name, privilege, grantor (string; support the
	//     `:` substring operator)
	//
	// Examples:
	//   - privilege = "CONNECT"
	//   - object_type = "TABLE" AND object_name:"orders"
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Ordering expression following AIP-132 syntax.
	// Supported fields: schema_name, object_name, privilege
	// Default: "schema_name asc, object_name asc, privilege asc"
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicGrantsRequest) Reset() {
	*x = ListPublicGrantsRequest{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicGrantsRequest) ProtoMessage() {}

func (x *ListPublicGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListPublicGrantsRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{16}
}

func (x *ListPublicGrantsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListPublicGrantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPublicGrantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPublicGrantsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListPublicGrantsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListPublicGrantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of privileges granted to PUBLIC in the database.
	Grants []*ObjectGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	// A token to retrieve the next page of results.
	// If this field is empty, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicGrantsResponse) Reset() {
	*x = ListPublicGrantsResponse{}
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicGrantsResponse) ProtoMessage() {}

func (x *ListPublicGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_role_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicGrantsResponse.ProtoReflect.Descriptor instead.
func (*ListPublicGrantsResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_role_proto_rawDescGZIP(), []int{17}
}

func (x *ListPublicGrantsResponse) GetGrants() []*ObjectGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *ListPublicGrantsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_querylane_console_v1alpha1_role_proto protoreflect.FileDescriptor

const file_querylane_console_v1alpha1_role_proto_rawDesc = "" +
	"\n" +
	"%querylane/console/v1alpha1/role.proto\x12\x1aquerylane.console.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x02\n" +
	"\x04Role\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\bR\x04name\x12 \n" +
	"\trole_name\x18\x02 \x01(\tB\x03\xe0A\x03R\broleName\x12O\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2*.querylane.console.v1alpha1.RoleAttributesB\x03\xe0A\x03R\n" +
	"attributes\x12L\n" +
	"\tmember_of\x18\x04 \x03(\v2*.querylane.console.v1alpha1.RoleMembershipB\x03\xe0A\x03R\bmemberOf\x12)\n" +
	"\x0eis_system_role\x18\x05 \x01(\bB\x03\xe0A\x03R\fisSystemRole\x12\x1d\n" +
	"\acomment\x18\x06 \x01(\tB\x03\xe0A\x03R\acomment:O\xeaAL\n" +
	"\x1aconsole.querylane.dev/Role\x12!instances/{instance}/roles/{role}*\x05roles2\x04role\"\xe7\x03\n" +
	"\x0eRoleAttributes\x12 \n" +
	"\tcan_login\x18\x01 \x01(\bB\x03\xe0A\x03R\bcanLogin\x12&\n" +
	"\fis_superuser\x18\x02 \x01(\bB\x03\xe0A\x03R\visSuperuser\x123\n" +
	"\x13can_create_database\x18\x03 \x01(\bB\x03\xe0A\x03R\x11canCreateDatabase\x12+\n" +
	"\x0fcan_create_role\x18\x04 \x01(\bB\x03\xe0A\x03R\rcanCreateRole\x12(\n" +
	"\rcan_replicate\x18\x05 \x01(\bB\x03\xe0A\x03R\fcanReplicate\x12&\n" +
	"\fbypasses_rls\x18\x06 \x01(\bB\x03\xe0A\x03R\vbypassesRls\x123\n" +
	"\x13inherits_by_default\x18\a \x01(\bB\x03\xe0A\x03R\x11inheritsByDefault\x12.\n" +
	"\x10connection_limit\x18\b \x01(\x05B\x03\xe0A\x03R\x0fconnectionLimit\x12@\n" +
	"\vvalid_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"validUntil\x120\n" +
	"\x11config_parameters\x18\n" +
	" \x03(\tB\x03\xe0A\x03R\x10configParameters\"\xc8\x02\n" +
	"\x0eRoleMembership\x126\n" +
	"\x04role\x18\x01 \x01(\tB\"\xe0A\x03\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/RoleR\x04role\x12 \n" +
	"\trole_name\x18\x02 \x01(\tB\x03\xe0A\x03R\broleName\x12&\n" +
	"\fadmin_option\x18\x03 \x01(\bB\x03\xe0A\x03R\vadminOption\x12*\n" +
	"\x0einherit_option\x18\x04 \x01(\bB\x03\xe0A\x03R\rinheritOption\x12\"\n" +
	"\n" +
	"set_option\x18\x05 \x01(\bB\x03\xe0A\x03R\tsetOption\x12E\n" +
	"\fgrantor_role\x18\x06 \x01(\tB\"\xe0A\x03\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/RoleR\vgrantorRole\x12\x1d\n" +
	"\agrantor\x18\a \x01(\tB\x03\xe0A\x03R\agrantor\"\x9f\x02\n" +
	"\vObjectGrant\x12Q\n" +
	"\vobject_type\x18\x01 \x01(\x0e2+.querylane.console.v1alpha1.GrantObjectTypeB\x03\xe0A\x03R\n" +
	"objectType\x12$\n" +
	"\vschema_name\x18\x02 \x01(\tB\x03\xe0A\x03R\n" +
	"schemaName\x12$\n" +
	"\vobject_name\x18\x03 \x01(\tB\x03\xe0A\x03R\n" +
	"objectName\x12!\n" +
	"\tprivilege\x18\x04 \x01(\tB\x03\xe0A\x03R\tprivilege\x12/\n" +
	"\x11with_grant_option\x18\x05 \x01(\bB\x03\xe0A\x03R\x0fwithGrantOption\x12\x1d\n" +
	"\agrantor\x18\x06 \x01(\tB\x03\xe0A\x03R\agrantor\"\xac\x01\n" +
	"\vOwnedObject\x12Q\n" +
	"\vobject_type\x18\x01 \x01(\x0e2+.querylane.console.v1alpha1.GrantObjectTypeB\x03\xe0A\x03R\n" +
	"objectType\x12$\n" +
	"\vschema_name\x18\x02 \x01(\tB\x03\xe0A\x03R\n" +
	"schemaName\x12$\n" +
	"\vobject_name\x18\x03 \x01(\tB\x03\xe0A\x03R\n" +
	"objectName\"\xe6\x02\n" +
	"\x14RoleDefaultPrivilege\x12E\n" +
	"\fcreator_role\x18\x01 \x01(\tB\"\xe0A\x03\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/RoleR\vcreatorRole\x12/\n" +
	"\x11creator_role_name\x18\x02 \x01(\tB\x03\xe0A\x03R\x0fcreatorRoleName\x12\\\n" +
	"\vobject_type\x18\x03 \x01(\x0e26.querylane.console.v1alpha1.DefaultPrivilegeObjectTypeB\x03\xe0A\x03R\n" +
	"objectType\x12$\n" +
	"\vschema_name\x18\x04 \x01(\tB\x03\xe0A\x03R\n" +
	"schemaName\x12!\n" +
	"\tprivilege\x18\x05 \x01(\tB\x03\xe0A\x03R\tprivilege\x12/\n" +
	"\x11with_grant_option\x18\x06 \x01(\bB\x03\xe0A\x03R\x0fwithGrantOption\"\x96\x02\n" +
	"\x10ListRolesRequest\x12u\n" +
	"\x06parent\x18\x01 \x01(\tB]\xe0A\x02\xfaA \n" +
	"\x1econsole.querylane.dev/Instance\xbaH4r220^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?$R\x06parent\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tB\x03\xe0A\x01R\aorderBy\"s\n" +
	"\x11ListRolesResponse\x126\n" +
	"\x05roles\x18\x01 \x03(\v2 .querylane.console.v1alpha1.RoleR\x05roles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8e\x01\n" +
	"\x0eGetRoleRequest\x12|\n" +
	"\x04name\x18\x01 \x01(\tBh\xe0A\x02\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/Role\xbaHC\xc8\x01\x01r>2<^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/roles/[^/]+$R\x04name\"G\n" +
	"\x0fGetRoleResponse\x124\n" +
	"\x04role\x18\x01 \x01(\v2 .querylane.console.v1alpha1.RoleR\x04role\"\xb6\x03\n" +
	"\x15ListRoleGrantsRequest\x12\x80\x01\n" +
	"\x06parent\x18\x01 \x01(\tBh\xe0A\x02\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/Role\xbaHC\xc8\x01\x01r>2<^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/roles/[^/]+$R\x06parent\x12\x8c\x01\n" +
	"\bdatabase\x18\x02 \x01(\tBp\xe0A\x02\xfaA \n" +
	"\x1econsole.querylane.dev/Database\xbaHG\xc8\x01\x01rB2@^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/databases/[^/]+$R\bdatabase\x12*\n" +
	"\tpage_size\x18\x03 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x06 \x01(\tB\x03\xe0A\x01R\aorderBy\"\x81\x01\n" +
	"\x16ListRoleGrantsResponse\x12?\n" +
	"\x06grants\x18\x01 \x03(\v2'.querylane.console.v1alpha1.ObjectGrantR\x06grants\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xbc\x03\n" +
	"\x1bListRoleOwnedObjectsRequest\x12\x80\x01\n" +
	"\x06parent\x18\x01 \x01(\tBh\xe0A\x02\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/Role\xbaHC\xc8\x01\x01r>2<^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/roles/[^/]+$R\x06parent\x12\x8c\x01\n" +
	"\bdatabase\x18\x02 \x01(\tBp\xe0A\x02\xfaA \n" +
	"\x1econsole.querylane.dev/Database\xbaHG\xc8\x01\x01rB2@^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/databases/[^/]+$R\bdatabase\x12*\n" +
	"\tpage_size\x18\x03 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x06 \x01(\tB\x03\xe0A\x01R\aorderBy\"\x94\x01\n" +
	"\x1cListRoleOwnedObjectsResponse\x12L\n" +
	"\rowned_objects\x18\x01 \x03(\v2'.querylane.console.v1alpha1.OwnedObjectR\fownedObjects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc1\x03\n" +
	" ListRoleDefaultPrivilegesRequest\x12\x80\x01\n" +
	"\x06parent\x18\x01 \x01(\tBh\xe0A\x02\xfaA\x1c\n" +
	"\x1aconsole.querylane.dev/Role\xbaHC\xc8\x01\x01r>2<^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/roles/[^/]+$R\x06parent\x12\x8c\x01\n" +
	"\bdatabase\x18\x02 \x01(\tBp\xe0A\x02\xfaA \n" +
	"\x1econsole.querylane.dev/Database\xbaHG\xc8\x01\x01rB2@^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/databases/[^/]+$R\bdatabase\x12*\n" +
	"\tpage_size\x18\x03 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x06 \x01(\tB\x03\xe0A\x01R\aorderBy\"\xac\x01\n" +
	"!ListRoleDefaultPrivilegesResponse\x12_\n" +
	"\x12default_privileges\x18\x01 \x03(\v20.querylane.console.v1alpha1.RoleDefaultPrivilegeR\x11defaultPrivileges\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb1\x02\n" +
	"\x17ListPublicGrantsRequest\x12\x88\x01\n" +
	"\x06parent\x18\x01 \x01(\tBp\xe0A\x02\xfaA \n" +
	"\x1econsole.querylane.dev/Database\xbaHG\xc8\x01\x01rB2@^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/databases/[^/]+$R\x06parent\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tB\x03\xe0A\x01R\aorderBy\"\x83\x01\n" +
	"\x18ListPublicGrantsResponse\x12?\n" +
	"\x06grants\x18\x01 \x03(\v2'.querylane.console.v1alpha1.ObjectGrantR\x06grants\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\xdd\x02\n" +
	"\x0fGrantObjectType\x12!\n" +
	"\x1dGRANT_OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aGRANT_OBJECT_TYPE_DATABASE\x10\x01\x12\x1c\n" +
	"\x18GRANT_OBJECT_TYPE_SCHEMA\x10\x02\x12\x1b\n" +
	"\x17GRANT_OBJECT_TYPE_TABLE\x10\x03\x12\x1a\n" +
	"\x16GRANT_OBJECT_TYPE_VIEW\x10\x04\x12'\n" +
	"#GRANT_OBJECT_TYPE_MATERIALIZED_VIEW\x10\x05\x12\x1e\n" +
	"\x1aGRANT_OBJECT_TYPE_SEQUENCE\x10\x06\x12#\n" +
	"\x1fGRANT_OBJECT_TYPE_FOREIGN_TABLE\x10\a\x12\x1e\n" +
	"\x1aGRANT_OBJECT_TYPE_FUNCTION\x10\b\x12\"\n" +
	"\x1eGRANT_OBJECT_TYPE_LARGE_OBJECT\x10\t*\xd4\x02\n" +
	"\x1aDefaultPrivilegeObjectType\x12-\n" +
	")DEFAULT_PRIVILEGE_OBJECT_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$DEFAULT_PRIVILEGE_OBJECT_TYPE_TABLES\x10\x01\x12+\n" +
	"'DEFAULT_PRIVILEGE_OBJECT_TYPE_SEQUENCES\x10\x02\x12+\n" +
	"'DEFAULT_PRIVILEGE_OBJECT_TYPE_FUNCTIONS\x10\x03\x12'\n" +
	"#DEFAULT_PRIVILEGE_OBJECT_TYPE_TYPES\x10\x04\x12)\n" +
	"%DEFAULT_PRIVILEGE_OBJECT_TYPE_SCHEMAS\x10\x05\x12/\n" +
	"+DEFAULT_PRIVILEGE_OBJECT_TYPE_LARGE_OBJECTS\x10\x062\x86\x06\n" +
	"\vRoleService\x12j\n" +
	"\tListRoles\x12,.querylane.console.v1alpha1.ListRolesRequest\x1a-.querylane.console.v1alpha1.ListRolesResponse\"\x00\x12d\n" +
	"\aGetRole\x12*.querylane.console.v1alpha1.GetRoleRequest\x1a+.querylane.console.v1alpha1.GetRoleResponse\"\x00\x12y\n" +
	"\x0eListRoleGrants\x121.querylane.console.v1alpha1.ListRoleGrantsRequest\x1a2.querylane.console.v1alpha1.ListRoleGrantsResponse\"\x00\x12\x8b\x01\n" +
	"\x14ListRoleOwnedObjects\x127.querylane.console.v1alpha1.ListRoleOwnedObjectsRequest\x1a8.querylane.console.v1alpha1.ListRoleOwnedObjectsResponse\"\x00\x12\x9a\x01\n" +
	"\x19ListRoleDefaultPrivileges\x12<.querylane.console.v1alpha1.ListRoleDefaultPrivilegesRequest\x1a=.querylane.console.v1alpha1.ListRoleDefaultPrivilegesResponse\"\x00\x12\x7f\n" +
	"\x10ListPublicGrants\x123.querylane.console.v1alpha1.ListPublicGrantsRequest\x1a4.querylane.console.v1alpha1.ListPublicGrantsResponse\"\x00B\x91\x02\n" +
	"\x1ecom.querylane.console.v1alpha1B\tRoleProtoP\x01ZZgithub.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1;consolev1alpha1\xa2\x02\x03QCX\xaa\x02\x1aQuerylane.Console.V1alpha1\xca\x02\x1aQuerylane\\Console\\V1alpha1\xe2\x02&Querylane\\Console\\V1alpha1\\GPBMetadata\xea\x02\x1cQuerylane::Console::V1alpha1b\x06proto3"

var (
	file_querylane_console_v1alpha1_role_proto_rawDescOnce sync.Once
	file_querylane_console_v1alpha1_role_proto_rawDescData []byte
)

func file_querylane_console_v1alpha1_role_proto_rawDescGZIP() []byte {
	file_querylane_console_v1alpha1_role_proto_rawDescOnce.Do(func() {
		file_querylane_console_v1alpha1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_role_proto_rawDesc), len(file_querylane_console_v1alpha1_role_proto_rawDesc)))
	})
	return file_querylane_console_v1alpha1_role_proto_rawDescData
}

var file_querylane_console_v1alpha1_role_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_querylane_console_v1alpha1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_querylane_console_v1alpha1_role_proto_goTypes = []any{
	(GrantObjectType)(0),                      // 0: querylane.console.v1alpha1.GrantObjectType
	(DefaultPrivilegeObjectType)(0),           // 1: querylane.console.v1alpha1.DefaultPrivilegeObjectType
	(*Role)(nil),                              // 2: querylane.console.v1alpha1.Role
	(*RoleAttributes)(nil),                    // 3: querylane.console.v1alpha1.RoleAttributes
	(*RoleMembership)(nil),                    // 4: querylane.console.v1alpha1.RoleMembership
	(*ObjectGrant)(nil),                       // 5: querylane.console.v1alpha1.ObjectGrant
	(*OwnedObject)(nil),                       // 6: querylane.console.v1alpha1.OwnedObject
	(*RoleDefaultPrivilege)(nil),              // 7: querylane.console.v1alpha1.RoleDefaultPrivilege
	(*ListRolesRequest)(nil),                  // 8: querylane.console.v1alpha1.ListRolesRequest
	(*ListRolesResponse)(nil),                 // 9: querylane.console.v1alpha1.ListRolesResponse
	(*GetRoleRequest)(nil),                    // 10: querylane.console.v1alpha1.GetRoleRequest
	(*GetRoleResponse)(nil),                   // 11: querylane.console.v1alpha1.GetRoleResponse
	(*ListRoleGrantsRequest)(nil),             // 12: querylane.console.v1alpha1.ListRoleGrantsRequest
	(*ListRoleGrantsResponse)(nil),            // 13: querylane.console.v1alpha1.ListRoleGrantsResponse
	(*ListRoleOwnedObjectsRequest)(nil),       // 14: querylane.console.v1alpha1.ListRoleOwnedObjectsRequest
	(*ListRoleOwnedObjectsResponse)(nil),      // 15: querylane.console.v1alpha1.ListRoleOwnedObjectsResponse
	(*ListRoleDefaultPrivilegesRequest)(nil),  // 16: querylane.console.v1alpha1.ListRoleDefaultPrivilegesRequest
	(*ListRoleDefaultPrivilegesResponse)(nil), // 17: querylane.console.v1alpha1.ListRoleDefaultPrivilegesResponse
	(*ListPublicGrantsRequest)(nil),           // 18: querylane.console.v1alpha1.ListPublicGrantsRequest
	(*ListPublicGrantsResponse)(nil),          // 19: querylane.console.v1alpha1.ListPublicGrantsResponse
	(*timestamppb.Timestamp)(nil),             // 20: google.protobuf.Timestamp
}
var file_querylane_console_v1alpha1_role_proto_depIdxs = []int32{
	3,  // 0: querylane.console.v1alpha1.Role.attributes:type_name -> querylane.console.v1alpha1.RoleAttributes
	4,  // 1: querylane.console.v1alpha1.Role.member_of:type_name -> querylane.console.v1alpha1.RoleMembership
	20, // 2: querylane.console.v1alpha1.RoleAttributes.valid_until:type_name -> google.protobuf.Timestamp
	0,  // 3: querylane.console.v1alpha1.ObjectGrant.object_type:type_name -> querylane.console.v1alpha1.GrantObjectType
	0,  // 4: querylane.console.v1alpha1.OwnedObject.object_type:type_name -> querylane.console.v1alpha1.GrantObjectType
	1,  // 5: querylane.console.v1alpha1.RoleDefaultPrivilege.object_type:type_name -> querylane.console.v1alpha1.DefaultPrivilegeObjectType
	2,  // 6: querylane.console.v1alpha1.ListRolesResponse.roles:type_name -> querylane.console.v1alpha1.Role
	2,  // 7: querylane.console.v1alpha1.GetRoleResponse.role:type_name -> querylane.console.v1alpha1.Role
	5,  // 8: querylane.console.v1alpha1.ListRoleGrantsResponse.grants:type_name -> querylane.console.v1alpha1.ObjectGrant
	6,  // 9: querylane.console.v1alpha1.ListRoleOwnedObjectsResponse.owned_objects:type_name -> querylane.console.v1alpha1.OwnedObject
	7,  // 10: querylane.console.v1alpha1.ListRoleDefaultPrivilegesResponse.default_privileges:type_name -> querylane.console.v1alpha1.RoleDefaultPrivilege
	5,  // 11: querylane.console.v1alpha1.ListPublicGrantsResponse.grants:type_name -> querylane.console.v1alpha1.ObjectGrant
	8,  // 12: querylane.console.v1alpha1.RoleService.ListRoles:input_type -> querylane.console.v1alpha1.ListRolesRequest
	10, // 13: querylane.console.v1alpha1.RoleService.GetRole:input_type -> querylane.console.v1alpha1.GetRoleRequest
	12, // 14: querylane.console.v1alpha1.RoleService.ListRoleGrants:input_type -> querylane.console.v1alpha1.ListRoleGrantsRequest
	14, // 15: querylane.console.v1alpha1.RoleService.ListRoleOwnedObjects:input_type -> querylane.console.v1alpha1.ListRoleOwnedObjectsRequest
	16, // 16: querylane.console.v1alpha1.RoleService.ListRoleDefaultPrivileges:input_type -> querylane.console.v1alpha1.ListRoleDefaultPrivilegesRequest
	18, // 17: querylane.console.v1alpha1.RoleService.ListPublicGrants:input_type -> querylane.console.v1alpha1.ListPublicGrantsRequest
	9,  // 18: querylane.console.v1alpha1.RoleService.ListRoles:output_type -> querylane.console.v1alpha1.ListRolesResponse
	11, // 19: querylane.console.v1alpha1.RoleService.GetRole:output_type -> querylane.console.v1alpha1.GetRoleResponse
	13, // 20: querylane.console.v1alpha1.RoleService.ListRoleGrants:output_type -> querylane.console.v1alpha1.ListRoleGrantsResponse
	15, // 21: querylane.console.v1alpha1.RoleService.ListRoleOwnedObjects:output_type -> querylane.console.v1alpha1.ListRoleOwnedObjectsResponse
	17, // 22: querylane.console.v1alpha1.RoleService.ListRoleDefaultPrivileges:output_type -> querylane.console.v1alpha1.ListRoleDefaultPrivilegesResponse
	19, // 23: querylane.console.v1alpha1.RoleService.ListPublicGrants:output_type -> querylane.console.v1alpha1.ListPublicGrantsResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_querylane_console_v1alpha1_role_proto_init() }
func file_querylane_console_v1alpha1_role_proto_init() {
	if File_querylane_console_v1alpha1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_role_proto_rawDesc), len(file_querylane_console_v1alpha1_role_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_querylane_console_v1alpha1_role_proto_goTypes,
		DependencyIndexes: file_querylane_console_v1alpha1_role_proto_depIdxs,
		EnumInfos:         file_querylane_console_v1alpha1_role_proto_enumTypes,
		MessageInfos:      file_querylane_console_v1alpha1_role_proto_msgTypes,
	}.Build()
	File_querylane_console_v1alpha1_role_proto = out.File
	file_querylane_console_v1alpha1_role_proto_goTypes = nil
	file_querylane_console_v1alpha1_role_proto_depIdxs = nil
}
