// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: querylane/console/v1alpha1/runner.proto

package consolev1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunnerExecution is the scheduling state of one background runner against
// one target. Backed by the same lease bookkeeping the multi-replica
// coordination uses, so it reflects the fleet, not a single replica.
type RunnerExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only. The runner this state belongs to (e.g. "probe_cache",
	// "instance_connectivity", "sample_retention").
	RunnerName string `protobuf:"bytes,1,opt,name=runner_name,json=runnerName,proto3" json:"runner_name,omitempty"`
	// Output-only. The target the runner executes against, as an AIP resource
	// name: "instances/{instance}" for instance-level runners,
	// "instances/{instance}/databases/{database}" for database-level runners,
	// or "meta" for jobs operating on querylane's own database.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Output-only. Whether a replica currently holds the execution lease
	// (a run is in flight right now).
	LeaseHeld bool `protobuf:"varint,3,opt,name=lease_held,json=leaseHeld,proto3" json:"lease_held,omitempty"`
	// Output-only. When the most recent run started.
	LastStartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_started_at,json=lastStartedAt,proto3" json:"last_started_at,omitempty"`
	// Output-only. When the most recent run finished, successfully or not.
	LastFinishedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_finished_at,json=lastFinishedAt,proto3" json:"last_finished_at,omitempty"`
	// Output-only. When the runner last completed successfully for this
	// target. A stale value relative to the runner's cadence means sampling
	// for this target is unhealthy.
	LastSuccessAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	// Output-only. The most recent infrastructure failure, empty after a
	// successful run. Collection-level issues (e.g. missing permissions on a
	// statistics view) do not surface here; they show up as missing samples.
	LastError     string `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerExecution) Reset() {
	*x = RunnerExecution{}
	mi := &file_querylane_console_v1alpha1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerExecution) ProtoMessage() {}

func (x *RunnerExecution) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerExecution.ProtoReflect.Descriptor instead.
func (*RunnerExecution) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerExecution) GetRunnerName() string {
	if x != nil {
		return x.RunnerName
	}
	return ""
}

func (x *RunnerExecution) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunnerExecution) GetLeaseHeld() bool {
	if x != nil {
		return x.LeaseHeld
	}
	return false
}

func (x *RunnerExecution) GetLastStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStartedAt
	}
	return nil
}

func (x *RunnerExecution) GetLastFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFinishedAt
	}
	return nil
}

func (x *RunnerExecution) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

func (x *RunnerExecution) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ListRunnerExecutionsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. AIP-160 filter. Filterable fields: runner_name, target.
	// Example: `target = "instances/prod"` or `runner_name = "probe_cache"`.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. AIP-132 order_by. Defaults to `runner_name, target`.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunnerExecutionsRequest) Reset() {
	*x = ListRunnerExecutionsRequest{}
	mi := &file_querylane_console_v1alpha1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnerExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnerExecutionsRequest) ProtoMessage() {}

func (x *ListRunnerExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnerExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListRunnerExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ListRunnerExecutionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRunnerExecutionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRunnerExecutionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRunnerExecutionsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListRunnerExecutionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunnerExecutions []*RunnerExecution     `protobuf:"bytes,1,rep,name=runner_executions,json=runnerExecutions,proto3" json:"runner_executions,omitempty"`
	NextPageToken    string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRunnerExecutionsResponse) Reset() {
	*x = ListRunnerExecutionsResponse{}
	mi := &file_querylane_console_v1alpha1_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnerExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnerExecutionsResponse) ProtoMessage() {}

func (x *ListRunnerExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnerExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListRunnerExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ListRunnerExecutionsResponse) GetRunnerExecutions() []*RunnerExecution {
	if x != nil {
		return x.RunnerExecutions
	}
	return nil
}

func (x *ListRunnerExecutionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_querylane_console_v1alpha1_runner_proto protoreflect.FileDescriptor

const file_querylane_console_v1alpha1_runner_proto_rawDesc = "" +
	"\n" +
	"'querylane/console/v1alpha1/runner.proto\x12\x1aquerylane.console.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x02\n" +
	"\x0fRunnerExecution\x12$\n" +
	"\vrunner_name\x18\x01 \x01(\tB\x03\xe0A\x03R\n" +
	"runnerName\x12\x1b\n" +
	"\x06target\x18\x02 \x01(\tB\x03\xe0A\x03R\x06target\x12\"\n" +
	"\n" +
	"lease_held\x18\x03 \x01(\bB\x03\xe0A\x03R\tleaseHeld\x12G\n" +
	"\x0flast_started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\rlastStartedAt\x12I\n" +
	"\x10last_finished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\x0elastFinishedAt\x12G\n" +
	"\x0flast_success_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\rlastSuccessAt\x12\"\n" +
	"\n" +
	"last_error\x18\a \x01(\tB\x03\xe0A\x03R\tlastError\"\xaa\x01\n" +
	"\x1bListRunnerExecutionsRequest\x12*\n" +
	"\tpage_size\x18\x01 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x03 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x04 \x01(\tB\x03\xe0A\x01R\aorderBy\"\xa0\x01\n" +
	"\x1cListRunnerExecutionsResponse\x12X\n" +
	"\x11runner_executions\x18\x01 \x03(\v2+.querylane.console.v1alpha1.RunnerExecutionR\x10runnerExecutions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x9d\x01\n" +
	"\rRunnerService\x12\x8b\x01\n" +
	"\x14ListRunnerExecutions\x127.querylane.console.v1alpha1.ListRunnerExecutionsRequest\x1a8.querylane.console.v1alpha1.ListRunnerExecutionsResponse\"\x00B\x93\x02\n" +
	"\x1ecom.querylane.console.v1alpha1B\vRunnerProtoP\x01ZZgithub.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1;consolev1alpha1\xa2\x02\x03QCX\xaa\x02\x1aQuerylane.Console.V1alpha1\xca\x02\x1aQuerylane\\Console\\V1alpha1\xe2\x02&Querylane\\Console\\V1alpha1\\GPBMetadata\xea\x02\x1cQuerylane::Console::V1alpha1b\x06proto3"

var (
	file_querylane_console_v1alpha1_runner_proto_rawDescOnce sync.Once
	file_querylane_console_v1alpha1_runner_proto_rawDescData []byte
)

func file_querylane_console_v1alpha1_runner_proto_rawDescGZIP() []byte {
	file_querylane_console_v1alpha1_runner_proto_rawDescOnce.Do(func() {
		file_querylane_console_v1alpha1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_runner_proto_rawDesc), len(file_querylane_console_v1alpha1_runner_proto_rawDesc)))
	})
	return file_querylane_console_v1alpha1_runner_proto_rawDescData
}

var file_querylane_console_v1alpha1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_querylane_console_v1alpha1_runner_proto_goTypes = []any{
	(*RunnerExecution)(nil),              // 0: querylane.console.v1alpha1.RunnerExecution
	(*ListRunnerExecutionsRequest)(nil),  // 1: querylane.console.v1alpha1.ListRunnerExecutionsRequest
	(*ListRunnerExecutionsResponse)(nil), // 2: querylane.console.v1alpha1.ListRunnerExecutionsResponse
	(*timestamppb.Timestamp)(nil),        // 3: google.protobuf.Timestamp
}
var file_querylane_console_v1alpha1_runner_proto_depIdxs = []int32{
	3, // 0: querylane.console.v1alpha1.RunnerExecution.last_started_at:type_name -> google.protobuf.Timestamp
	3, // 1: querylane.console.v1alpha1.RunnerExecution.last_finished_at:type_name -> google.protobuf.Timestamp
	3, // 2: querylane.console.v1alpha1.RunnerExecution.last_success_at:type_name -> google.protobuf.Timestamp
	0, // 3: querylane.console.v1alpha1.ListRunnerExecutionsResponse.runner_executions:type_name -> querylane.console.v1alpha1.RunnerExecution
	1, // 4: querylane.console.v1alpha1.RunnerService.ListRunnerExecutions:input_type -> querylane.console.v1alpha1.ListRunnerExecutionsRequest
	2, // 5: querylane.console.v1alpha1.RunnerService.ListRunnerExecutions:output_type -> querylane.console.v1alpha1.ListRunnerExecutionsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_querylane_console_v1alpha1_runner_proto_init() }
func file_querylane_console_v1alpha1_runner_proto_init() {
	if File_querylane_console_v1alpha1_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_runner_proto_rawDesc), len(file_querylane_console_v1alpha1_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_querylane_console_v1alpha1_runner_proto_goTypes,
		DependencyIndexes: file_querylane_console_v1alpha1_runner_proto_depIdxs,
		MessageInfos:      file_querylane_console_v1alpha1_runner_proto_msgTypes,
	}.Build()
	File_querylane_console_v1alpha1_runner_proto = out.File
	file_querylane_console_v1alpha1_runner_proto_goTypes = nil
	file_querylane_console_v1alpha1_runner_proto_depIdxs = nil
}
