// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: querylane/console/v1alpha1/schema.proto

package consolev1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Schema represents a namespace for tables within a Database.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output-only identifier. The unique resource name of the schema.
	// Format: instances/{instance}/databases/{database}/schemas/{schema}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output-only. The display name of the schema.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Output-only. The PostgreSQL role that owns this schema.
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// Output-only. Whether this is a system schema that should typically
	// be hidden from end users (e.g., information_schema, pg_catalog).
	IsSystemSchema bool `protobuf:"varint,5,opt,name=is_system_schema,json=isSystemSchema,proto3" json:"is_system_schema,omitempty"`
	// Output-only. The last time a DDL operation was performed on this schema.
	LastDdlTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_ddl_time,json=lastDdlTime,proto3" json:"last_ddl_time,omitempty"`
	// Output-only. The time when the schema was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Schema) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Schema) GetIsSystemSchema() bool {
	if x != nil {
		return x.IsSystemSchema
	}
	return false
}

func (x *Schema) GetLastDdlTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDdlTime
	}
	return nil
}

func (x *Schema) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type ListSchemasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parent Database from which to list schemas.
	// Format: instances/{instance}/databases/{database}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of schemas to return. Server may return fewer.
	// If unspecified or 0, server will choose a reasonable default (typically 50).
	// Maximum value is 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListSchemas` call.
	// Provide this to retrieve the next page of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter expression (an AIP-160 subset: `=`, `!=`, the `:`
	// case-insensitive substring operator, combined with `AND`). Values are
	// quoted strings or the bare bools true/false. Filterable fields:
	//   - name, owner (string; support the `:` substring operator)
	//   - is_system_schema (bool)
	//
	// Examples:
	//   - is_system_schema = false (exclude system schemas)
	//   - owner = "postgres"
	//   - name:"app"
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Ordering expression following AIP-132 syntax.
	// Supported fields: name, display_name, owner, last_ddl_time
	// Default: "name asc"
	//
	// Examples:
	//   - "name asc"
	//   - "last_ddl_time desc, name asc"
	//   - "owner desc"
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *ListSchemasRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListSchemasRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSchemasRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSchemasRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListSchemasRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListSchemasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of schemas found in the database.
	Schemas []*Schema `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// A token to retrieve the next page of results.
	// If this field is empty, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Output-only. Freshness and sync status for this catalog list.
	SyncMetadata  *CatalogSyncMetadata `protobuf:"bytes,3,opt,name=sync_metadata,json=syncMetadata,proto3" json:"sync_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ListSchemasResponse) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ListSchemasResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSchemasResponse) GetSyncMetadata() *CatalogSyncMetadata {
	if x != nil {
		return x.SyncMetadata
	}
	return nil
}

type GetSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the schema to retrieve.
	// Format: instances/{instance}/databases/{database}/schemas/{schema}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved schema resource.
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querylane_console_v1alpha1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_querylane_console_v1alpha1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_querylane_console_v1alpha1_schema_proto protoreflect.FileDescriptor

const file_querylane_console_v1alpha1_schema_proto_rawDesc = "" +
	"\n" +
	"'querylane/console/v1alpha1/schema.proto\x12\x1aquerylane.console.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-querylane/console/v1alpha1/catalog_sync.proto\"\x8d\x03\n" +
	"\x06Schema\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\bR\x04name\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x03\xe0A\x03R\vdisplayName\x12\x19\n" +
	"\x05owner\x18\x03 \x01(\tB\x03\xe0A\x03R\x05owner\x12-\n" +
	"\x10is_system_schema\x18\x05 \x01(\bB\x03\xe0A\x03R\x0eisSystemSchema\x12C\n" +
	"\rlast_ddl_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\vlastDdlTime\x12@\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime:n\xeaAk\n" +
	"\x1cconsole.querylane.dev/Schema\x12:instances/{instance}/databases/{database}/schemas/{schema}*\aschemas2\x06schema\"\xa9\x02\n" +
	"\x12ListSchemasRequest\x12\x85\x01\n" +
	"\x06parent\x18\x01 \x01(\tBm\xe0A\x02\xfaA \n" +
	"\x1econsole.querylane.dev/Database\xbaHDrB2@^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/databases/[^/]+$R\x06parent\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xe0A\x01\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tB\x03\xe0A\x01R\aorderBy\"\xd6\x01\n" +
	"\x13ListSchemasResponse\x12<\n" +
	"\aschemas\x18\x01 \x03(\v2\".querylane.console.v1alpha1.SchemaR\aschemas\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12Y\n" +
	"\rsync_metadata\x18\x03 \x01(\v2/.querylane.console.v1alpha1.CatalogSyncMetadataB\x03\xe0A\x03R\fsyncMetadata\"\xa5\x01\n" +
	"\x10GetSchemaRequest\x12\x90\x01\n" +
	"\x04name\x18\x01 \x01(\tB|\xe0A\x02\xfaA\x1e\n" +
	"\x1cconsole.querylane.dev/Schema\xbaHU\xc8\x01\x01rP2N^instances/[a-zA-Z]([a-zA-Z0-9_-]*[a-zA-Z0-9])?/databases/[^/]+/schemas/[^/]+$R\x04name\"O\n" +
	"\x11GetSchemaResponse\x12:\n" +
	"\x06schema\x18\x01 \x01(\v2\".querylane.console.v1alpha1.SchemaR\x06schema2\xed\x01\n" +
	"\rSchemaService\x12p\n" +
	"\vListSchemas\x12..querylane.console.v1alpha1.ListSchemasRequest\x1a/.querylane.console.v1alpha1.ListSchemasResponse\"\x00\x12j\n" +
	"\tGetSchema\x12,.querylane.console.v1alpha1.GetSchemaRequest\x1a-.querylane.console.v1alpha1.GetSchemaResponse\"\x00B\x93\x02\n" +
	"\x1ecom.querylane.console.v1alpha1B\vSchemaProtoP\x01ZZgithub.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1;consolev1alpha1\xa2\x02\x03QCX\xaa\x02\x1aQuerylane.Console.V1alpha1\xca\x02\x1aQuerylane\\Console\\V1alpha1\xe2\x02&Querylane\\Console\\V1alpha1\\GPBMetadata\xea\x02\x1cQuerylane::Console::V1alpha1b\x06proto3"

var (
	file_querylane_console_v1alpha1_schema_proto_rawDescOnce sync.Once
	file_querylane_console_v1alpha1_schema_proto_rawDescData []byte
)

func file_querylane_console_v1alpha1_schema_proto_rawDescGZIP() []byte {
	file_querylane_console_v1alpha1_schema_proto_rawDescOnce.Do(func() {
		file_querylane_console_v1alpha1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_schema_proto_rawDesc), len(file_querylane_console_v1alpha1_schema_proto_rawDesc)))
	})
	return file_querylane_console_v1alpha1_schema_proto_rawDescData
}

var file_querylane_console_v1alpha1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_querylane_console_v1alpha1_schema_proto_goTypes = []any{
	(*Schema)(nil),                // 0: querylane.console.v1alpha1.Schema
	(*ListSchemasRequest)(nil),    // 1: querylane.console.v1alpha1.ListSchemasRequest
	(*ListSchemasResponse)(nil),   // 2: querylane.console.v1alpha1.ListSchemasResponse
	(*GetSchemaRequest)(nil),      // 3: querylane.console.v1alpha1.GetSchemaRequest
	(*GetSchemaResponse)(nil),     // 4: querylane.console.v1alpha1.GetSchemaResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*CatalogSyncMetadata)(nil),   // 6: querylane.console.v1alpha1.CatalogSyncMetadata
}
var file_querylane_console_v1alpha1_schema_proto_depIdxs = []int32{
	5, // 0: querylane.console.v1alpha1.Schema.last_ddl_time:type_name -> google.protobuf.Timestamp
	5, // 1: querylane.console.v1alpha1.Schema.create_time:type_name -> google.protobuf.Timestamp
	0, // 2: querylane.console.v1alpha1.ListSchemasResponse.schemas:type_name -> querylane.console.v1alpha1.Schema
	6, // 3: querylane.console.v1alpha1.ListSchemasResponse.sync_metadata:type_name -> querylane.console.v1alpha1.CatalogSyncMetadata
	0, // 4: querylane.console.v1alpha1.GetSchemaResponse.schema:type_name -> querylane.console.v1alpha1.Schema
	1, // 5: querylane.console.v1alpha1.SchemaService.ListSchemas:input_type -> querylane.console.v1alpha1.ListSchemasRequest
	3, // 6: querylane.console.v1alpha1.SchemaService.GetSchema:input_type -> querylane.console.v1alpha1.GetSchemaRequest
	2, // 7: querylane.console.v1alpha1.SchemaService.ListSchemas:output_type -> querylane.console.v1alpha1.ListSchemasResponse
	4, // 8: querylane.console.v1alpha1.SchemaService.GetSchema:output_type -> querylane.console.v1alpha1.GetSchemaResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_querylane_console_v1alpha1_schema_proto_init() }
func file_querylane_console_v1alpha1_schema_proto_init() {
	if File_querylane_console_v1alpha1_schema_proto != nil {
		return
	}
	file_querylane_console_v1alpha1_catalog_sync_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_querylane_console_v1alpha1_schema_proto_rawDesc), len(file_querylane_console_v1alpha1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_querylane_console_v1alpha1_schema_proto_goTypes,
		DependencyIndexes: file_querylane_console_v1alpha1_schema_proto_depIdxs,
		MessageInfos:      file_querylane_console_v1alpha1_schema_proto_msgTypes,
	}.Build()
	File_querylane_console_v1alpha1_schema_proto = out.File
	file_querylane_console_v1alpha1_schema_proto_goTypes = nil
	file_querylane_console_v1alpha1_schema_proto_depIdxs = nil
}
