import { create, toBinary } from "@bufbuild/protobuf";
import { Code, ConnectError } from "@connectrpc/connect";
import {
  cleanup,
  render,
  screen,
  waitFor,
  within,
} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import type { GridRow } from "@/components/data-grid/table-data-grid/grid-row-model";
import { ROW_KEY_FIELD } from "@/components/data-grid/table-data-grid/grid-row-model";
import { TableDetail } from "@/features/data-explorer/explorer-table-detail";
import { PostgreSqlErrorDetailSchema } from "@/protogen/querylane/console/v1alpha1/errors_pb";
import {
  ReadRowsResponseSchema,
  RowCount_Status,
  RowCountSchema,
  TableResultSetSchema,
} from "@/protogen/querylane/console/v1alpha1/table_data_pb";
import {
  ConstraintType,
  DataType,
  GetTablePartitionMetadataResponseSchema,
  IdentityGeneration,
  ListTableColumnsResponseSchema,
  ListTableConstraintsResponseSchema,
  ListTableIndexesResponseSchema,
  ListTablePoliciesResponseSchema,
  ListTableTriggersResponseSchema,
  PolicyCommand,
  PolicyMode,
  ReferentialAction,
  Table_TableType,
  TableConstraintSchema,
  type TablePolicy,
  TablePolicySchema,
  TableSchema,
} from "@/protogen/querylane/console/v1alpha1/table_pb";

const POSTGRES_DETAIL_TYPE = "querylane.console.v1alpha1.PostgreSqlErrorDetail";
const COLUMNS_TAB_RE = /^Columns/;
const CREATE_TABLE_RE = /CREATE TABLE/;
const CREATE_INDEX_RE = /CREATE (?:UNIQUE )?INDEX/;
const CREATE_POLICY_RE = /CREATE POLICY/;
const CREATE_TABLE_SQL_RE = /CREATE TABLE "public"\."customers" \(/;
const INDEXES_TAB_RE = /^Indexes/;
const IDENTITY_COLUMN_SQL_RE =
  /"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL/;
const PRIMARY_KEY_CONSTRAINT_SQL_RE =
  /ALTER TABLE "public"\."customers" ADD CONSTRAINT "customers_pkey" PRIMARY KEY \(id\);/;
const PRIMARY_KEY_INDEX_SQL_RE =
  /CREATE UNIQUE INDEX "customers_pkey" ON "public"\."customers" USING btree \("id"\);/;
const TRIGGER_SQL_RE =
  /CREATE TRIGGER customers_audit_trigger\s+AFTER INSERT OR UPDATE ON public\.customers\s+FOR EACH ROW EXECUTE FUNCTION audit_customer_changes\(\);/;
const SNIPPET_TRIGGER_UNAVAILABLE_RE =
  /-- Trigger "customers_search_trigger": full definition unavailable/;
const RESERVED_COLUMN_SQL_RE = /"order" text NOT NULL/;
const RESERVED_NULLABLE_COLUMN_SQL_RE = /"user" text,/;
const FULL_TRIGGER_STATEMENTS_SQL_RE =
  /CREATE TRIGGER customers_replica_trigger\s+AFTER DELETE ON public\.customers\s+FOR EACH ROW EXECUTE FUNCTION audit_customer_changes\(\);\s+CREATE TRIGGER customers_statement_trigger\s+BEFORE UPDATE ON public\.customers\s+FOR EACH STATEMENT EXECUTE FUNCTION sync_customer_summary\(\);/;
const DISABLED_TRIGGER_SQL_RE =
  /CREATE TRIGGER customers_audit_trigger[\s\S]*ALTER TABLE "public"\."customers" DISABLE TRIGGER "customers_audit_trigger";/;
const PARTITIONED_TABLE_SQL_RE =
  /CREATE TABLE "public"\."events" \([\s\S]*\) PARTITION BY RANGE \(created_at\);/;
const CHILD_PARTITION_SQL_RE =
  /CREATE TABLE "archive"\."events_2025" PARTITION OF "public"\."events"\s+FOR VALUES FROM \('2025-01-01'\) TO \('2026-01-01'\);/;
const COLUMN_COMMENT_SQL_RE =
  /COMMENT ON COLUMN "public"\."customers"\."display name" IS 'Owner''s name';/;
const KIND_FILTER_RE = /^Kind$/;
const LAST_FETCHED_RE = /^Last fetched/;

vi.mock("@tanstack/react-router", async (importOriginal) => {
  const actual =
    await importOriginal<typeof import("@tanstack/react-router")>();
  const linkExportName = "Link";
  return {
    ...actual,
    [linkExportName]: ({
      children,
      params,
      search,
    }: {
      children: ReactNode;
      params: { databaseId: string; instanceId: string };
      search: { category: string; name: string; schema: string };
    }) => (
      <a
        href={`/instances/${params.instanceId}/databases/${params.databaseId}/explorer?schema=${search.schema}&category=${search.category}&name=${search.name}`}
      >
        {children}
      </a>
    ),
  };
});

interface MockGridColumn {
  key: string;
  renderCell?: (args: { row: GridRow; rowIdx: number }) => ReactNode;
  renderHeaderCell?: () => ReactNode;
}

interface MockGridProps {
  columns?: MockGridColumn[];
  rows?: GridRow[];
}

function querySqlCodeBlock(pattern: RegExp) {
  return Array.from(
    document.querySelectorAll<HTMLElement>(
      'code.language-sql[data-syntax-highlighter="shiki"]'
    )
  ).find((codeBlock) => pattern.test(codeBlock.textContent ?? ""));
}

function getSqlCodeBlock(pattern: RegExp) {
  const codeBlock = querySqlCodeBlock(pattern);
  if (!codeBlock) {
    throw new Error(`Expected a highlighted SQL block matching ${pattern}.`);
  }
  return codeBlock;
}

const tableQueries = vi.hoisted(() => ({
  columns: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(() => Promise.resolve()),
  },
  constraints: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(() => Promise.resolve()),
  },
  indexes: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(() => Promise.resolve()),
  },
  partitionMetadata: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(() => Promise.resolve()),
  },
  policies: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(() => Promise.resolve()),
  },
  triggers: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(() => Promise.resolve()),
  },
}));

const tableDataApi = vi.hoisted(() => ({
  useReadCellValueMutation: vi.fn(),
  useReadRowsQuery: vi.fn(),
  useStreamRowsExporter: vi.fn(),
}));

const reactDataGrid = vi.hoisted(() => ({
  dataGrid: vi.fn((props: MockGridProps) => (
    <div data-testid="data-grid">
      {props.rows?.map((row, rowIndex) => (
        <div key={row[ROW_KEY_FIELD]}>
          {props.columns?.map((column) => (
            <div data-testid={`grid-cell-${column.key}`} key={column.key}>
              {column.renderCell?.({ row, rowIdx: rowIndex })}
            </div>
          ))}
        </div>
      ))}
    </div>
  )),
}));

vi.mock("react-data-grid", () => ({
  ...Object.fromEntries([
    ["DataGrid", reactDataGrid.dataGrid],
    ["SelectColumn", { columnName: "", key: "__select" }],
  ]),
  SELECT_COLUMN_KEY: "__select",
}));

vi.mock("@/hooks/api/table", () => ({
  useGetTablePartitionMetadataQuery: () => tableQueries.partitionMetadata,
  useListTableColumnsQuery: () => tableQueries.columns,
  useListTableConstraintsQuery: () => tableQueries.constraints,
  useListTableIndexesQuery: () => tableQueries.indexes,
  useListTablePoliciesQuery: () => tableQueries.policies,
  useListTableTriggersQuery: () => tableQueries.triggers,
}));

vi.mock("@/hooks/api/table-data", () => ({
  useReadCellValueMutation: tableDataApi.useReadCellValueMutation,
  useReadRowsQuery: tableDataApi.useReadRowsQuery,
  useStreamRowsExporter: tableDataApi.useStreamRowsExporter,
}));

function seedSuccessfulMetadataQueries() {
  tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
    columns: [],
  });
  tableQueries.columns.error = null;
  tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
    constraints: [],
  });
  tableQueries.constraints.dataUpdatedAt = 0;
  tableQueries.constraints.error = null;
  tableQueries.constraints.isFetching = false;
  tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
    indexes: [],
  });
  tableQueries.indexes.error = null;
  tableQueries.partitionMetadata.data = create(
    GetTablePartitionMetadataResponseSchema,
    {}
  );
  tableQueries.partitionMetadata.error = null;
  tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
    policies: [],
  });
  tableQueries.policies.error = null;
  tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
    triggers: [],
  });
  tableQueries.triggers.error = null;
  tableDataApi.useReadRowsQuery.mockReturnValue({
    data: create(ReadRowsResponseSchema, {
      resultSet: create(TableResultSetSchema, {
        columns: [],
        rows: [],
      }),
    }),
    error: null,
    isFetching: false,
    isLoading: false,
    refetch: vi.fn(),
  });
  tableDataApi.useReadCellValueMutation.mockReturnValue({
    isError: false,
    isPending: false,
    mutate: vi.fn(),
  });
  tableDataApi.useStreamRowsExporter.mockReturnValue(vi.fn());
}

function createMetadataError({
  code,
  conditionName,
  message,
  operation,
  reason,
  sqlstate,
  sqlstateClass,
}: {
  code: Code;
  conditionName: string;
  message: string;
  operation: string;
  reason: string;
  sqlstate: string;
  sqlstateClass: string;
}) {
  const error = new ConnectError(
    `PostgreSQL ${conditionName} during ${operation}: ${message}`,
    code
  );
  error.details = [
    {
      debug: {
        domain: "console.querylane.dev",
        metadata: {
          conditionName,
          operation,
          sqlstate,
          sqlstateClass,
        },
        reason,
      },
      type: "google.rpc.ErrorInfo",
      value: new Uint8Array([1]),
    },
    {
      type: POSTGRES_DETAIL_TYPE,
      value: toBinary(
        PostgreSqlErrorDetailSchema,
        create(PostgreSqlErrorDetailSchema, {
          conditionName,
          operation,
          sqlstate,
          sqlstateClass,
        })
      ),
    },
  ];
  return error;
}

function createCheckConstraints(count: number) {
  return Array.from({ length: count }, (_, index) =>
    create(TableConstraintSchema, {
      columnNames: [`status_${index + 1}`],
      constraintName: `customers_status_${index + 1}_check`,
      definition: `CHECK (status_${index + 1} <> '')`,
      type: ConstraintType.CHECK,
    })
  );
}

function renderConstraintsTab() {
  return render(
    <TableDetail
      databaseId="app"
      initialTab="constraints"
      instanceId="prod"
      schemaName="public"
      table={create(TableSchema)}
      tableName="customers"
    />
  );
}

beforeEach(() => {
  seedSuccessfulMetadataQueries();
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("TableDetail header", () => {
  it("moves the estimated row count into the header rows stat", () => {
    tableDataApi.useReadRowsQuery.mockReturnValue({
      data: create(ReadRowsResponseSchema, {
        resultSet: create(TableResultSetSchema, {
          columns: [],
          rowCount: create(RowCountSchema, {
            status: RowCount_Status.ESTIMATED,
            value: 72_000n,
          }),
          rows: [],
        }),
      }),
      dataUpdatedAt: Date.UTC(2026, 5, 14, 10, 30, 15),
      error: null,
      isFetching: false,
      isLoading: false,
      refetch: vi.fn(),
    });

    render(
      <TableDetail
        databaseId="app"
        instanceId="prod"
        schemaName="commerce"
        table={create(TableSchema, { rowCount: 72_000n, sizeBytes: 4096n })}
        tableName="order_event_2026_h1"
      />
    );

    expect(screen.getByText("≈72k")).toBeTruthy();
    expect(screen.queryByText("≈72,000 rows")).toBeNull();
  });
});

describe("TableDetail definition document", () => {
  it("renders the definition tab as a copyable schema document", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "id",
          dataType: DataType.INTEGER,
          identityGeneration: IdentityGeneration.BY_DEFAULT,
          isIdentity: true,
          isNullable: false,
          isPrimaryKey: true,
          ordinalPosition: 1,
          rawType: "bigint",
        },
        {
          columnName: "status",
          dataType: DataType.STRING,
          defaultValue: "'active'::text",
          isNullable: false,
          ordinalPosition: 2,
          rawType: "text",
        },
        {
          columnName: "metadata",
          dataType: DataType.JSON,
          defaultValue: "'{}'::jsonb",
          isNullable: true,
          ordinalPosition: 3,
          rawType: "jsonb",
        },
      ],
    });
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        {
          columnNames: ["id"],
          constraintName: "customers_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        },
      ],
    });
    tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
      indexes: [
        {
          indexName: "customers_pkey",
          isUnique: true,
          keyColumns: ["id"],
          method: "btree",
        },
        {
          indexName: "customers_status_idx",
          keyColumns: ["status"],
          method: "btree",
        },
      ],
    });
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.PERMISSIVE,
          policyName: "customers_account_read_policy",
          roles: ["app_reader"],
          usingExpression:
            "account_id = current_setting('app.account_id')::uuid",
        },
      ],
    });
    tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
      triggers: [
        {
          definition:
            "CREATE TRIGGER customers_audit_trigger\n  AFTER INSERT OR UPDATE ON public.customers\n  FOR EACH ROW EXECUTE FUNCTION audit_customer_changes()",
          enabled: true,
          events: ["INSERT", "UPDATE"],
          functionName: "audit_customer_changes",
          timing: "AFTER",
          triggerName: "customers_audit_trigger",
        },
        {
          definition:
            "CREATE TRIGGER customers_replica_trigger\n  AFTER DELETE ON public.customers\n  FOR EACH ROW EXECUTE FUNCTION audit_customer_changes()",
          enabled: true,
          triggerName: "customers_replica_trigger",
        },
        {
          definition:
            "CREATE TRIGGER customers_statement_trigger\n  BEFORE UPDATE ON public.customers\n  FOR EACH STATEMENT EXECUTE FUNCTION sync_customer_summary();",
          enabled: true,
          triggerName: "customers_statement_trigger",
        },
        {
          // Snippet-form definition: not reconstructable without guessing the
          // trigger level, so the document should say so instead.
          definition: "EXECUTE FUNCTION refresh_customer_search()",
          enabled: true,
          functionName: "refresh_customer_search",
          triggerName: "customers_search_trigger",
        },
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          rowCount: 987_654n,
          sizeBytes: 42_467_328n,
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(screen.getByText("Schema document")).toBeTruthy();
    expect(screen.getByRole("heading", { name: "Create table" })).toBeTruthy();
    expect(getSqlCodeBlock(CREATE_TABLE_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(IDENTITY_COLUMN_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(PRIMARY_KEY_CONSTRAINT_SQL_RE)).toBeTruthy();
    expect(querySqlCodeBlock(PRIMARY_KEY_INDEX_SQL_RE)).toBeUndefined();
    expect(
      screen.getByText(
        "Exact index definitions are unavailable. Use the pg_dump command to preserve expressions, operator classes, and ordering."
      )
    ).toBeTruthy();
    expect(
      screen.getByText(
        "Policy definitions are available, but row-level security enablement and forced mode are not. Use the pg_dump command to reproduce policies safely."
      )
    ).toBeTruthy();
    expect(getSqlCodeBlock(TRIGGER_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(FULL_TRIGGER_STATEMENTS_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(SNIPPET_TRIGGER_UNAVAILABLE_RE)).toBeTruthy();
    expect(
      screen.getByRole("heading", { name: "Reproduce locally" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "Drift detection" })
    ).toBeNull();
    expect(screen.queryByText("Referenced by")).toBeNull();
    expect(screen.queryByRole("heading", { name: "Danger zone" })).toBeNull();
    expect(
      screen.getByText(
        "Definition is generated from pg_catalog on each visit; Querylane never stores or mutates schema."
      )
    ).toBeTruthy();
  });

  it("quotes reserved identifiers in the definition document", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "user",
          dataType: DataType.STRING,
          isNullable: true,
          ordinalPosition: 1,
          rawType: "text",
        },
        {
          columnName: "order",
          dataType: DataType.STRING,
          isNullable: false,
          ordinalPosition: 2,
          rawType: "text",
        },
      ],
    });
    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, { tableType: Table_TableType.BASE_TABLE })}
        tableName="orders"
      />
    );

    expect(getSqlCodeBlock(RESERVED_COLUMN_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(RESERVED_NULLABLE_COLUMN_SQL_RE)).toBeTruthy();
  });

  it("renders executable DDL for a partitioned table and its children", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "created_at",
          isNullable: false,
          ordinalPosition: 1,
          rawType: "timestamptz",
        },
      ],
    });
    tableQueries.partitionMetadata.data = create(
      GetTablePartitionMetadataResponseSchema,
      {
        partitionMetadata: {
          childPartitions: [
            {
              partitionBound:
                "FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')",
              table:
                "instances/prod/databases/app/schemas/archive/tables/events_2025",
            },
          ],
          partitionCount: 1,
          partitionKey: "RANGE (created_at)",
        },
      }
    );

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.PARTITIONED,
        })}
        tableName="events"
      />
    );

    expect(getSqlCodeBlock(PARTITIONED_TABLE_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(CHILD_PARTITION_SQL_RE)).toBeTruthy();
  });
});

describe("TableDetail definition safety", () => {
  it("refreshes live metadata when the definition tab opens", async () => {
    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    await waitFor(() => {
      expect(tableQueries.columns.refetch).toHaveBeenCalledOnce();
      expect(tableQueries.constraints.refetch).toHaveBeenCalledOnce();
      expect(tableQueries.indexes.refetch).toHaveBeenCalledOnce();
      expect(tableQueries.partitionMetadata.refetch).toHaveBeenCalledOnce();
      expect(tableQueries.policies.refetch).toHaveBeenCalledOnce();
      expect(tableQueries.triggers.refetch).toHaveBeenCalledOnce();
    });
  });

  it("does not fabricate CREATE TABLE syntax for foreign tables", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "external_id",
          isNullable: false,
          ordinalPosition: 1,
          rawType: "text",
        },
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.EXTERNAL,
        })}
        tableName="external_customers"
      />
    );

    expect(querySqlCodeBlock(CREATE_TABLE_RE)).toBeUndefined();
    expect(
      screen.getByText(
        "Exact foreign-table DDL is unavailable. Use the pg_dump command to preserve its server and options."
      )
    ).toBeTruthy();
  });

  it("does not reconstruct indexes from lossy column metadata", () => {
    tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
      indexes: [
        {
          indexName: "customers_email_lower_idx",
          keyColumns: [],
          method: "btree",
        },
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(querySqlCodeBlock(CREATE_INDEX_RE)).toBeUndefined();
    expect(
      screen.getByText(
        "Exact index definitions are unavailable. Use the pg_dump command to preserve expressions, operator classes, and ordering."
      )
    ).toBeTruthy();
  });

  it("does not present policies as complete DDL without table RLS state", () => {
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.PERMISSIVE,
          policyName: "customers_read",
          roles: ["app_reader"],
          usingExpression: "tenant_id = current_setting('app.tenant_id')",
        },
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(querySqlCodeBlock(CREATE_POLICY_RE)).toBeUndefined();
    expect(
      screen.getByText(
        "Policy definitions are available, but row-level security enablement and forced mode are not. Use the pg_dump command to reproduce policies safely."
      )
    ).toBeTruthy();
  });

  it("preserves disabled trigger state in generated DDL", () => {
    tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
      triggers: [
        {
          definition:
            "CREATE TRIGGER customers_audit_trigger AFTER INSERT ON public.customers FOR EACH ROW EXECUTE FUNCTION audit_customer_changes()",
          enabled: false,
          triggerName: "customers_audit_trigger",
        },
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(getSqlCodeBlock(DISABLED_TRIGGER_SQL_RE)).toBeTruthy();
  });

  it("includes available column comments", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "display name",
          comment: "Owner's name",
          isNullable: true,
          ordinalPosition: 1,
          rawType: "text",
        },
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(getSqlCodeBlock(COLUMN_COMMENT_SQL_RE)).toBeTruthy();
  });

  it("copies a shell-valid reproduce script", async () => {
    const user = userEvent.setup();
    const writeText = vi.fn<(value: string) => Promise<void>>(() =>
      Promise.resolve()
    );
    const originalClipboard = Object.getOwnPropertyDescriptor(
      navigator,
      "clipboard"
    );
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText },
    });

    try {
      render(
        <TableDetail
          databaseId="app"
          initialTab="definition"
          instanceId="prod"
          schemaName="public"
          table={create(TableSchema, {
            tableType: Table_TableType.BASE_TABLE,
          })}
          tableName="customers"
        />
      );

      await user.click(screen.getByRole("button", { name: "Copy all steps" }));

      const script = writeText.mock.calls[0]?.[0];
      expect(script).toContain("export POSTGRES_HOST='your-host'");
      expect(script).toContain("export POSTGRES_ROLE='your-role'");
      expect(script).not.toContain("=<");
      expect(screen.getByRole("button", { name: "Copied" })).toBeTruthy();
    } finally {
      if (originalClipboard) {
        Object.defineProperty(navigator, "clipboard", originalClipboard);
      } else {
        Reflect.deleteProperty(navigator, "clipboard");
      }
    }
  });

  it("shows copy failures instead of silently ignoring them", async () => {
    const user = userEvent.setup();
    const originalClipboard = Object.getOwnPropertyDescriptor(
      navigator,
      "clipboard"
    );
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: {
        writeText: vi.fn(() => Promise.reject(new Error("permission denied"))),
      },
    });

    try {
      render(
        <TableDetail
          databaseId="app"
          initialTab="definition"
          instanceId="prod"
          schemaName="public"
          table={create(TableSchema, {
            tableType: Table_TableType.BASE_TABLE,
          })}
          tableName="customers"
        />
      );

      await user.click(screen.getByRole("button", { name: "Copy all steps" }));

      expect(screen.getByRole("button", { name: "Copy failed" })).toBeTruthy();
    } finally {
      if (originalClipboard) {
        Object.defineProperty(navigator, "clipboard", originalClipboard);
      } else {
        Reflect.deleteProperty(navigator, "clipboard");
      }
    }
  });
});

describe("TableDetail tab routing", () => {
  it("honors URL-backed metadata tabs and reports tab changes", async () => {
    const user = userEvent.setup();
    const onTabChange = vi.fn();

    render(
      <TableDetail
        databaseId="app"
        initialTab="columns"
        instanceId="prod"
        onTabChange={onTabChange}
        schemaName="commerce"
        table={create(TableSchema, { rowCount: 72_000n, sizeBytes: 4096n })}
        tableName="order_event_2026_h1"
      />
    );

    expect(
      screen
        .getByRole("tab", { name: COLUMNS_TAB_RE })
        .hasAttribute("data-active")
    ).toBe(true);

    await user.click(screen.getByRole("tab", { name: INDEXES_TAB_RE }));

    expect(onTabChange).toHaveBeenCalledWith("indexes");
  });
});

describe("TableDetail constraints pagination", () => {
  it("paginates constraint cards after ten results", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: createCheckConstraints(11),
    });
    renderConstraintsTab();

    expect(screen.getByText("customers_status_1_check")).toBeTruthy();
    expect(screen.getByText("customers_status_10_check")).toBeTruthy();
    expect(screen.queryByText("customers_status_11_check")).toBeNull();
    expect(screen.getByText("Showing 1–10 of 11")).toBeTruthy();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
    expect(
      screen.getByRole("navigation", { name: "Constraints pagination" })
    ).toBeTruthy();
    expect(screen.getByRole("status").textContent).toContain(
      "Showing 1–10 of 11"
    );

    await user.click(screen.getByRole("button", { name: "Next page" }));

    expect(screen.queryByText("customers_status_1_check")).toBeNull();
    expect(screen.getByText("customers_status_11_check")).toBeTruthy();
    expect(screen.getByText("Showing 11–11 of 11")).toBeTruthy();
    expect(screen.getByText("Page 2 of 2")).toBeTruthy();
  });

  it("paginates constraints in their grouped display order", () => {
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        ...createCheckConstraints(10),
        create(TableConstraintSchema, {
          columnNames: ["id"],
          constraintName: "customers_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        }),
      ],
    });

    renderConstraintsTab();

    expect(screen.getByText("customers_pkey")).toBeTruthy();
    expect(screen.getByText("customers_status_9_check")).toBeTruthy();
    expect(screen.queryByText("customers_status_10_check")).toBeNull();
  });

  it("changes the constraint page size", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: createCheckConstraints(26),
    });
    renderConstraintsTab();

    const pageSize = screen.getByRole("combobox", {
      name: "Constraints per page",
    });
    expect(within(pageSize).getByText("10")).toBeTruthy();

    await user.click(pageSize);
    await user.click(screen.getByRole("option", { name: "25" }));

    expect(screen.getByText("customers_status_25_check")).toBeTruthy();
    expect(screen.queryByText("customers_status_26_check")).toBeNull();
    expect(screen.getByText("Showing 1–25 of 26")).toBeTruthy();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
  });

  it("returns to the first page when constraint search changes", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: createCheckConstraints(11),
    });
    renderConstraintsTab();

    await user.click(screen.getByRole("button", { name: "Next page" }));
    await user.type(
      screen.getByRole("textbox", { name: "Search constraints…" }),
      "status_5_check"
    );

    expect(screen.getByText("customers_status_5_check")).toBeTruthy();
    expect(screen.queryByText("customers_status_11_check")).toBeNull();
    expect(
      screen.getByRole("combobox", { name: "Constraints per page" })
    ).toBeTruthy();
    expect(screen.getByText("Showing 1–1 of 1")).toBeTruthy();
  });

  it("returns to the first page when the constraint kind changes", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        ...createCheckConstraints(10),
        create(TableConstraintSchema, {
          columnNames: ["id"],
          constraintName: "customers_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        }),
      ],
    });

    renderConstraintsTab();

    await user.click(screen.getByRole("button", { name: "Next page" }));
    await user.click(screen.getByRole("button", { name: KIND_FILTER_RE }));
    await user.click(screen.getByRole("option", { name: "PRIMARY KEY" }));

    expect(screen.getByText("customers_pkey")).toBeTruthy();
    expect(screen.queryByText("customers_status_1_check")).toBeNull();
  });

  it("keeps a valid page when refreshed constraints shrink", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: createCheckConstraints(11),
    });
    const { rerender } = renderConstraintsTab();

    await user.click(screen.getByRole("button", { name: "Next page" }));

    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["status"],
          constraintName: "customers_status_check",
          definition: "CHECK (status <> '')",
          type: ConstraintType.CHECK,
        }),
      ],
    });
    rerender(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema)}
        tableName="customers"
      />
    );

    expect(screen.getByText("customers_status_check")).toBeTruthy();
  });
});

describe("TableDetail constraints tab", () => {
  it("keeps search left of the inline kind filter and combines both", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["id"],
          constraintName: "customers_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        }),
        create(TableConstraintSchema, {
          columnNames: ["account_id"],
          constraintName: "customers_account_id_fkey",
          definition: "FOREIGN KEY (account_id) REFERENCES public.accounts(id)",
          type: ConstraintType.FOREIGN_KEY,
        }),
        create(TableConstraintSchema, {
          columnNames: ["status"],
          constraintName: "customers_status_check",
          definition: "CHECK (status <> '')",
          type: ConstraintType.CHECK,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema)}
        tableName="customers"
      />
    );

    const search = screen.getByRole("textbox", {
      name: "Search constraints…",
    });
    const kindFilter = screen.getByRole("button", { name: KIND_FILTER_RE });
    const filterControls = search.closest(
      '[data-slot="constraints-filter-controls"]'
    );

    expect(filterControls).not.toBeNull();
    expect(filterControls?.contains(kindFilter)).toBe(true);
    expect(filterControls?.firstElementChild?.contains(search)).toBe(true);
    expect(filterControls?.lastElementChild?.contains(kindFilter)).toBe(true);

    await user.type(search, "account_id");

    expect(screen.getByText("customers_account_id_fkey")).toBeTruthy();
    expect(screen.queryByText("customers_pkey")).toBeNull();
    expect(screen.queryByText("customers_status_check")).toBeNull();

    await user.click(kindFilter);
    await user.click(screen.getByRole("option", { name: "CHECK" }));

    expect(screen.getByText("No constraints found")).toBeTruthy();

    await user.clear(search);

    expect(screen.getByText("customers_status_check")).toBeTruthy();
    expect(screen.queryByText("customers_pkey")).toBeNull();
    expect(screen.queryByText("customers_account_id_fkey")).toBeNull();
  });

  it("groups keys and outbound foreign keys as constraint cards", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.dataUpdatedAt = Date.UTC(2026, 0, 1, 23);
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["id"],
          constraintName: "shipment_event_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        }),
        create(TableConstraintSchema, {
          columnNames: ["shipment_id"],
          constraintName: "shipment_event_shipment_id_fkey",
          definition:
            "FOREIGN KEY (shipment_id) REFERENCES shipping.shipments(id) ON DELETE CASCADE",
          onDelete: ReferentialAction.CASCADE,
          referencedColumnNames: ["id"],
          referencedTable:
            "instances/prod/databases/app/schemas/shipping/tables/shipments",
          type: ConstraintType.FOREIGN_KEY,
        }),
      ],
    });

    const { container } = render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="shipping"
        table={create(TableSchema, { rowCount: 18_200_000n, sizeBytes: 4096n })}
        tableName="shipment_event"
      />
    );

    expect(
      screen.getByRole("heading", {
        name: "Keys primary key and uniqueness",
      })
    ).toBeTruthy();
    expect(
      screen.getByRole("heading", {
        name: "Foreign keys outbound references from this table",
      })
    ).toBeTruthy();
    expect(screen.getByText("shipment_event_pkey")).toBeTruthy();
    expect(screen.getByText("shipment_event_shipment_id_fkey")).toBeTruthy();
    expect(
      screen.getByText("ON DELETE CASCADE", {
        selector: '[data-slot="badge"]',
      })
    ).toBeTruthy();
    expect(
      screen
        .getByRole("link", { name: "shipping.shipments" })
        .getAttribute("href")
    ).toBe(
      "/instances/prod/databases/app/explorer?schema=shipping&category=tables&name=shipments"
    );
    const highlightedDefinitions = Array.from(
      container.querySelectorAll(
        'code.language-sql[data-syntax-highlighter="shiki"]'
      )
    );
    expect(highlightedDefinitions.map((code) => code.textContent)).toEqual([
      "PRIMARY KEY (id)",
      "FOREIGN KEY (shipment_id) REFERENCES shipping.shipments(id) ON DELETE CASCADE",
    ]);
    expect(
      container.querySelectorAll("[data-shiki-token]").length
    ).toBeGreaterThan(8);
    expect(screen.queryByRole("button", { name: "Copy SQL" })).toBeNull();
    expect(screen.queryByRole("table")).toBeNull();
    expect(screen.getByText(LAST_FETCHED_RE)).toBeTruthy();

    await user.click(screen.getByRole("button", { name: "Refresh" }));

    expect(tableQueries.constraints.refetch).toHaveBeenCalledOnce();
  });

  it("uses readable plain-text fallbacks for incomplete metadata", () => {
    const malformedReference =
      "instances/prod/databases/app/tables/legacy_orders";
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["order_id"],
          constraintName: "orders_order_id_fkey",
          referencedTable: malformedReference,
          type: ConstraintType.FOREIGN_KEY,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema)}
        tableName="orders"
      />
    );

    const card = screen.getByText("orders_order_id_fkey").closest("article");
    expect(card).not.toBeNull();
    expect(within(card as HTMLElement).getByText("legacy_orders")).toBeTruthy();
    expect(
      within(card as HTMLElement).queryByText(malformedReference)
    ).toBeNull();
    expect(
      within(card as HTMLElement).getByText("FOREIGN KEY (order_id)")
    ).toBeTruthy();
    expect(
      card?.querySelector('code[data-syntax-highlighter="shiki"]')
    ).toBeNull();
  });

  it("shows design-export validation badges and check groups", () => {
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["account_id"],
          constraintName: "customers_account_id_fkey",
          definition:
            "FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE RESTRICT",
          onDelete: ReferentialAction.RESTRICT,
          referencedColumnNames: ["id"],
          referencedTable:
            "instances/prod/databases/app/schemas/public/tables/accounts",
          type: ConstraintType.FOREIGN_KEY,
        }),
        create(TableConstraintSchema, {
          columnNames: ["status"],
          constraintName: "customers_status_check",
          definition: "CHECK (status IN ('active', 'archived'))",
          type: ConstraintType.CHECK,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, { rowCount: 12n, sizeBytes: 4096n })}
        tableName="customers"
      />
    );

    expect(
      screen.getByText("ON DELETE RESTRICT", {
        selector: '[data-slot="badge"]',
      })
    ).toBeTruthy();
    expect(screen.getAllByText("validated")).toHaveLength(2);
    expect(
      screen.getByRole("heading", {
        name: "Checks row-level validation rules",
      })
    ).toBeTruthy();
    expect(screen.queryByText("Other constraints")).toBeNull();
  });

  it("only treats a trailing NOT VALID clause as unvalidated", () => {
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["notes"],
          constraintName: "customers_notes_check",
          definition: "CHECK (notes <> 'NOT VALID')",
          type: ConstraintType.CHECK,
        }),
        create(TableConstraintSchema, {
          columnNames: ["status"],
          constraintName: "customers_status_not_valid_check",
          definition: "CHECK (status <> 'deleted') NOT VALID",
          type: ConstraintType.CHECK,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema)}
        tableName="customers"
      />
    );

    const validatedCard = screen
      .getByText("customers_notes_check")
      .closest("article");
    const notValidCard = screen
      .getByText("customers_status_not_valid_check")
      .closest("article");

    expect(validatedCard).not.toBeNull();
    expect(notValidCard).not.toBeNull();
    expect(
      within(validatedCard as HTMLElement).getByText("validated")
    ).toBeTruthy();
    expect(
      within(validatedCard as HTMLElement).queryByText("NOT VALID")
    ).toBeNull();
    expect(
      within(notValidCard as HTMLElement).getByText("NOT VALID", {
        selector: '[data-slot="badge"]',
      })
    ).toBeTruthy();
    expect(
      within(notValidCard as HTMLElement).queryByText("validated")
    ).toBeNull();
  });
});

describe("TableDetail metadata errors", () => {
  it("keeps available definition sections when optional metadata fails", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "id",
          isNullable: false,
          ordinalPosition: 1,
          rawType: "bigint",
        },
      ],
    });
    tableQueries.indexes.error = createMetadataError({
      code: Code.PermissionDenied,
      conditionName: "insufficient_privilege",
      message: "missing index access",
      operation: "list_indexes",
      reason: "PERMISSION_DENIED",
      sqlstate: "42501",
      sqlstateClass: "42",
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(getSqlCodeBlock(CREATE_TABLE_SQL_RE)).toBeTruthy();
    expect(screen.getByText("PostgreSQL permission denied")).toBeTruthy();
  });

  it("renders SQLSTATE-aware tab errors with retry and copyable details", async () => {
    const user = userEvent.setup();
    tableQueries.indexes.error = createMetadataError({
      code: Code.PermissionDenied,
      conditionName: "insufficient_privilege",
      message: "missing index access",
      operation: "list_indexes",
      reason: "PERMISSION_DENIED",
      sqlstate: "42501",
      sqlstateClass: "42",
    });
    tableQueries.indexes.data = undefined;

    render(
      <TableDetail
        databaseId="app"
        initialTab="indexes"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, { rowCount: 12n, sizeBytes: 4096n })}
        tableName="customers"
      />
    );

    expect(screen.getByText("PostgreSQL permission denied")).toBeTruthy();
    expect(
      screen.getByText("Retry after checking the role or grants.")
    ).toBeTruthy();
    expect(screen.getByRole("button", { name: "Retry" })).toBeTruthy();

    await user.click(screen.getByRole("button", { name: "Error details" }));

    expect(screen.getByText("Code: PermissionDenied")).toBeTruthy();
    expect(screen.getByText("SQLSTATE: 42501")).toBeTruthy();
    expect(screen.getByText("Condition: insufficient_privilege")).toBeTruthy();
    expect(screen.getByText("Endpoint: ListTableIndexes")).toBeTruthy();
    expect(screen.getByRole("button", { name: "Copy details" })).toBeTruthy();
  });

  it("renders every failed metadata query with real RPC endpoints", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.error = createMetadataError({
      code: Code.PermissionDenied,
      conditionName: "insufficient_privilege",
      message: "missing constraint access",
      operation: "list_constraints",
      reason: "PERMISSION_DENIED",
      sqlstate: "42501",
      sqlstateClass: "42",
    });
    tableQueries.constraints.data = undefined;
    tableQueries.indexes.error = createMetadataError({
      code: Code.Unavailable,
      conditionName: "cannot_connect_now",
      message: "server unavailable",
      operation: "list_indexes",
      reason: "UNAVAILABLE",
      sqlstate: "57P03",
      sqlstateClass: "57",
    });
    tableQueries.indexes.data = undefined;

    render(
      <TableDetail
        databaseId="app"
        initialTab="columns"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, { rowCount: 12n, sizeBytes: 4096n })}
        tableName="customers"
      />
    );

    const detailButtons = screen.getAllByRole("button", {
      name: "Error details",
    });
    expect(detailButtons).toHaveLength(2);

    const endpoints = new Set<string>();
    for (const detailButton of detailButtons) {
      await user.click(detailButton);
      for (const endpoint of ["ListTableConstraints", "ListTableIndexes"]) {
        if (screen.queryByText(`Endpoint: ${endpoint}`)) {
          endpoints.add(endpoint);
        }
      }
      expect(screen.queryByText("Endpoint: TableDetail/columns")).toBeNull();
      await user.keyboard("{Escape}");
    }
    expect(endpoints).toEqual(
      new Set(["ListTableConstraints", "ListTableIndexes"])
    );
  });
});

function renderPoliciesTab(policies: TablePolicy[]) {
  tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
    policies,
  });
  return render(
    <TableDetail
      databaseId="app"
      initialTab="policies"
      instanceId="prod"
      schemaName="billing"
      table={create(TableSchema)}
      tableName="invoices"
    />
  );
}

function createPolicies(count: number): TablePolicy[] {
  return Array.from({ length: count }, (_, index) =>
    create(TablePolicySchema, {
      command: PolicyCommand.SELECT,
      mode: PolicyMode.PERMISSIVE,
      policyName: `invoices_policy_${index + 1}`,
      roles: ["app_reader"],
      usingExpression: `tenant_id = ${index + 1}`,
    })
  );
}

describe("TableDetail policies tab pagination", () => {
  it("paginates policy cards six at a time", async () => {
    const user = userEvent.setup();
    renderPoliciesTab(createPolicies(7));

    expect(
      screen.getByRole("heading", { name: "invoices_policy_1" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "invoices_policy_7" })
    ).toBeNull();
    expect(screen.getByText("Showing 1–6 of 7 policies")).toBeTruthy();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
    expect(screen.getByRole("status").textContent).toBe("Page 1 of 2");

    await user.click(
      screen.getByRole("button", { name: "Next policies page" })
    );

    expect(
      screen.queryByRole("heading", { name: "invoices_policy_1" })
    ).toBeNull();
    expect(
      screen.getByRole("heading", { name: "invoices_policy_7" })
    ).toBeTruthy();
    expect(screen.getByText("Showing 7–7 of 7 policies")).toBeTruthy();
    expect(screen.getByText("Page 2 of 2")).toBeTruthy();
    expect(screen.getByRole("status").textContent).toBe("Page 2 of 2");
  });

  it("changes policy page size using the resource-card options", async () => {
    const user = userEvent.setup();
    renderPoliciesTab(createPolicies(13));

    await user.click(
      screen.getByRole("button", { name: "Next policies page" })
    );
    const pageSizeSelect = screen.getByRole("combobox", { name: "Per page" });
    expect(pageSizeSelect.textContent).toContain("6");

    await user.click(pageSizeSelect);
    expect(screen.getByRole("option", { name: "6" })).toBeTruthy();
    expect(screen.getByRole("option", { name: "12" })).toBeTruthy();
    expect(screen.getByRole("option", { name: "24" })).toBeTruthy();
    await user.click(screen.getByRole("option", { name: "12" }));

    expect(
      screen.getByRole("heading", { name: "invoices_policy_1" })
    ).toBeTruthy();
    expect(
      screen.getByRole("heading", { name: "invoices_policy_12" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "invoices_policy_13" })
    ).toBeNull();
    expect(screen.getByText("Showing 1–12 of 13 policies")).toBeTruthy();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
  });

  it("returns to the first policy page when search changes", async () => {
    const user = userEvent.setup();
    renderPoliciesTab(createPolicies(7));

    await user.click(
      screen.getByRole("button", { name: "Next policies page" })
    );
    const search = screen.getByRole("textbox", { name: "Search policies…" });
    await user.type(search, "policy_1");
    await user.clear(search);

    expect(
      screen.getByRole("heading", { name: "invoices_policy_1" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "invoices_policy_7" })
    ).toBeNull();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
  });

  it("returns to the first policy page when mode filters change", async () => {
    const user = userEvent.setup();
    renderPoliciesTab(
      Array.from({ length: 7 }, (_, index) =>
        create(TablePolicySchema, {
          command: PolicyCommand.SELECT,
          mode: index === 6 ? PolicyMode.RESTRICTIVE : PolicyMode.PERMISSIVE,
          policyName: `invoices_policy_${index + 1}`,
          roles: ["app_reader"],
          usingExpression: `tenant_id = ${index + 1}`,
        })
      )
    );

    await user.click(
      screen.getByRole("button", { name: "Next policies page" })
    );
    await user.click(screen.getByRole("button", { name: "Mode" }));
    await user.click(screen.getByRole("option", { name: "Restrictive" }));
    await user.click(screen.getByRole("option", { name: "Clear filter" }));

    expect(
      screen.getByRole("heading", { name: "invoices_policy_1" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "invoices_policy_7" })
    ).toBeNull();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
  });

  it("navigates from the clamped page after refreshed policies shrink", async () => {
    const user = userEvent.setup();
    const { rerender } = renderPoliciesTab(createPolicies(25));
    const nextPage = screen.getByRole("button", {
      name: "Next policies page",
    });
    await user.click(nextPage);
    await user.click(nextPage);
    await user.click(nextPage);
    await user.click(nextPage);
    expect(
      screen.getByRole("heading", { name: "invoices_policy_25" })
    ).toBeTruthy();

    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: createPolicies(7),
    });
    rerender(
      <TableDetail
        databaseId="app"
        initialTab="policies"
        instanceId="prod"
        schemaName="billing"
        table={create(TableSchema)}
        tableName="invoices"
      />
    );

    await user.click(
      screen.getByRole("button", { name: "Previous policies page" })
    );

    expect(
      screen.getByRole("heading", { name: "invoices_policy_1" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "invoices_policy_7" })
    ).toBeNull();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
  });
});

describe("TableDetail policies tab", () => {
  it("explains RLS policy cards and previews matching policies by role and command", async () => {
    const user = userEvent.setup();
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        create(TablePolicySchema, {
          checkExpression: "customer = current_setting('app.tenant')",
          command: PolicyCommand.ALL,
          mode: PolicyMode.PERMISSIVE,
          policyName: "invoices_tenant_all",
          roles: ["app_readwrite"],
          usingExpression: "customer = current_setting('app.tenant')",
        }),
        create(TablePolicySchema, {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.PERMISSIVE,
          policyName: "invoices_finance_select",
          roles: ["app_readwrite"],
          usingExpression: "pg_has_role(current_user, 'billing', 'member')",
        }),
        create(TablePolicySchema, {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.PERMISSIVE,
          policyName: "invoices_reader_recent",
          roles: ["app_readonly"],
          usingExpression: "issued_at >= now() - interval '90 days'",
        }),
      ],
    });

    const { container } = render(
      <TableDetail
        databaseId="app"
        initialTab="policies"
        instanceId="prod"
        schemaName="billing"
        table={create(TableSchema, { rowCount: 940_000n, sizeBytes: 4096n })}
        tableName="invoices"
      />
    );

    expect(
      screen.getByText(
        "This table defines row-level security policies; table owners and BYPASSRLS roles may bypass them"
      )
    ).toBeTruthy();
    expect(
      screen.getByRole("heading", {
        level: 2,
        name: "invoices_tenant_all",
      })
    ).toBeTruthy();
    expect(screen.getAllByText("FOR SELECT")).toHaveLength(2);
    expect(screen.getAllByText("PERMISSIVE")).toHaveLength(3);
    expect(screen.getAllByText("TO app_readwrite")).toHaveLength(2);
    expect(screen.getByText("WITH CHECK")).toBeTruthy();
    expect(screen.getByText("How the server combines these")).toBeTruthy();
    const sqlExpressions = Array.from(
      container.querySelectorAll(
        'code.language-sql[data-syntax-highlighter="shiki"]'
      ),
      (code) => code.textContent
    );
    expect(sqlExpressions).toHaveLength(5);
    expect(sqlExpressions).toContain(
      "customer = current_setting('app.tenant')"
    );
    expect(screen.queryAllByRole("button", { name: "Copy SQL" })).toHaveLength(
      0
    );

    expect(
      screen.getByText(
        "2 permissive policies apply — a row passes if any one matches. Rows visible to app_readwrite are those where:"
      )
    ).toBeTruthy();
    expect(
      screen.getAllByText("invoices_finance_select").length
    ).toBeGreaterThan(0);
    expect(sqlExpressions).toContain(
      "(customer = current_setting('app.tenant'))\nOR (pg_has_role(current_user, 'billing', 'member'))"
    );
    expect(screen.queryByText("invoices_reader_recent")).toBeTruthy();

    await user.click(screen.getByRole("combobox", { name: "Policy command" }));
    await user.click(screen.getByRole("option", { name: "INSERT" }));

    expect(
      screen.getByText(
        "1 permissive policy applies — a new row passes if it matches. New rows inserted by app_readwrite must satisfy:"
      )
    ).toBeTruthy();
    expect(
      Array.from(
        container.querySelectorAll(
          'code.language-sql[data-syntax-highlighter="shiki"]'
        ),
        (code) => code.textContent
      )
    ).not.toContain(
      "(customer = current_setting('app.tenant'))\nOR (pg_has_role(current_user, 'billing', 'member'))"
    );

    await user.click(screen.getByRole("combobox", { name: "Policy role" }));
    await user.click(screen.getByRole("option", { name: "app_readonly" }));

    const rejectedInsertVerdict = screen.getByText(
      "No permissive policy applies — RLS rejects every INSERT by app_readonly."
    );
    expect(rejectedInsertVerdict).toBeTruthy();
    expect(
      rejectedInsertVerdict.closest('[aria-live="polite"]')
    ).not.toBeNull();
  });

  it("searches policy cards by name without changing the RLS preview", async () => {
    const user = userEvent.setup();
    renderPoliciesTab([
      create(TablePolicySchema, {
        command: PolicyCommand.SELECT,
        mode: PolicyMode.PERMISSIVE,
        policyName: "invoices_tenant_select",
        roles: ["app_reader"],
        usingExpression: "tenant_id = current_setting('app.tenant')",
      }),
      create(TablePolicySchema, {
        command: PolicyCommand.SELECT,
        mode: PolicyMode.PERMISSIVE,
        policyName: "invoices_finance_select",
        roles: ["app_reader"],
        usingExpression: "department = 'finance'",
      }),
    ]);

    await user.type(
      screen.getByRole("textbox", { name: "Search policies…" }),
      "finance"
    );

    expect(
      screen.queryByRole("heading", { name: "invoices_tenant_select" })
    ).toBeNull();
    expect(
      screen.getByRole("heading", { name: "invoices_finance_select" })
    ).toBeTruthy();
    expect(
      screen.getByText("2 permissive policies apply", { exact: false })
    ).toBeTruthy();
  });

  it("filters policy cards by mode without changing the RLS preview", async () => {
    const user = userEvent.setup();
    renderPoliciesTab([
      create(TablePolicySchema, {
        command: PolicyCommand.SELECT,
        mode: PolicyMode.PERMISSIVE,
        policyName: "invoices_tenant_select",
        roles: ["app_reader"],
        usingExpression: "tenant_id = current_setting('app.tenant')",
      }),
      create(TablePolicySchema, {
        command: PolicyCommand.SELECT,
        mode: PolicyMode.RESTRICTIVE,
        policyName: "invoices_not_suspended",
        roles: ["app_reader"],
        usingExpression: "NOT suspended",
      }),
    ]);

    await user.click(screen.getByRole("button", { name: "Mode" }));
    await user.click(screen.getByRole("option", { name: "Restrictive" }));

    expect(
      screen.queryByRole("heading", { name: "invoices_tenant_select" })
    ).toBeNull();
    expect(
      screen.getByRole("heading", { name: "invoices_not_suspended" })
    ).toBeTruthy();
    expect(
      screen.getByText("1 restrictive policy must also pass", { exact: false })
    ).toBeTruthy();
  });

  it("keeps policy filters available when no cards match", async () => {
    const user = userEvent.setup();
    renderPoliciesTab([
      create(TablePolicySchema, {
        command: PolicyCommand.SELECT,
        mode: PolicyMode.PERMISSIVE,
        policyName: "invoices_tenant_select",
        roles: ["app_reader"],
        usingExpression: "tenant_id = current_setting('app.tenant')",
      }),
    ]);

    const search = screen.getByRole("textbox", { name: "Search policies…" });
    await user.type(search, "missing");

    expect(screen.getByText("No policies found")).toBeTruthy();
    expect(screen.getByRole("button", { name: "Mode" })).toBeTruthy();

    await user.clear(search);
    expect(
      screen.getByRole("heading", { name: "invoices_tenant_select" })
    ).toBeTruthy();
  });

  it("previews UPDATE visibility from USING without folding in WITH CHECK", async () => {
    const user = userEvent.setup();
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        create(TablePolicySchema, {
          checkExpression: "status <> 'archived'",
          command: PolicyCommand.UPDATE,
          mode: PolicyMode.PERMISSIVE,
          policyName: "invoices_tenant_update",
          roles: ["app_writer"],
          usingExpression: "tenant_id = current_setting('app.tenant')",
        }),
      ],
    });

    const { container } = render(
      <TableDetail
        databaseId="app"
        initialTab="policies"
        instanceId="prod"
        schemaName="billing"
        table={create(TableSchema)}
        tableName="invoices"
      />
    );

    await user.click(screen.getByRole("combobox", { name: "Policy command" }));
    await user.click(screen.getByRole("option", { name: "UPDATE" }));

    const sqlExpressions = Array.from(
      container.querySelectorAll(
        'code.language-sql[data-syntax-highlighter="shiki"]'
      ),
      (code) => code.textContent
    );
    expect(sqlExpressions.at(-1)).toBe(
      "(tenant_id = current_setting('app.tenant'))"
    );
  });

  it("ANDs restrictive policies on top without double-wrapping permissive predicates", () => {
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        create(TablePolicySchema, {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.PERMISSIVE,
          policyName: "invoices_tenant_select",
          roles: ["app_reader"],
          usingExpression: "tenant_id = current_setting('app.tenant')",
        }),
        create(TablePolicySchema, {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.RESTRICTIVE,
          policyName: "invoices_not_suspended",
          roles: ["app_reader"],
          usingExpression: "NOT suspended",
        }),
      ],
    });

    const { container } = render(
      <TableDetail
        databaseId="app"
        initialTab="policies"
        instanceId="prod"
        schemaName="billing"
        table={create(TableSchema)}
        tableName="invoices"
      />
    );

    expect(screen.getByText("RESTRICTIVE")).toBeTruthy();
    expect(
      screen.getByText(
        "1 permissive policy applies — a row passes if it matches. 1 restrictive policy must also pass. Rows visible to app_reader are those where:"
      )
    ).toBeTruthy();
    expect(
      Array.from(
        container.querySelectorAll(
          'code.language-sql[data-syntax-highlighter="shiki"]'
        ),
        (code) => code.textContent
      ).at(-1)
    ).toBe("(tenant_id = current_setting('app.tenant'))\nAND (NOT suspended)");
  });
});
