import { create, toBinary } from "@bufbuild/protobuf";
import { Code, ConnectError } from "@connectrpc/connect";
import { afterEach, beforeEach, describe, expect, it, rs } from "@rstest/core";
import * as routerActual from "@tanstack/react-router" with {
  rstest: "importActual",
};
import {
  cleanup,
  render,
  screen,
  waitFor,
  within,
} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";

import type { GridRow } from "@/components/data-grid/table-data-grid/grid-row-model";
import { ROW_KEY_FIELD } from "@/components/data-grid/table-data-grid/grid-row-model";
import { TableDetail } from "@/features/data-explorer/explorer-table-detail";
import {
  PostgreSqlErrorDetailSchema,
  PostgreSqlErrorKind,
  PostgreSqlErrorRetryGuidance,
} from "@/protogen/querylane/console/v1alpha1/errors_pb";
import {
  ReadRowsResponseSchema,
  TableResultSetSchema,
} from "@/protogen/querylane/console/v1alpha1/table_data_pb";
import {
  ColumnSchema,
  ConstraintType,
  DataType,
  GetTablePartitionMetadataResponseSchema,
  IdentityGeneration,
  ListTableColumnsResponseSchema,
  ListTableConstraintsResponseSchema,
  ListTableIndexesResponseSchema,
  ListTablePoliciesResponseSchema,
  ListTableTriggersResponseSchema,
  PolicyCommand,
  PolicyMode,
  Table_TableType,
  TableConstraintSchema,
  TableIndexSchema,
  type TablePolicy,
  TablePolicySchema,
  TableSchema,
  TableTriggerSchema,
} from "@/protogen/querylane/console/v1alpha1/table_pb";

const POSTGRES_DETAIL_TYPE = "querylane.console.v1alpha1.PostgreSqlErrorDetail";
const COLUMNS_TAB_RE = /^Columns/;
const CREATE_TABLE_SQL_RE = /CREATE TABLE "public"\."customers" \(/;
const INDEXES_TAB_RE = /^Indexes/;
const IDENTITY_COLUMN_SQL_RE =
  /"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL/;
const PRIMARY_KEY_CONSTRAINT_SQL_RE =
  /ALTER TABLE "public"\."customers" ADD CONSTRAINT "customers_pkey" PRIMARY KEY \(id\);/;
const PRIMARY_KEY_INDEX_SQL_RE =
  /CREATE UNIQUE INDEX "customers_pkey" ON "public"\."customers" USING btree \("id"\);/;
const TRIGGER_SQL_RE =
  /CREATE TRIGGER customers_audit_trigger\s+AFTER INSERT OR UPDATE ON public\.customers\s+FOR EACH ROW EXECUTE FUNCTION audit_customer_changes\(\);/;
const SNIPPET_TRIGGER_UNAVAILABLE_RE =
  /-- Trigger "customers_search_trigger": full definition unavailable/;
const FULL_TRIGGER_STATEMENTS_SQL_RE =
  /CREATE TRIGGER customers_replica_trigger\s+AFTER DELETE ON public\.customers\s+FOR EACH ROW EXECUTE FUNCTION audit_customer_changes\(\);\s+CREATE TRIGGER customers_statement_trigger\s+BEFORE UPDATE ON public\.customers\s+FOR EACH STATEMENT EXECUTE FUNCTION sync_customer_summary\(\);/;
const PARTITIONED_TABLE_SQL_RE =
  /CREATE TABLE "public"\."events" \([\s\S]*\) PARTITION BY RANGE \(created_at\);/;
const CHILD_PARTITION_SQL_RE =
  /CREATE TABLE "archive"\."events_2025" PARTITION OF "public"\."events"\s+FOR VALUES FROM \('2025-01-01'\) TO \('2026-01-01'\);/;
const KIND_FILTER_RE = /^Kind$/;
const LAST_FETCHED_RE = /^Last fetched/;
const COMMAND_REGION_RE = /command$/;

rs.mock("@tanstack/react-router", () => {
  const linkExportName = "Link";
  return {
    ...routerActual,
    [linkExportName]: ({
      children,
      params,
      search,
    }: {
      children: ReactNode;
      params: { databaseId: string; instanceId: string };
      search: { category: string; name: string; schema: string };
    }) => (
      <a
        href={`/instances/${params.instanceId}/databases/${params.databaseId}/explorer?schema=${search.schema}&category=${search.category}&name=${search.name}`}
      >
        {children}
      </a>
    ),
  };
});

interface MockGridColumn {
  key: string;
  renderCell?: (args: { row: GridRow; rowIdx: number }) => ReactNode;
  renderHeaderCell?: () => ReactNode;
}

interface MockGridProps {
  columns?: MockGridColumn[];
  rows?: GridRow[];
}

function querySqlCodeBlock(pattern: RegExp) {
  return Array.from(
    document.querySelectorAll<HTMLElement>("code.language-sql")
  ).find((codeBlock) => pattern.test(codeBlock.textContent ?? ""));
}

function getSqlCodeBlock(pattern: RegExp) {
  const codeBlock = querySqlCodeBlock(pattern);
  if (!codeBlock) {
    throw new Error(`Expected a SQL block matching ${pattern}.`);
  }
  return codeBlock;
}

const tableQueries = rs.hoisted(() => ({
  columns: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(() => Promise.resolve()),
  },
  constraints: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(() => Promise.resolve()),
  },
  indexes: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(() => Promise.resolve()),
  },
  partitionMetadata: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(() => Promise.resolve()),
  },
  policies: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(() => Promise.resolve()),
  },
  triggers: {
    data: undefined as unknown,
    dataUpdatedAt: 0,
    error: null as Error | null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(() => Promise.resolve()),
  },
}));

const tableDataApi = rs.hoisted(() => ({
  useReadCellValueMutation: rs.fn(),
  useReadRowsQuery: rs.fn(),
  useReadRowsQueryActions: rs.fn(() => ({
    fetch: rs.fn(() => Promise.resolve()),
    getState: rs.fn(() => ({ fetchStatus: "idle", status: "success" })),
    prefetch: rs.fn(),
  })),
  useStreamRowsExporter: rs.fn(),
}));

const reactDataGrid = rs.hoisted(() => ({
  dataGrid: rs.fn((props: MockGridProps) => (
    <div data-testid="data-grid">
      {props.rows?.map((row, rowIndex) => (
        <div key={row[ROW_KEY_FIELD]}>
          {props.columns?.map((column) => (
            <div data-testid={`grid-cell-${column.key}`} key={column.key}>
              {column.renderCell?.({ row, rowIdx: rowIndex })}
            </div>
          ))}
        </div>
      ))}
    </div>
  )),
}));

rs.mock("react-data-grid", () => ({
  ...Object.fromEntries([
    ["DataGrid", reactDataGrid.dataGrid],
    ["SelectColumn", { columnName: "", key: "__select" }],
  ]),
  SELECT_COLUMN_KEY: "__select",
}));

rs.mock("@/hooks/api/table", () => ({
  useGetTablePartitionMetadataQuery: () => tableQueries.partitionMetadata,
  useListTableColumnsQuery: () => tableQueries.columns,
  useListTableConstraintsQuery: () => tableQueries.constraints,
  useListTableIndexesQuery: () => tableQueries.indexes,
  useListTablePoliciesQuery: () => tableQueries.policies,
  useListTableTriggersQuery: () => tableQueries.triggers,
}));

rs.mock("@/hooks/api/table-data", () => ({
  useReadCellValueMutation: tableDataApi.useReadCellValueMutation,
  useReadRowsQuery: tableDataApi.useReadRowsQuery,
  useReadRowsQueryActions: tableDataApi.useReadRowsQueryActions,
  useStreamRowsExporter: tableDataApi.useStreamRowsExporter,
}));

function seedSuccessfulMetadataQueries() {
  tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
    columns: [],
  });
  tableQueries.columns.error = null;
  tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
    constraints: [],
  });
  tableQueries.constraints.dataUpdatedAt = 0;
  tableQueries.constraints.error = null;
  tableQueries.constraints.isFetching = false;
  tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
    indexes: [],
  });
  tableQueries.indexes.error = null;
  tableQueries.partitionMetadata.data = create(
    GetTablePartitionMetadataResponseSchema,
    {}
  );
  tableQueries.partitionMetadata.error = null;
  tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
    policies: [],
  });
  tableQueries.policies.error = null;
  tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
    triggers: [],
  });
  tableQueries.triggers.error = null;
  tableDataApi.useReadRowsQuery.mockReturnValue({
    data: create(ReadRowsResponseSchema, {
      resultSet: create(TableResultSetSchema, {
        columns: [],
        rows: [],
      }),
    }),
    error: null,
    isFetching: false,
    isLoading: false,
    refetch: rs.fn(),
  });
  tableDataApi.useReadCellValueMutation.mockReturnValue({
    isError: false,
    isPending: false,
    mutate: rs.fn(),
  });
  tableDataApi.useStreamRowsExporter.mockReturnValue(rs.fn());
}

function createMetadataError({
  code,
  conditionName,
  kind,
  message,
  operation,
  reason,
  retryGuidance,
  sqlstate,
  sqlstateClass,
}: {
  code: Code;
  conditionName: string;
  kind: PostgreSqlErrorKind;
  message: string;
  operation: string;
  reason: string;
  retryGuidance: PostgreSqlErrorRetryGuidance;
  sqlstate: string;
  sqlstateClass: string;
}) {
  const error = new ConnectError(
    `PostgreSQL ${conditionName} during ${operation}: ${message}`,
    code
  );
  error.details = [
    {
      debug: {
        domain: "console.querylane.dev",
        metadata: {
          conditionName,
          operation,
          sqlstate,
          sqlstateClass,
        },
        reason,
      },
      type: "google.rpc.ErrorInfo",
      value: new Uint8Array([1]),
    },
    {
      type: POSTGRES_DETAIL_TYPE,
      value: toBinary(
        PostgreSqlErrorDetailSchema,
        create(PostgreSqlErrorDetailSchema, {
          conditionName,
          kind,
          operation,
          retryGuidance,
          sqlstate,
          sqlstateClass,
        })
      ),
    },
  ];
  return error;
}

function mockClipboardWriteText() {
  const originalClipboard = Object.getOwnPropertyDescriptor(
    navigator,
    "clipboard"
  );
  const writeText = rs.fn(() => Promise.resolve());
  Object.defineProperty(navigator, "clipboard", {
    configurable: true,
    value: { writeText },
  });
  return {
    restore: () => {
      if (originalClipboard) {
        Object.defineProperty(navigator, "clipboard", originalClipboard);
      } else {
        Reflect.deleteProperty(navigator, "clipboard");
      }
    },
    writeText,
  };
}

function getTableRowFor(text: string) {
  const row = screen.getByText(text).closest("tr");
  if (!row) {
    throw new Error(`Expected "${text}" to render inside a table row.`);
  }
  return row;
}

function getIndexSummaryStrip() {
  const strip = document.querySelector('[data-slot="index-summary-strip"]');
  if (!strip) {
    throw new Error("Expected the index summary strip to render.");
  }
  return strip;
}

function getSearchEmptyState() {
  const emptyState = document.querySelector('[data-slot="search-empty-state"]');
  if (!emptyState) {
    throw new Error("Expected the filtered-empty state to render.");
  }
  return emptyState;
}

beforeEach(() => {
  seedSuccessfulMetadataQueries();
});

afterEach(() => {
  cleanup();
  rs.clearAllMocks();
});

describe("TableDetail definition document", () => {
  it("renders the definition tab as a copyable schema document", async () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "id",
          dataType: DataType.INTEGER,
          identityGeneration: IdentityGeneration.BY_DEFAULT,
          isIdentity: true,
          isNullable: false,
          isPrimaryKey: true,
          ordinalPosition: 1,
          rawType: "bigint",
        },
        {
          columnName: "status",
          dataType: DataType.STRING,
          defaultValue: "'active'::text",
          isNullable: false,
          ordinalPosition: 2,
          rawType: "text",
        },
        {
          columnName: "metadata",
          dataType: DataType.JSON,
          defaultValue: "'{}'::jsonb",
          isNullable: true,
          ordinalPosition: 3,
          rawType: "jsonb",
        },
      ],
    });
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        {
          columnNames: ["id"],
          constraintName: "customers_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        },
      ],
    });
    tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
      indexes: [
        {
          indexName: "customers_pkey",
          isUnique: true,
          keyColumns: ["id"],
          method: "btree",
        },
        {
          indexName: "customers_status_idx",
          keyColumns: ["status"],
          method: "btree",
        },
      ],
    });
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        {
          command: PolicyCommand.SELECT,
          mode: PolicyMode.PERMISSIVE,
          policyName: "customers_account_read_policy",
          roles: ["app_reader"],
          usingExpression:
            "account_id = current_setting('app.account_id')::uuid",
        },
      ],
    });
    tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
      triggers: [
        {
          definition:
            "CREATE TRIGGER customers_audit_trigger\n  AFTER INSERT OR UPDATE ON public.customers\n  FOR EACH ROW EXECUTE FUNCTION audit_customer_changes()",
          enabled: true,
          events: ["INSERT", "UPDATE"],
          functionName: "audit_customer_changes",
          timing: "AFTER",
          triggerName: "customers_audit_trigger",
        },
        {
          definition:
            "CREATE TRIGGER customers_replica_trigger\n  AFTER DELETE ON public.customers\n  FOR EACH ROW EXECUTE FUNCTION audit_customer_changes()",
          enabled: true,
          triggerName: "customers_replica_trigger",
        },
        {
          definition:
            "CREATE TRIGGER customers_statement_trigger\n  BEFORE UPDATE ON public.customers\n  FOR EACH STATEMENT EXECUTE FUNCTION sync_customer_summary();",
          enabled: true,
          triggerName: "customers_statement_trigger",
        },
        {
          // Snippet-form definition: not reconstructable without guessing the
          // trigger level, so the document should say so instead.
          definition: "EXECUTE FUNCTION refresh_customer_search()",
          enabled: true,
          functionName: "refresh_customer_search",
          triggerName: "customers_search_trigger",
        },
      ],
    });

    const { container } = render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          rowCount: 987_654n,
          sizeBytes: 42_467_328n,
          tableType: Table_TableType.BASE_TABLE,
        })}
        tableName="customers"
      />
    );

    expect(screen.getByText("Schema document")).toBeTruthy();
    expect(screen.getByRole("heading", { name: "Create table" })).toBeTruthy();
    await waitFor(() => {
      expect(getSqlCodeBlock(CREATE_TABLE_SQL_RE)).toBeTruthy();
      expect(
        container.querySelectorAll(
          'code.language-bash[data-syntax-highlighter="shiki"]'
        )
      ).toHaveLength(3);
    });
    expect(getSqlCodeBlock(IDENTITY_COLUMN_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(PRIMARY_KEY_CONSTRAINT_SQL_RE)).toBeTruthy();
    expect(querySqlCodeBlock(PRIMARY_KEY_INDEX_SQL_RE)).toBeUndefined();
    expect(
      screen.getByText(
        "Exact index definitions are unavailable. Use the pg_dump command to preserve expressions, operator classes, and ordering."
      )
    ).toBeTruthy();
    expect(
      screen.getByText(
        "Policy definitions are available, but row-level security enablement and forced mode are not. Use the pg_dump command to reproduce policies safely."
      )
    ).toBeTruthy();
    expect(getSqlCodeBlock(TRIGGER_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(FULL_TRIGGER_STATEMENTS_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(SNIPPET_TRIGGER_UNAVAILABLE_RE)).toBeTruthy();
    const reproduceHeading = screen.getByRole("heading", {
      name: "Reproduce locally",
    });
    const reproduceCard =
      reproduceHeading.closest<HTMLElement>('[data-slot="card"]');
    if (!reproduceCard) {
      throw new Error("Expected the reproduce locally card to render.");
    }
    const reproduceCardQueries = within(reproduceCard);
    const scopeTabs = reproduceCardQueries.getByRole("tablist", {
      name: "Reproduction scope",
    });
    expect(scopeTabs.getAttribute("data-variant")).toBe("default");
    expect(
      reproduceCardQueries.getByRole("tab", { name: "customers" })
    ).toBeTruthy();
    expect(
      reproduceCardQueries.getByRole("tab", { name: "public" })
    ).toBeTruthy();
    expect(reproduceCardQueries.getByRole("tab", { name: "app" })).toBeTruthy();
    const copyAllSteps = reproduceCardQueries.getByRole("button", {
      name: "Copy all steps",
    });
    expect(
      reproduceHeading
        .closest('[data-slot="card-header"]')
        ?.contains(copyAllSteps)
    ).toBe(true);
    const highlightedCommands = Array.from(
      container.querySelectorAll(
        'pre code.language-bash[data-syntax-highlighter="shiki"]'
      )
    );
    expect(highlightedCommands).toHaveLength(3);
    const commandRegions = screen.getAllByRole("region", {
      name: COMMAND_REGION_RE,
    });
    expect(commandRegions).toHaveLength(3);
    expect(
      highlightedCommands.every(
        (command) => command.querySelectorAll("[data-shiki-token]").length > 3
      )
    ).toBe(true);
    expect(highlightedCommands[0]?.textContent).toBe(
      `pg_dump -h "$POSTGRES_HOST" \\\n  -U "$POSTGRES_ROLE" -d "\${DATABASE_NAME:-app}" \\\n  --schema-only --no-owner --no-privileges \\\n  --table='"public"."customers"' > 'customers.sql'`
    );
    expect(
      screen.getByRole("heading", { name: "Referenced tables" })
    ).toBeTruthy();
    expect(screen.getByText("No referenced tables")).toBeTruthy();
    expect(screen.queryByRole("heading", { name: "Dependencies" })).toBeNull();
    expect(
      screen.queryByRole("heading", { name: "Drift detection" })
    ).toBeNull();
    expect(screen.queryByText("Referenced by")).toBeNull();
    expect(screen.queryByRole("heading", { name: "Danger zone" })).toBeNull();
    expect(
      screen.getByText(
        "Definition is generated from pg_catalog on each visit; Querylane never stores or mutates schema."
      )
    ).toBeTruthy();
  });

  it("renders executable DDL for a partitioned table and its children", () => {
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        {
          columnName: "created_at",
          isNullable: false,
          ordinalPosition: 1,
          rawType: "timestamptz",
        },
      ],
    });
    tableQueries.partitionMetadata.data = create(
      GetTablePartitionMetadataResponseSchema,
      {
        partitionMetadata: {
          childPartitions: [
            {
              partitionBound:
                "FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')",
              table:
                "instances/prod/databases/app/schemas/archive/tables/events_2025",
            },
          ],
          partitionCount: 1,
          partitionKey: "RANGE (created_at)",
        },
      }
    );

    render(
      <TableDetail
        databaseId="app"
        initialTab="definition"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.PARTITIONED,
        })}
        tableName="events"
      />
    );

    expect(getSqlCodeBlock(PARTITIONED_TABLE_SQL_RE)).toBeTruthy();
    expect(getSqlCodeBlock(CHILD_PARTITION_SQL_RE)).toBeTruthy();
  });
});

describe("TableDetail definition safety", () => {
  it("shows copy failures instead of silently ignoring them", async () => {
    const user = userEvent.setup();
    const originalClipboard = Object.getOwnPropertyDescriptor(
      navigator,
      "clipboard"
    );
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: {
        writeText: rs.fn(() => Promise.reject(new Error("permission denied"))),
      },
    });

    try {
      render(
        <TableDetail
          databaseId="app"
          initialTab="definition"
          instanceId="prod"
          schemaName="public"
          table={create(TableSchema, {
            tableType: Table_TableType.BASE_TABLE,
          })}
          tableName="customers"
        />
      );

      await user.click(screen.getByRole("button", { name: "Copy all steps" }));

      expect(screen.getByRole("button", { name: "Copy failed" })).toBeTruthy();
    } finally {
      if (originalClipboard) {
        Object.defineProperty(navigator, "clipboard", originalClipboard);
      } else {
        Reflect.deleteProperty(navigator, "clipboard");
      }
    }
  });
});

describe("TableDetail tab routing", () => {
  it("honors URL-backed metadata tabs and reports tab changes", async () => {
    const user = userEvent.setup();
    const onTabChange = rs.fn();

    render(
      <TableDetail
        databaseId="app"
        initialTab="columns"
        instanceId="prod"
        onTabChange={onTabChange}
        schemaName="commerce"
        table={create(TableSchema, { rowCount: 72_000n, sizeBytes: 4096n })}
        tableName="order_event_2026_h1"
      />
    );

    expect(
      screen
        .getByRole("tab", { name: COLUMNS_TAB_RE })
        .hasAttribute("data-active")
    ).toBe(true);

    await user.click(screen.getByRole("tab", { name: INDEXES_TAB_RE }));

    expect(onTabChange).toHaveBeenCalledWith("indexes");
  });
});

describe("TableDetail partitions pagination", () => {
  it("shows summary cards without pagination chrome when no child partitions load", () => {
    tableQueries.partitionMetadata.data = create(
      GetTablePartitionMetadataResponseSchema,
      {
        partitionMetadata: {
          partitionCount: 0,
          partitionKey: "RANGE (created_at)",
        },
      }
    );

    render(
      <TableDetail
        databaseId="app"
        initialTab="partitions"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, {
          tableType: Table_TableType.PARTITIONED,
        })}
        tableName="events"
      />
    );

    expect(screen.getByText("Partition key")).toBeTruthy();
    expect(screen.getByText("RANGE (created_at)")).toBeTruthy();
    expect(
      screen.queryByRole("combobox", { name: "Rows per page" })
    ).toBeNull();
    expect(screen.queryByText("Page 1 of 1")).toBeNull();
  });
});

describe("TableDetail constraints tab", () => {
  it("combines the quicksearch with the inline kind filter", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["id"],
          constraintName: "customers_pkey",
          definition: "PRIMARY KEY (id)",
          type: ConstraintType.PRIMARY_KEY,
        }),
        create(TableConstraintSchema, {
          columnNames: ["account_id"],
          constraintName: "customers_account_id_fkey",
          definition: "FOREIGN KEY (account_id) REFERENCES public.accounts(id)",
          type: ConstraintType.FOREIGN_KEY,
        }),
        create(TableConstraintSchema, {
          columnNames: ["status"],
          constraintName: "customers_status_check",
          definition: "CHECK (status <> '')",
          type: ConstraintType.CHECK,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema)}
        tableName="customers"
      />
    );

    const search = screen.getByRole("textbox", {
      name: "Search constraints…",
    });
    const kindFilter = screen.getByRole("button", { name: KIND_FILTER_RE });

    await user.type(search, "account_id");

    expect(screen.getByText("customers_account_id_fkey")).toBeTruthy();
    expect(screen.queryByText("customers_pkey")).toBeNull();
    expect(screen.queryByText("customers_status_check")).toBeNull();

    await user.click(kindFilter);
    await user.click(screen.getByRole("option", { name: "CHECK" }));

    expect(getSearchEmptyState().textContent).toContain("No results found");

    await user.clear(search);

    expect(screen.getByText("customers_status_check")).toBeTruthy();
    expect(screen.queryByText("customers_pkey")).toBeNull();
    expect(screen.queryByText("customers_account_id_fkey")).toBeNull();
  });

  it("uses readable plain-text fallbacks for incomplete metadata", () => {
    const malformedReference =
      "instances/prod/databases/app/tables/legacy_orders";
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["order_id"],
          constraintName: "orders_order_id_fkey",
          referencedTable: malformedReference,
          type: ConstraintType.FOREIGN_KEY,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="constraints"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema)}
        tableName="orders"
      />
    );

    const row = getTableRowFor("orders_order_id_fkey");
    expect(within(row).getByText("legacy_orders")).toBeTruthy();
    expect(within(row).queryByText(malformedReference)).toBeNull();
    expect(within(row).getByText("FOREIGN KEY (order_id)")).toBeTruthy();
  });
});

describe("TableDetail columns tab", () => {
  it("renders and filters a dense column inventory", async () => {
    const user = userEvent.setup();
    tableQueries.columns.data = create(ListTableColumnsResponseSchema, {
      columns: [
        create(ColumnSchema, {
          columnName: "id",
          comment: "Surrogate key",
          dataType: DataType.UUID,
          defaultValue: "gen_random_uuid()",
          isNullable: false,
          isPrimaryKey: true,
          ordinalPosition: 1,
          rawType: "uuid",
        }),
        create(ColumnSchema, {
          columnName: "ref",
          comment: "Human-readable booking reference",
          dataType: DataType.STRING,
          isNullable: false,
          isUnique: true,
          ordinalPosition: 2,
          rawType: "text",
        }),
        create(ColumnSchema, {
          columnName: "carrier_id",
          dataType: DataType.INTEGER,
          isNullable: false,
          ordinalPosition: 3,
          rawType: "int4",
        }),
        create(ColumnSchema, {
          columnName: "eta",
          comment: "Set NULL once delivered",
          dataType: DataType.DATE,
          isNullable: true,
          ordinalPosition: 4,
          rawType: "date",
        }),
      ],
    });
    tableQueries.constraints.data = create(ListTableConstraintsResponseSchema, {
      constraints: [
        create(TableConstraintSchema, {
          columnNames: ["carrier_id"],
          referencedColumnNames: ["id"],
          referencedTable:
            "instances/prod/databases/app/schemas/public/tables/carriers",
          type: ConstraintType.FOREIGN_KEY,
        }),
      ],
    });
    tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
      indexes: [
        create(TableIndexSchema, {
          indexName: "shipments_ref_key",
          isUnique: true,
          keyColumns: ["ref"],
          method: "btree",
        }),
      ],
    });
    tableQueries.columns.dataUpdatedAt = Date.UTC(2026, 5, 30, 3, 12);
    tableQueries.constraints.dataUpdatedAt = Date.UTC(2026, 5, 30, 3, 12);
    tableQueries.indexes.dataUpdatedAt = Date.UTC(2026, 5, 30, 3, 12);

    render(
      <TableDetail
        databaseId="app"
        initialTab="columns"
        instanceId="prod"
        schemaName="shipping"
        table={create(TableSchema, {
          rowCount: 2_400_000n,
          sizeBytes: 12_800_000_000n,
        })}
        tableName="shipments"
      />
    );

    expect(screen.queryByText("4 columns · 2 indexed · 1 nullable")).toBeNull();
    for (const filter of [
      "Type",
      "Key",
      "Nullability",
      "Default",
      "Generation",
    ]) {
      expect(screen.getByRole("button", { name: filter })).toBeTruthy();
    }
    expect(screen.getByText("Catalog metadata")).toBeTruthy();
    expect(screen.getByText(LAST_FETCHED_RE)).toBeTruthy();
    expect(
      screen.getByRole("columnheader", { name: "Ordinal position" })
    ).toBeTruthy();
    expect(screen.getByRole("columnheader", { name: "Column" })).toBeTruthy();
    expect(screen.getByRole("columnheader", { name: "Nullable" })).toBeTruthy();
    expect(screen.getByRole("columnheader", { name: "Storage" })).toBeTruthy();
    expect(screen.getByRole("columnheader", { name: "Distinct" })).toBeTruthy();
    expect(screen.getByRole("columnheader", { name: "Null %" })).toBeTruthy();
    expect(
      screen.getByRole("columnheader", { name: "Avg width" })
    ).toBeTruthy();
    expect(screen.getByText("Surrogate key")).toBeTruthy();
    expect(screen.getByText("Human-readable booking reference")).toBeTruthy();
    expect(screen.getByText("Set NULL once delivered")).toBeTruthy();
    expect(screen.getByText("Primary key")).toBeTruthy();
    expect(screen.getByText("Unique")).toBeTruthy();
    expect(screen.getByText("Foreign key")).toBeTruthy();
    expect(screen.queryByText("PK")).toBeNull();
    expect(screen.queryByText("UQ")).toBeNull();
    expect(screen.queryByText("FK")).toBeNull();
    expect(screen.getByText("YES")).toBeTruthy();
    expect(screen.getAllByText("NO")).toHaveLength(3);
    expect(screen.getAllByText("0%")).toHaveLength(3);
    expect(screen.getByText("gen_random_uuid()")).toBeTruthy();
    expect(
      screen.getAllByTitle("Not available from the current column metadata API")
    ).toHaveLength(16);

    await user.click(screen.getByRole("button", { name: "Nullability" }));
    await user.click(screen.getByRole("option", { name: "Nullable" }));
    await waitFor(() => {
      expect(screen.queryByText("Surrogate key")).toBeNull();
    });
    expect(screen.getByText("Set NULL once delivered")).toBeTruthy();
    await user.click(screen.getByRole("button", { name: "Reset" }));

    const search = screen.getByRole("textbox", { name: "Search columns…" });
    await user.type(search, "booking");
    await waitFor(() => {
      expect(screen.queryByText("Surrogate key")).toBeNull();
    });
    expect(screen.getByText("Human-readable booking reference")).toBeTruthy();

    await user.clear(search);
    await user.type(search, "carriers.id");
    await waitFor(() => {
      expect(screen.getByText("carrier_id")).toBeTruthy();
    });
  });
});

describe("TableDetail indexes tab", () => {
  it("renders usage stats, partial indexes, expression indexes, and unused pills", () => {
    tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
      indexes: [
        create(TableIndexSchema, {
          blocksHit: 997n,
          blocksRead: 3n,
          definition:
            "CREATE UNIQUE INDEX shipments_pkey ON shipping.shipments USING btree (id)",
          hasUsageStats: true,
          indexName: "shipments_pkey",
          isUnique: true,
          isValid: true,
          keyColumns: ["id"],
          keyParts: ["id"],
          method: "btree",
          scanCount: 48_100_000n,
          sizeBytes: 312n * 1024n * 1024n,
          tuplesFetched: 48_100_000n,
          tuplesRead: 48_400_000n,
        }),
        create(TableIndexSchema, {
          blocksHit: 989n,
          blocksRead: 11n,
          definition:
            "CREATE INDEX shipments_status_idx ON shipping.shipments USING btree (status) WHERE status <> 'delivered'",
          hasUsageStats: true,
          indexName: "shipments_status_idx",
          isValid: true,
          keyColumns: ["status"],
          keyParts: ["status"],
          method: "btree",
          predicate: "status <> 'delivered'",
          scanCount: 9_400_000n,
          sizeBytes: 18n * 1024n * 1024n,
          tuplesFetched: 9_300_000n,
          tuplesRead: 11_200_000n,
        }),
        create(TableIndexSchema, {
          blocksHit: 991n,
          blocksRead: 9n,
          definition:
            "CREATE INDEX shipments_carrier_id_idx ON shipping.shipments USING btree (carrier_id)",
          hasUsageStats: true,
          indexName: "shipments_carrier_id_idx",
          isValid: true,
          keyColumns: ["carrier_id"],
          keyParts: ["carrier_id"],
          method: "btree",
          scanCount: 1_200_000n,
          sizeBytes: 52n * 1024n * 1024n,
          tuplesFetched: 1_200_000n,
          tuplesRead: 2_800_000n,
        }),
        create(TableIndexSchema, {
          definition:
            "CREATE INDEX shipments_legacy_ref_idx ON shipping.shipments USING btree (lower(ref))",
          hasExpression: true,
          hasUsageStats: true,
          indexName: "shipments_legacy_ref_idx",
          isValid: true,
          keyParts: ["lower(ref)"],
          method: "btree",
          sizeBytes: 96n * 1024n * 1024n,
        }),
      ],
    });

    render(
      <TableDetail
        databaseId="app"
        initialTab="indexes"
        instanceId="prod"
        schemaName="shipping"
        table={create(TableSchema, {
          rowCount: 2_400_000n,
          sizeBytes: 13_743_895_347n,
        })}
        tableName="shipments"
      />
    );

    expect(getIndexSummaryStrip().textContent).toBe(
      "4 indexes · 478 MB total vs heap 12.8 GB · 58.7M scans since stats reset · 1 unused"
    );
    expect(screen.getByText("48.1M")).toBeTruthy();
    expect(screen.getByText("9.4M")).toBeTruthy();
    expect(screen.getByText("1.2M")).toBeTruthy();
    expect(screen.getByText("99.7%")).toBeTruthy();
    expect(screen.getByText("98.9%")).toBeTruthy();
    expect(screen.getByText("99.1%")).toBeTruthy();
    // The predicate and expression are part of the Columns cell now.
    expect(
      screen.getByTitle("(status) WHERE status <> 'delivered'").textContent
    ).toBe("(status) WHERE status <> 'delivered'");
    expect(screen.getByTitle("(lower(ref))")).toBeTruthy();
    const unusedRow = getTableRowFor("shipments_legacy_ref_idx");
    expect(within(unusedRow).getByText("Unused")).toBeTruthy();
    expect(within(unusedRow).getByText("0")).toBeTruthy();
    expect(screen.getAllByText("Unused")).toHaveLength(1);
    // The old badge-and-progressbar chrome is gone.
    expect(screen.queryByText("PARTIAL")).toBeNull();
    expect(screen.queryByText("EXPRESSION")).toBeNull();
    expect(screen.queryByRole("progressbar")).toBeNull();
  });
});

describe("TableDetail indexes tab SQL and stats", () => {
  it("preserves quoted key parts in fallback index SQL", async () => {
    const user = userEvent.setup();
    const clipboard = mockClipboardWriteText();
    tableQueries.indexes.data = create(ListTableIndexesResponseSchema, {
      indexes: [
        create(TableIndexSchema, {
          indexName: "orders_mixed_case_idx",
          isValid: true,
          keyParts: ['"Order"'],
          method: "btree",
        }),
      ],
    });

    try {
      render(
        <TableDetail
          databaseId="app"
          initialTab="indexes"
          instanceId="prod"
          schemaName="sales"
          table={undefined}
          tableName="orders"
        />
      );

      await user.click(
        screen.getByRole("button", { name: "Copy CREATE INDEX SQL" })
      );

      expect(clipboard.writeText).toHaveBeenCalledWith(
        'CREATE INDEX orders_mixed_case_idx ON sales.orders USING btree ("Order")'
      );
    } finally {
      clipboard.restore();
    }
  });
});

describe("TableDetail triggers tab", () => {
  it("paginates filtered trigger cards and changes page size", async () => {
    const user = userEvent.setup();
    tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
      triggers: Array.from({ length: 12 }, (_, index) => {
        const suffix = String(index).padStart(2, "0");
        return create(TableTriggerSchema, {
          definition: `CREATE TRIGGER trg_event_${suffix} AFTER UPDATE ON shipping.shipment_event FOR EACH ROW EXECUTE FUNCTION shipping.handle_event_${suffix}()`,
          enabled: true,
          triggerName: `trg_event_${suffix}`,
        });
      }),
    });

    render(
      <TableDetail
        databaseId="warehouse"
        initialTab="triggers"
        instanceId="prod"
        schemaName="shipping"
        table={create(TableSchema, { rowCount: 18_200_000n })}
        tableName="shipment_event"
      />
    );

    expect(screen.getAllByText("trg_event_00").length).toBeGreaterThan(0);
    expect(screen.queryAllByText("trg_event_10")).toHaveLength(0);
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
    expect(
      screen.getByRole("combobox", { name: "Triggers per page" })
    ).toBeTruthy();

    await user.click(screen.getByRole("button", { name: "Next page" }));
    expect(screen.queryAllByText("trg_event_00")).toHaveLength(0);
    expect(screen.getAllByText("trg_event_10").length).toBeGreaterThan(0);
    expect(screen.getByText("Page 2 of 2")).toBeTruthy();

    await user.click(screen.getByRole("button", { name: "State" }));
    await user.click(screen.getByRole("option", { name: "Enabled" }));
    expect(screen.getAllByText("trg_event_00").length).toBeGreaterThan(0);
    expect(screen.queryAllByText("trg_event_10")).toHaveLength(0);
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();

    await user.click(screen.getByRole("button", { name: "Next page" }));
    const search = screen.getByRole("textbox", { name: "Search triggers…" });
    await user.type(search, "00");
    await user.clear(search);
    expect(screen.getAllByText("trg_event_00").length).toBeGreaterThan(0);
    expect(screen.queryAllByText("trg_event_10")).toHaveLength(0);

    await user.click(
      screen.getByRole("combobox", { name: "Triggers per page" })
    );
    await user.click(screen.getByRole("option", { name: "25" }));
    expect(screen.getAllByText("trg_event_00").length).toBeGreaterThan(0);
    expect(screen.getAllByText("trg_event_11").length).toBeGreaterThan(0);
    expect(screen.getByText("Page 1 of 1")).toBeTruthy();
  });

  it("renders trigger cards with executable SQL and copy action", async () => {
    const user = userEvent.setup();
    const writeText = rs.fn(() => Promise.resolve());
    const originalClipboardDescriptor = Object.getOwnPropertyDescriptor(
      navigator,
      "clipboard"
    );
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText },
    });
    tableQueries.triggers.data = create(ListTableTriggersResponseSchema, {
      triggers: [
        create(TableTriggerSchema, {
          definition:
            "CREATE TRIGGER trg_event_enrich BEFORE INSERT ON shipping.shipment_event\n  FOR EACH ROW EXECUTE FUNCTION shipping.enrich_event_location();",
          enabled: true,
          events: ["INSERT"],
          functionName: "shipping.enrich_event_location",
          timing: "BEFORE",
          triggerName: "trg_event_enrich",
        }),
        create(TableTriggerSchema, {
          definition:
            "CREATE TRIGGER trg_shipments_notify AFTER UPDATE OF status ON shipping.shipment_event FOR EACH ROW WHEN ((old.status IS DISTINCT FROM new.status)) EXECUTE FUNCTION shipping.notify_status_change()",
          enabled: false,
          events: ["UPDATE"],
          functionName: "notify_status_change",
          timing: "AFTER",
          triggerName: "trg_shipments_notify",
        }),
      ],
    });
    tableQueries.triggers.refetch.mockClear();

    try {
      render(
        <TableDetail
          databaseId="warehouse"
          initialTab="triggers"
          instanceId="prod"
          schemaName="shipping"
          table={create(TableSchema, { rowCount: 18_200_000n })}
          tableName="shipment_event"
        />
      );

      expect(screen.getAllByText("trg_event_enrich").length).toBeGreaterThan(0);
      expect(screen.getAllByText("BEFORE").length).toBeGreaterThan(0);
      expect(screen.getAllByText("INSERT").length).toBeGreaterThan(0);
      expect(screen.getAllByText("ROW").length).toBeGreaterThan(0);
      expect(
        screen.getByText("→ shipping.enrich_event_location()")
      ).toBeTruthy();
      expect(screen.getByText("disabled")).toBeTruthy();
      expect(
        screen.getByText("WHEN ((old.status IS DISTINCT FROM new.status))")
      ).toBeTruthy();
      const highlightedDefinitions = Array.from(
        screen
          .getByTestId("data-explorer-table-triggers")
          .querySelectorAll(
            'code.language-sql[data-syntax-highlighter="shiki"]'
          )
      );
      expect(highlightedDefinitions).toHaveLength(2);
      expect(highlightedDefinitions[0]?.textContent).toBe(
        "CREATE TRIGGER trg_event_enrich BEFORE INSERT ON shipping.shipment_event\n  FOR EACH ROW EXECUTE FUNCTION shipping.enrich_event_location();"
      );
      expect(
        highlightedDefinitions.every(
          (definition) =>
            definition.querySelectorAll("[data-shiki-token]").length > 5
        )
      ).toBe(true);
      expect(screen.getAllByRole("status")).toHaveLength(2);
      expect(
        screen
          .getAllByRole("status")
          .every((status) => status.textContent === "")
      ).toBe(true);

      await user.click(
        screen.getByRole("button", {
          name: "Copy SQL for trg_event_enrich",
        })
      );

      expect(writeText).toHaveBeenCalledWith(
        "CREATE TRIGGER trg_event_enrich BEFORE INSERT ON shipping.shipment_event\n  FOR EACH ROW EXECUTE FUNCTION shipping.enrich_event_location();"
      );
      expect(
        screen.getAllByRole("status").map((status) => status.textContent)
      ).toContain("SQL for trg_event_enrich copied.");

      writeText.mockRejectedValueOnce(new Error("Clipboard denied"));
      await user.click(
        screen.getByRole("button", {
          name: "Copy SQL for trg_shipments_notify",
        })
      );
      expect(screen.getByText("Copy failed")).toBeTruthy();
      expect(
        screen.getAllByRole("status").map((status) => status.textContent)
      ).toContain("Could not copy SQL for trg_shipments_notify.");

      await user.click(screen.getByRole("button", { name: "Refresh" }));
      expect(tableQueries.triggers.refetch).toHaveBeenCalledTimes(1);
    } finally {
      if (originalClipboardDescriptor) {
        Object.defineProperty(
          navigator,
          "clipboard",
          originalClipboardDescriptor
        );
      } else {
        Reflect.deleteProperty(navigator, "clipboard");
      }
    }
  });
});

describe("TableDetail metadata errors", () => {
  it("renders every failed metadata query with real RPC endpoints", async () => {
    const user = userEvent.setup();
    tableQueries.constraints.error = createMetadataError({
      code: Code.PermissionDenied,
      conditionName: "insufficient_privilege",
      kind: PostgreSqlErrorKind.POSTGRESQL_ERROR_KIND_PERMISSION_DENIED,
      message: "missing constraint access",
      operation: "list_constraints",
      reason: "PERMISSION_DENIED",
      retryGuidance:
        PostgreSqlErrorRetryGuidance.POSTGRESQL_ERROR_RETRY_GUIDANCE_AFTER_CORRECTION,
      sqlstate: "42501",
      sqlstateClass: "42",
    });
    tableQueries.constraints.data = undefined;
    tableQueries.indexes.error = createMetadataError({
      code: Code.Unavailable,
      conditionName: "cannot_connect_now",
      kind: PostgreSqlErrorKind.POSTGRESQL_ERROR_KIND_UNAVAILABLE,
      message: "server unavailable",
      operation: "list_indexes",
      reason: "UNAVAILABLE",
      retryGuidance:
        PostgreSqlErrorRetryGuidance.POSTGRESQL_ERROR_RETRY_GUIDANCE_LATER,
      sqlstate: "57P03",
      sqlstateClass: "57",
    });
    tableQueries.indexes.data = undefined;

    render(
      <TableDetail
        databaseId="app"
        initialTab="columns"
        instanceId="prod"
        schemaName="public"
        table={create(TableSchema, { rowCount: 12n, sizeBytes: 4096n })}
        tableName="customers"
      />
    );

    const detailButtons = screen.getAllByRole("button", {
      name: "Error details",
    });
    expect(detailButtons).toHaveLength(2);

    const endpoints = new Set<string>();
    async function collectEndpoint(index: number): Promise<void> {
      const detailButton = detailButtons[index];
      if (!detailButton) {
        return;
      }

      await user.click(detailButton);
      for (const endpoint of ["ListTableConstraints", "ListTableIndexes"]) {
        if (screen.queryByText(`Endpoint: ${endpoint}`)) {
          endpoints.add(endpoint);
        }
      }
      expect(screen.queryByText("Endpoint: TableDetail/columns")).toBeNull();
      await user.keyboard("{Escape}");

      await collectEndpoint(index + 1);
    }

    await collectEndpoint(0);
    expect(endpoints).toEqual(
      new Set(["ListTableConstraints", "ListTableIndexes"])
    );
  });
});

function renderPoliciesTab(policies: TablePolicy[]) {
  tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
    policies,
  });
  return render(
    <TableDetail
      databaseId="app"
      initialTab="policies"
      instanceId="prod"
      schemaName="billing"
      table={create(TableSchema)}
      tableName="invoices"
    />
  );
}

describe("TableDetail policies tab pagination", () => {
  it("returns to the first policy page when mode filters change", async () => {
    const user = userEvent.setup();
    renderPoliciesTab(
      Array.from({ length: 11 }, (_, index) =>
        create(TablePolicySchema, {
          command: PolicyCommand.SELECT,
          mode: index === 10 ? PolicyMode.RESTRICTIVE : PolicyMode.PERMISSIVE,
          policyName: `invoices_policy_${index + 1}`,
          roles: ["app_reader"],
          usingExpression: `tenant_id = ${index + 1}`,
        })
      )
    );

    await user.click(
      screen.getByRole("button", { name: "Next policies page" })
    );
    await user.click(screen.getByRole("button", { name: "Mode" }));
    await user.click(screen.getByRole("option", { name: "Restrictive" }));
    await user.click(screen.getByRole("option", { name: "Clear filter" }));

    expect(
      screen.getByRole("heading", { name: "invoices_policy_1" })
    ).toBeTruthy();
    expect(
      screen.queryByRole("heading", { name: "invoices_policy_11" })
    ).toBeNull();
    expect(screen.getByText("Page 1 of 2")).toBeTruthy();
  });
});

describe("TableDetail policies tab", () => {
  it("previews UPDATE visibility from USING without folding in WITH CHECK", async () => {
    const user = userEvent.setup();
    tableQueries.policies.data = create(ListTablePoliciesResponseSchema, {
      policies: [
        create(TablePolicySchema, {
          checkExpression: "status <> 'archived'",
          command: PolicyCommand.UPDATE,
          mode: PolicyMode.PERMISSIVE,
          policyName: "invoices_tenant_update",
          roles: ["app_writer"],
          usingExpression: "tenant_id = current_setting('app.tenant')",
        }),
      ],
    });

    const { container } = render(
      <TableDetail
        databaseId="app"
        initialTab="policies"
        instanceId="prod"
        schemaName="billing"
        table={create(TableSchema)}
        tableName="invoices"
      />
    );

    await user.click(screen.getByRole("combobox", { name: "Policy command" }));
    await user.click(screen.getByRole("option", { name: "UPDATE" }));

    const sqlExpressions = Array.from(
      container.querySelectorAll(
        'code.language-sql[data-syntax-highlighter="shiki"]'
      ),
      (code) => code.textContent
    );
    expect(sqlExpressions.at(-1)).toBe(
      "(tenant_id = current_setting('app.tenant'))"
    );
  });
});
