// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file querylane/console/v1alpha1/catalog_sync.proto (package querylane.console.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file querylane/console/v1alpha1/catalog_sync.proto.
 */
export const file_querylane_console_v1alpha1_catalog_sync: GenFile = /*@__PURE__*/
  fileDesc("Ci1xdWVyeWxhbmUvY29uc29sZS92MWFscGhhMS9jYXRhbG9nX3N5bmMucHJvdG8SGnF1ZXJ5bGFuZS5jb25zb2xlLnYxYWxwaGExIscBChNDYXRhbG9nU3luY01ldGFkYXRhEkcKC3N5bmNfc3RhdHVzGAEgASgOMi0ucXVlcnlsYW5lLmNvbnNvbGUudjFhbHBoYTEuQ2F0YWxvZ1N5bmNTdGF0dXNCA+BBAxI3Cg5sYXN0X3N5bmNlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCA+BBAxIVCghpc19zdGFsZRgDIAEoCEID4EEDEhcKCnN5bmNfZXJyb3IYBCABKAlCA+BBAyq+AQoRQ2F0YWxvZ1N5bmNTdGF0dXMSIwofQ0FUQUxPR19TWU5DX1NUQVRVU19VTlNQRUNJRklFRBAAEiQKIENBVEFMT0dfU1lOQ19TVEFUVVNfTkVWRVJfU1lOQ0VEEAESHwobQ0FUQUxPR19TWU5DX1NUQVRVU19TWU5DSU5HEAISHgoaQ0FUQUxPR19TWU5DX1NUQVRVU19TWU5DRUQQAxIdChlDQVRBTE9HX1NZTkNfU1RBVFVTX0VSUk9SEARCmAIKHmNvbS5xdWVyeWxhbmUuY29uc29sZS52MWFscGhhMUIQQ2F0YWxvZ1N5bmNQcm90b1ABWlpnaXRodWIuY29tL3F1ZXJ5bGFuZS9xdWVyeWxhbmUvYmFja2VuZC9wcm90b2dlbi9xdWVyeWxhbmUvY29uc29sZS92MWFscGhhMTtjb25zb2xldjFhbHBoYTGiAgNRQ1iqAhpRdWVyeWxhbmUuQ29uc29sZS5WMWFscGhhMcoCGlF1ZXJ5bGFuZVxDb25zb2xlXFYxYWxwaGEx4gImUXVlcnlsYW5lXENvbnNvbGVcVjFhbHBoYTFcR1BCTWV0YWRhdGHqAhxRdWVyeWxhbmU6OkNvbnNvbGU6OlYxYWxwaGExYgZwcm90bzM", [file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * CatalogSyncMetadata describes whether a list response came from fresh,
 * stale, syncing, or degraded cached catalog data.
 *
 * @generated from message querylane.console.v1alpha1.CatalogSyncMetadata
 */
export type CatalogSyncMetadata = Message<"querylane.console.v1alpha1.CatalogSyncMetadata"> & {
  /**
   * Output-only. Current sync status for the listed catalog scope.
   *
   * @generated from field: querylane.console.v1alpha1.CatalogSyncStatus sync_status = 1;
   */
  syncStatus: CatalogSyncStatus;

  /**
   * Output-only. Last time the listed scope completed a successful sync.
   *
   * @generated from field: google.protobuf.Timestamp last_synced_at = 2;
   */
  lastSyncedAt?: Timestamp;

  /**
   * Output-only. Whether the returned data may be stale.
   *
   * @generated from field: bool is_stale = 3;
   */
  isStale: boolean;

  /**
   * Output-only. Last sync error, when sync_status is ERROR.
   *
   * @generated from field: string sync_error = 4;
   */
  syncError: string;
};

/**
 * Describes the message querylane.console.v1alpha1.CatalogSyncMetadata.
 * Use `create(CatalogSyncMetadataSchema)` to create a new message.
 */
export const CatalogSyncMetadataSchema: GenMessage<CatalogSyncMetadata> = /*@__PURE__*/
  messageDesc(file_querylane_console_v1alpha1_catalog_sync, 0);

/**
 * CatalogSyncStatus describes freshness of a cached catalog scope.
 *
 * @generated from enum querylane.console.v1alpha1.CatalogSyncStatus
 */
export enum CatalogSyncStatus {
  /**
   * Default unspecified value.
   *
   * @generated from enum value: CATALOG_SYNC_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The scope has never completed an initial sync.
   *
   * @generated from enum value: CATALOG_SYNC_STATUS_NEVER_SYNCED = 1;
   */
  NEVER_SYNCED = 1,

  /**
   * A sync is currently running. Cached rows may be stale.
   *
   * @generated from enum value: CATALOG_SYNC_STATUS_SYNCING = 2;
   */
  SYNCING = 2,

  /**
   * The scope is synced and fresh.
   *
   * @generated from enum value: CATALOG_SYNC_STATUS_SYNCED = 3;
   */
  SYNCED = 3,

  /**
   * The last refresh failed. Cached rows may be stale.
   *
   * @generated from enum value: CATALOG_SYNC_STATUS_ERROR = 4;
   */
  ERROR = 4,
}

/**
 * Describes the enum querylane.console.v1alpha1.CatalogSyncStatus.
 */
export const CatalogSyncStatusSchema: GenEnum<CatalogSyncStatus> = /*@__PURE__*/
  enumDesc(file_querylane_console_v1alpha1_catalog_sync, 0);

