// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file querylane/console/v1alpha1/extension.proto (package querylane.console.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import { file_google_api_resource } from "../../../google/api/resource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file querylane/console/v1alpha1/extension.proto.
 */
export const file_querylane_console_v1alpha1_extension: GenFile = /*@__PURE__*/
  fileDesc("CipxdWVyeWxhbmUvY29uc29sZS92MWFscGhhMS9leHRlbnNpb24ucHJvdG8SGnF1ZXJ5bGFuZS5jb25zb2xlLnYxYWxwaGExIrkCCglFeHRlbnNpb24SEQoEbmFtZRgBIAEoCUID4EEIEhkKDGRpc3BsYXlfbmFtZRgCIAEoCUID4EEDEhMKBnNjaGVtYRgDIAEoCUID4EEDEhwKD2RlZmF1bHRfdmVyc2lvbhgEIAEoCUID4EEDEh4KEWluc3RhbGxlZF92ZXJzaW9uGAUgASgJQgPgQQMSFAoHY29tbWVudBgGIAEoCUID4EEDEhYKCWluc3RhbGxlZBgHIAEoCEID4EEDOn3qQXoKH2NvbnNvbGUucXVlcnlsYW5lLmRldi9FeHRlbnNpb24SQGluc3RhbmNlcy97aW5zdGFuY2V9L2RhdGFiYXNlcy97ZGF0YWJhc2V9L2V4dGVuc2lvbnMve2V4dGVuc2lvbn0qCmV4dGVuc2lvbnMyCWV4dGVuc2lvbiKBAgoVTGlzdEV4dGVuc2lvbnNSZXF1ZXN0EoABCgZwYXJlbnQYASABKAlCcOBBAvpBIAoeY29uc29sZS5xdWVyeWxhbmUuZGV2L0RhdGFiYXNlukhHyAEBckIyQF5pbnN0YW5jZXMvW2EtekEtWl0oW2EtekEtWjAtOV8tXSpbYS16QS1aMC05XSk/L2RhdGFiYXNlcy9bXi9dKyQSIAoJcGFnZV9zaXplGAIgASgFQg3gQQG6SAcaBRjoBygAEhcKCnBhZ2VfdG9rZW4YAyABKAlCA+BBARITCgZmaWx0ZXIYBCABKAlCA+BBARIVCghvcmRlcl9ieRgFIAEoCUID4EEBImwKFkxpc3RFeHRlbnNpb25zUmVzcG9uc2USOQoKZXh0ZW5zaW9ucxgBIAMoCzIlLnF1ZXJ5bGFuZS5jb25zb2xlLnYxYWxwaGExLkV4dGVuc2lvbhIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkyjQEKEEV4dGVuc2lvblNlcnZpY2USeQoOTGlzdEV4dGVuc2lvbnMSMS5xdWVyeWxhbmUuY29uc29sZS52MWFscGhhMS5MaXN0RXh0ZW5zaW9uc1JlcXVlc3QaMi5xdWVyeWxhbmUuY29uc29sZS52MWFscGhhMS5MaXN0RXh0ZW5zaW9uc1Jlc3BvbnNlIgBClgIKHmNvbS5xdWVyeWxhbmUuY29uc29sZS52MWFscGhhMUIORXh0ZW5zaW9uUHJvdG9QAVpaZ2l0aHViLmNvbS9xdWVyeWxhbmUvcXVlcnlsYW5lL2JhY2tlbmQvcHJvdG9nZW4vcXVlcnlsYW5lL2NvbnNvbGUvdjFhbHBoYTE7Y29uc29sZXYxYWxwaGExogIDUUNYqgIaUXVlcnlsYW5lLkNvbnNvbGUuVjFhbHBoYTHKAhpRdWVyeWxhbmVcQ29uc29sZVxWMWFscGhhMeICJlF1ZXJ5bGFuZVxDb25zb2xlXFYxYWxwaGExXEdQQk1ldGFkYXRh6gIcUXVlcnlsYW5lOjpDb25zb2xlOjpWMWFscGhhMWIGcHJvdG8z", [file_buf_validate_validate, file_google_api_field_behavior, file_google_api_resource]);

/**
 * A PostgreSQL extension available in a Database.
 *
 * @generated from message querylane.console.v1alpha1.Extension
 */
export type Extension = Message<"querylane.console.v1alpha1.Extension"> & {
  /**
   * Output-only identifier. The unique resource name of the extension.
   * Format: instances/{instance}/databases/{database}/extensions/{extension}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Output-only. The extension name from pg_available_extensions.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Output-only. Schema where the extension is installed. Empty when the
   * extension is available but not installed.
   *
   * @generated from field: string schema = 3;
   */
  schema: string;

  /**
   * Output-only. Default version available on the connected PostgreSQL server.
   *
   * @generated from field: string default_version = 4;
   */
  defaultVersion: string;

  /**
   * Output-only. Installed version in this database. Empty when not installed.
   *
   * @generated from field: string installed_version = 5;
   */
  installedVersion: string;

  /**
   * Output-only. Short description from pg_available_extensions.
   *
   * @generated from field: string comment = 6;
   */
  comment: string;

  /**
   * Output-only. Whether the extension is installed in this database.
   *
   * @generated from field: bool installed = 7;
   */
  installed: boolean;
};

/**
 * Describes the message querylane.console.v1alpha1.Extension.
 * Use `create(ExtensionSchema)` to create a new message.
 */
export const ExtensionSchema: GenMessage<Extension> = /*@__PURE__*/
  messageDesc(file_querylane_console_v1alpha1_extension, 0);

/**
 * @generated from message querylane.console.v1alpha1.ListExtensionsRequest
 */
export type ListExtensionsRequest = Message<"querylane.console.v1alpha1.ListExtensionsRequest"> & {
  /**
   * Required. The parent Database from which to list extensions.
   * Format: instances/{instance}/databases/{database}
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * Optional. The maximum number of extensions to return. Server may return fewer.
   * If unspecified or 0, server will choose a reasonable default (typically 50).
   * Maximum value is 1000.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * Optional. A page token received from a previous `ListExtensions` call.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * Optional. Filter expression (an AIP-160 subset: `=`, `!=`, the `:`
   * case-insensitive substring operator, combined with `AND`). Values are
   * quoted strings or the bare bools true/false. Filterable fields:
   *   - name, schema (string; support the `:` substring operator)
   *   - installed (bool)
   * Examples:
   *   - installed = true
   *   - name:"trgm"
   *   - schema = "public" AND installed = true
   *
   * @generated from field: string filter = 4;
   */
  filter: string;

  /**
   * Optional. Ordering expression following AIP-132 syntax.
   * Supported fields: name, schema, installed
   * Default: "name asc"
   *
   * @generated from field: string order_by = 5;
   */
  orderBy: string;
};

/**
 * Describes the message querylane.console.v1alpha1.ListExtensionsRequest.
 * Use `create(ListExtensionsRequestSchema)` to create a new message.
 */
export const ListExtensionsRequestSchema: GenMessage<ListExtensionsRequest> = /*@__PURE__*/
  messageDesc(file_querylane_console_v1alpha1_extension, 1);

/**
 * @generated from message querylane.console.v1alpha1.ListExtensionsResponse
 */
export type ListExtensionsResponse = Message<"querylane.console.v1alpha1.ListExtensionsResponse"> & {
  /**
   * The list of extensions available in the database.
   *
   * @generated from field: repeated querylane.console.v1alpha1.Extension extensions = 1;
   */
  extensions: Extension[];

  /**
   * A token to retrieve the next page of results.
   * If this field is empty, there are no subsequent pages.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message querylane.console.v1alpha1.ListExtensionsResponse.
 * Use `create(ListExtensionsResponseSchema)` to create a new message.
 */
export const ListExtensionsResponseSchema: GenMessage<ListExtensionsResponse> = /*@__PURE__*/
  messageDesc(file_querylane_console_v1alpha1_extension, 2);

/**
 * Service for viewing PostgreSQL extensions available in a database.
 *
 * @generated from service querylane.console.v1alpha1.ExtensionService
 */
export const ExtensionService: GenService<{
  /**
   * Lists extensions available in a given Database, including whether each
   * extension is installed in that database.
   *
   * @generated from rpc querylane.console.v1alpha1.ExtensionService.ListExtensions
   */
  listExtensions: {
    methodKind: "unary";
    input: typeof ListExtensionsRequestSchema;
    output: typeof ListExtensionsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_querylane_console_v1alpha1_extension, 0);

