// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file querylane/console/v1alpha1/role.proto (package querylane.console.v1alpha1, syntax proto3)
/* eslint-disable */

import { RoleService } from "./role_pb";

/**
 * Lists server-level PostgreSQL roles available in a given Instance.
 *
 * @generated from rpc querylane.console.v1alpha1.RoleService.ListRoles
 */
export const listRoles = RoleService.method.listRoles;

/**
 * Gets the details of a specific Role.
 *
 * @generated from rpc querylane.console.v1alpha1.RoleService.GetRole
 */
export const getRole = RoleService.method.getRole;

/**
 * Lists the object-level privileges granted directly to a Role within a
 * specific Database (its rows in pg_database/pg_namespace/pg_class ACLs).
 *
 * @generated from rpc querylane.console.v1alpha1.RoleService.ListRoleGrants
 */
export const listRoleGrants = RoleService.method.listRoleGrants;

/**
 * Lists the objects a Role owns within a specific Database. Owners hold every
 * privilege on their objects implicitly, so ownership is a primary source of
 * access that ListRoleGrants does not report.
 *
 * @generated from rpc querylane.console.v1alpha1.RoleService.ListRoleOwnedObjects
 */
export const listRoleOwnedObjects = RoleService.method.listRoleOwnedObjects;

/**
 * Lists the default privileges (ALTER DEFAULT PRIVILEGES) that grant access
 * to a Role on objects created later by other roles, within a Database
 * (its rows in pg_default_acl).
 *
 * @generated from rpc querylane.console.v1alpha1.RoleService.ListRoleDefaultPrivileges
 */
export const listRoleDefaultPrivileges = RoleService.method.listRoleDefaultPrivileges;

/**
 * Lists the privileges available to PUBLIC within a Database — privileges
 * every role implicitly holds regardless of its own grants. Returns the
 * effective database-level PUBLIC privileges (CONNECT/TEMPORARY, synthesized
 * from PostgreSQL defaults when datacl is unset) plus every explicit
 * "GRANT ... TO PUBLIC" ACL entry on schemas and objects. Categorical defaults
 * that are not per-object enumerable (EXECUTE on every function, the
 * public-schema USAGE default) are not returned as rows; the UI surfaces those
 * as guidance. Completes the "no direct grants does not mean no access" story.
 *
 * @generated from rpc querylane.console.v1alpha1.RoleService.ListPublicGrants
 */
export const listPublicGrants = RoleService.method.listPublicGrants;
