// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file querylane/console/v1alpha1/runner.proto (package querylane.console.v1alpha1, syntax proto3)
/* eslint-disable */

import { RunnerService } from "./runner_pb";

/**
 * Lists background runner executions: one entry per (runner, target) pair.
 *
 * @generated from rpc querylane.console.v1alpha1.RunnerService.ListRunnerExecutions
 */
export const listRunnerExecutions = RunnerService.method.listRunnerExecutions;
