// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file querylane/console/v1alpha1/sql.proto (package querylane.console.v1alpha1, syntax proto3)
/* eslint-disable */

import { SQLService } from "./sql_pb";

/**
 * Produces an EXPLAIN plan for a single query.
 *
 * @generated from rpc querylane.console.v1alpha1.SQLService.ExplainQuery
 */
export const explainQuery = SQLService.method.explainQuery;

/**
 * Checks a single statement without running it. PostgreSQL parses the
 * statement and resolves every table, column, function and type it
 * references, so the result covers syntax errors and unknown objects alike.
 *
 * @generated from rpc querylane.console.v1alpha1.SQLService.ValidateQuery
 */
export const validateQuery = SQLService.method.validateQuery;
