// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file querylane/console/v1alpha1/table_data.proto (package querylane.console.v1alpha1, syntax proto3)
/* eslint-disable */

import { TableDataService } from "./table_data_pb";

/**
 * Reads a single bounded page of rows. Intended for the interactive grid.
 *
 * @generated from rpc querylane.console.v1alpha1.TableDataService.ReadRows
 */
export const readRows = TableDataService.method.readRows;

/**
 * Reads the full value of a single cell, identified by an opaque token
 * returned in TableCell.full_value_token when a PREVIEW response
 * truncated the value.
 *
 * @generated from rpc querylane.console.v1alpha1.TableDataService.ReadCellValue
 */
export const readCellValue = TableDataService.method.readCellValue;
