// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/console.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConsoleServiceName is the fully-qualified name of the ConsoleService service.
	ConsoleServiceName = "querylane.console.v1alpha1.ConsoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConsoleServiceGetConsoleConfigProcedure is the fully-qualified name of the ConsoleService's
	// GetConsoleConfig RPC.
	ConsoleServiceGetConsoleConfigProcedure = "/querylane.console.v1alpha1.ConsoleService/GetConsoleConfig"
)

// ConsoleServiceClient is a client for the querylane.console.v1alpha1.ConsoleService service.
type ConsoleServiceClient interface {
	// Retrieves static, server-provided configuration and metadata about the
	// console instance, such as build information and capabilities.
	GetConsoleConfig(context.Context, *connect.Request[v1alpha1.GetConsoleConfigRequest]) (*connect.Response[v1alpha1.GetConsoleConfigResponse], error)
}

// NewConsoleServiceClient constructs a client for the querylane.console.v1alpha1.ConsoleService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConsoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConsoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	consoleServiceMethods := v1alpha1.File_querylane_console_v1alpha1_console_proto.Services().ByName("ConsoleService").Methods()
	return &consoleServiceClient{
		getConsoleConfig: connect.NewClient[v1alpha1.GetConsoleConfigRequest, v1alpha1.GetConsoleConfigResponse](
			httpClient,
			baseURL+ConsoleServiceGetConsoleConfigProcedure,
			connect.WithSchema(consoleServiceMethods.ByName("GetConsoleConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// consoleServiceClient implements ConsoleServiceClient.
type consoleServiceClient struct {
	getConsoleConfig *connect.Client[v1alpha1.GetConsoleConfigRequest, v1alpha1.GetConsoleConfigResponse]
}

// GetConsoleConfig calls querylane.console.v1alpha1.ConsoleService.GetConsoleConfig.
func (c *consoleServiceClient) GetConsoleConfig(ctx context.Context, req *connect.Request[v1alpha1.GetConsoleConfigRequest]) (*connect.Response[v1alpha1.GetConsoleConfigResponse], error) {
	return c.getConsoleConfig.CallUnary(ctx, req)
}

// ConsoleServiceHandler is an implementation of the querylane.console.v1alpha1.ConsoleService
// service.
type ConsoleServiceHandler interface {
	// Retrieves static, server-provided configuration and metadata about the
	// console instance, such as build information and capabilities.
	GetConsoleConfig(context.Context, *connect.Request[v1alpha1.GetConsoleConfigRequest]) (*connect.Response[v1alpha1.GetConsoleConfigResponse], error)
}

// NewConsoleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConsoleServiceHandler(svc ConsoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	consoleServiceMethods := v1alpha1.File_querylane_console_v1alpha1_console_proto.Services().ByName("ConsoleService").Methods()
	consoleServiceGetConsoleConfigHandler := connect.NewUnaryHandler(
		ConsoleServiceGetConsoleConfigProcedure,
		svc.GetConsoleConfig,
		connect.WithSchema(consoleServiceMethods.ByName("GetConsoleConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.ConsoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConsoleServiceGetConsoleConfigProcedure:
			consoleServiceGetConsoleConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConsoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConsoleServiceHandler struct{}

func (UnimplementedConsoleServiceHandler) GetConsoleConfig(context.Context, *connect.Request[v1alpha1.GetConsoleConfigRequest]) (*connect.Response[v1alpha1.GetConsoleConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.ConsoleService.GetConsoleConfig is not implemented"))
}
