// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/extension.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExtensionServiceName is the fully-qualified name of the ExtensionService service.
	ExtensionServiceName = "querylane.console.v1alpha1.ExtensionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExtensionServiceListExtensionsProcedure is the fully-qualified name of the ExtensionService's
	// ListExtensions RPC.
	ExtensionServiceListExtensionsProcedure = "/querylane.console.v1alpha1.ExtensionService/ListExtensions"
)

// ExtensionServiceClient is a client for the querylane.console.v1alpha1.ExtensionService service.
type ExtensionServiceClient interface {
	// Lists extensions available in a given Database, including whether each
	// extension is installed in that database.
	ListExtensions(context.Context, *connect.Request[v1alpha1.ListExtensionsRequest]) (*connect.Response[v1alpha1.ListExtensionsResponse], error)
}

// NewExtensionServiceClient constructs a client for the querylane.console.v1alpha1.ExtensionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExtensionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExtensionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	extensionServiceMethods := v1alpha1.File_querylane_console_v1alpha1_extension_proto.Services().ByName("ExtensionService").Methods()
	return &extensionServiceClient{
		listExtensions: connect.NewClient[v1alpha1.ListExtensionsRequest, v1alpha1.ListExtensionsResponse](
			httpClient,
			baseURL+ExtensionServiceListExtensionsProcedure,
			connect.WithSchema(extensionServiceMethods.ByName("ListExtensions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// extensionServiceClient implements ExtensionServiceClient.
type extensionServiceClient struct {
	listExtensions *connect.Client[v1alpha1.ListExtensionsRequest, v1alpha1.ListExtensionsResponse]
}

// ListExtensions calls querylane.console.v1alpha1.ExtensionService.ListExtensions.
func (c *extensionServiceClient) ListExtensions(ctx context.Context, req *connect.Request[v1alpha1.ListExtensionsRequest]) (*connect.Response[v1alpha1.ListExtensionsResponse], error) {
	return c.listExtensions.CallUnary(ctx, req)
}

// ExtensionServiceHandler is an implementation of the querylane.console.v1alpha1.ExtensionService
// service.
type ExtensionServiceHandler interface {
	// Lists extensions available in a given Database, including whether each
	// extension is installed in that database.
	ListExtensions(context.Context, *connect.Request[v1alpha1.ListExtensionsRequest]) (*connect.Response[v1alpha1.ListExtensionsResponse], error)
}

// NewExtensionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExtensionServiceHandler(svc ExtensionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	extensionServiceMethods := v1alpha1.File_querylane_console_v1alpha1_extension_proto.Services().ByName("ExtensionService").Methods()
	extensionServiceListExtensionsHandler := connect.NewUnaryHandler(
		ExtensionServiceListExtensionsProcedure,
		svc.ListExtensions,
		connect.WithSchema(extensionServiceMethods.ByName("ListExtensions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.ExtensionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExtensionServiceListExtensionsProcedure:
			extensionServiceListExtensionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExtensionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExtensionServiceHandler struct{}

func (UnimplementedExtensionServiceHandler) ListExtensions(context.Context, *connect.Request[v1alpha1.ListExtensionsRequest]) (*connect.Response[v1alpha1.ListExtensionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.ExtensionService.ListExtensions is not implemented"))
}
