// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/instance.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InstanceServiceName is the fully-qualified name of the InstanceService service.
	InstanceServiceName = "querylane.console.v1alpha1.InstanceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InstanceServiceListInstancesProcedure is the fully-qualified name of the InstanceService's
	// ListInstances RPC.
	InstanceServiceListInstancesProcedure = "/querylane.console.v1alpha1.InstanceService/ListInstances"
	// InstanceServiceGetInstanceProcedure is the fully-qualified name of the InstanceService's
	// GetInstance RPC.
	InstanceServiceGetInstanceProcedure = "/querylane.console.v1alpha1.InstanceService/GetInstance"
	// InstanceServiceCreateInstanceProcedure is the fully-qualified name of the InstanceService's
	// CreateInstance RPC.
	InstanceServiceCreateInstanceProcedure = "/querylane.console.v1alpha1.InstanceService/CreateInstance"
	// InstanceServiceTestInstanceConnectionProcedure is the fully-qualified name of the
	// InstanceService's TestInstanceConnection RPC.
	InstanceServiceTestInstanceConnectionProcedure = "/querylane.console.v1alpha1.InstanceService/TestInstanceConnection"
	// InstanceServiceUpdateInstanceProcedure is the fully-qualified name of the InstanceService's
	// UpdateInstance RPC.
	InstanceServiceUpdateInstanceProcedure = "/querylane.console.v1alpha1.InstanceService/UpdateInstance"
	// InstanceServiceDeleteInstanceProcedure is the fully-qualified name of the InstanceService's
	// DeleteInstance RPC.
	InstanceServiceDeleteInstanceProcedure = "/querylane.console.v1alpha1.InstanceService/DeleteInstance"
	// InstanceServiceGetInstanceOverviewProcedure is the fully-qualified name of the InstanceService's
	// GetInstanceOverview RPC.
	InstanceServiceGetInstanceOverviewProcedure = "/querylane.console.v1alpha1.InstanceService/GetInstanceOverview"
	// InstanceServiceCheckInstanceHealthProcedure is the fully-qualified name of the InstanceService's
	// CheckInstanceHealth RPC.
	InstanceServiceCheckInstanceHealthProcedure = "/querylane.console.v1alpha1.InstanceService/CheckInstanceHealth"
)

// InstanceServiceClient is a client for the querylane.console.v1alpha1.InstanceService service.
type InstanceServiceClient interface {
	// Lists registered Instances.
	ListInstances(context.Context, *connect.Request[v1alpha1.ListInstancesRequest]) (*connect.Response[v1alpha1.ListInstancesResponse], error)
	// Gets the details of a registered Instance.
	GetInstance(context.Context, *connect.Request[v1alpha1.GetInstanceRequest]) (*connect.Response[v1alpha1.GetInstanceResponse], error)
	// Registers a new external database instance with the platform.
	// The platform will attempt to validate the connection details upon creation.
	CreateInstance(context.Context, *connect.Request[v1alpha1.CreateInstanceRequest]) (*connect.Response[v1alpha1.CreateInstanceResponse], error)
	// Tests PostgreSQL connection details without creating or updating an Instance.
	TestInstanceConnection(context.Context, *connect.Request[v1alpha1.TestInstanceConnectionRequest]) (*connect.Response[v1alpha1.TestInstanceConnectionResponse], error)
	// Updates the connection details for a registered Instance.
	UpdateInstance(context.Context, *connect.Request[v1alpha1.UpdateInstanceRequest]) (*connect.Response[v1alpha1.UpdateInstanceResponse], error)
	// De-registers an Instance, removing its connection record from the platform.
	// This does not affect the external database itself.
	DeleteInstance(context.Context, *connect.Request[v1alpha1.DeleteInstanceRequest]) (*connect.Response[v1alpha1.DeleteInstanceResponse], error)
	// Returns a live health overview for a PostgreSQL instance.
	// Metrics are queried directly from the instance and cached briefly.
	GetInstanceOverview(context.Context, *connect.Request[v1alpha1.GetInstanceOverviewRequest]) (*connect.Response[v1alpha1.GetInstanceOverviewResponse], error)
	// Checks live PostgreSQL health signals that are inexpensive and directly
	// observable from ordinary database views/settings.
	CheckInstanceHealth(context.Context, *connect.Request[v1alpha1.CheckInstanceHealthRequest]) (*connect.Response[v1alpha1.CheckInstanceHealthResponse], error)
}

// NewInstanceServiceClient constructs a client for the querylane.console.v1alpha1.InstanceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInstanceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InstanceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	instanceServiceMethods := v1alpha1.File_querylane_console_v1alpha1_instance_proto.Services().ByName("InstanceService").Methods()
	return &instanceServiceClient{
		listInstances: connect.NewClient[v1alpha1.ListInstancesRequest, v1alpha1.ListInstancesResponse](
			httpClient,
			baseURL+InstanceServiceListInstancesProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("ListInstances")),
			connect.WithClientOptions(opts...),
		),
		getInstance: connect.NewClient[v1alpha1.GetInstanceRequest, v1alpha1.GetInstanceResponse](
			httpClient,
			baseURL+InstanceServiceGetInstanceProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("GetInstance")),
			connect.WithClientOptions(opts...),
		),
		createInstance: connect.NewClient[v1alpha1.CreateInstanceRequest, v1alpha1.CreateInstanceResponse](
			httpClient,
			baseURL+InstanceServiceCreateInstanceProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("CreateInstance")),
			connect.WithClientOptions(opts...),
		),
		testInstanceConnection: connect.NewClient[v1alpha1.TestInstanceConnectionRequest, v1alpha1.TestInstanceConnectionResponse](
			httpClient,
			baseURL+InstanceServiceTestInstanceConnectionProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("TestInstanceConnection")),
			connect.WithClientOptions(opts...),
		),
		updateInstance: connect.NewClient[v1alpha1.UpdateInstanceRequest, v1alpha1.UpdateInstanceResponse](
			httpClient,
			baseURL+InstanceServiceUpdateInstanceProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("UpdateInstance")),
			connect.WithClientOptions(opts...),
		),
		deleteInstance: connect.NewClient[v1alpha1.DeleteInstanceRequest, v1alpha1.DeleteInstanceResponse](
			httpClient,
			baseURL+InstanceServiceDeleteInstanceProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("DeleteInstance")),
			connect.WithClientOptions(opts...),
		),
		getInstanceOverview: connect.NewClient[v1alpha1.GetInstanceOverviewRequest, v1alpha1.GetInstanceOverviewResponse](
			httpClient,
			baseURL+InstanceServiceGetInstanceOverviewProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("GetInstanceOverview")),
			connect.WithClientOptions(opts...),
		),
		checkInstanceHealth: connect.NewClient[v1alpha1.CheckInstanceHealthRequest, v1alpha1.CheckInstanceHealthResponse](
			httpClient,
			baseURL+InstanceServiceCheckInstanceHealthProcedure,
			connect.WithSchema(instanceServiceMethods.ByName("CheckInstanceHealth")),
			connect.WithClientOptions(opts...),
		),
	}
}

// instanceServiceClient implements InstanceServiceClient.
type instanceServiceClient struct {
	listInstances          *connect.Client[v1alpha1.ListInstancesRequest, v1alpha1.ListInstancesResponse]
	getInstance            *connect.Client[v1alpha1.GetInstanceRequest, v1alpha1.GetInstanceResponse]
	createInstance         *connect.Client[v1alpha1.CreateInstanceRequest, v1alpha1.CreateInstanceResponse]
	testInstanceConnection *connect.Client[v1alpha1.TestInstanceConnectionRequest, v1alpha1.TestInstanceConnectionResponse]
	updateInstance         *connect.Client[v1alpha1.UpdateInstanceRequest, v1alpha1.UpdateInstanceResponse]
	deleteInstance         *connect.Client[v1alpha1.DeleteInstanceRequest, v1alpha1.DeleteInstanceResponse]
	getInstanceOverview    *connect.Client[v1alpha1.GetInstanceOverviewRequest, v1alpha1.GetInstanceOverviewResponse]
	checkInstanceHealth    *connect.Client[v1alpha1.CheckInstanceHealthRequest, v1alpha1.CheckInstanceHealthResponse]
}

// ListInstances calls querylane.console.v1alpha1.InstanceService.ListInstances.
func (c *instanceServiceClient) ListInstances(ctx context.Context, req *connect.Request[v1alpha1.ListInstancesRequest]) (*connect.Response[v1alpha1.ListInstancesResponse], error) {
	return c.listInstances.CallUnary(ctx, req)
}

// GetInstance calls querylane.console.v1alpha1.InstanceService.GetInstance.
func (c *instanceServiceClient) GetInstance(ctx context.Context, req *connect.Request[v1alpha1.GetInstanceRequest]) (*connect.Response[v1alpha1.GetInstanceResponse], error) {
	return c.getInstance.CallUnary(ctx, req)
}

// CreateInstance calls querylane.console.v1alpha1.InstanceService.CreateInstance.
func (c *instanceServiceClient) CreateInstance(ctx context.Context, req *connect.Request[v1alpha1.CreateInstanceRequest]) (*connect.Response[v1alpha1.CreateInstanceResponse], error) {
	return c.createInstance.CallUnary(ctx, req)
}

// TestInstanceConnection calls querylane.console.v1alpha1.InstanceService.TestInstanceConnection.
func (c *instanceServiceClient) TestInstanceConnection(ctx context.Context, req *connect.Request[v1alpha1.TestInstanceConnectionRequest]) (*connect.Response[v1alpha1.TestInstanceConnectionResponse], error) {
	return c.testInstanceConnection.CallUnary(ctx, req)
}

// UpdateInstance calls querylane.console.v1alpha1.InstanceService.UpdateInstance.
func (c *instanceServiceClient) UpdateInstance(ctx context.Context, req *connect.Request[v1alpha1.UpdateInstanceRequest]) (*connect.Response[v1alpha1.UpdateInstanceResponse], error) {
	return c.updateInstance.CallUnary(ctx, req)
}

// DeleteInstance calls querylane.console.v1alpha1.InstanceService.DeleteInstance.
func (c *instanceServiceClient) DeleteInstance(ctx context.Context, req *connect.Request[v1alpha1.DeleteInstanceRequest]) (*connect.Response[v1alpha1.DeleteInstanceResponse], error) {
	return c.deleteInstance.CallUnary(ctx, req)
}

// GetInstanceOverview calls querylane.console.v1alpha1.InstanceService.GetInstanceOverview.
func (c *instanceServiceClient) GetInstanceOverview(ctx context.Context, req *connect.Request[v1alpha1.GetInstanceOverviewRequest]) (*connect.Response[v1alpha1.GetInstanceOverviewResponse], error) {
	return c.getInstanceOverview.CallUnary(ctx, req)
}

// CheckInstanceHealth calls querylane.console.v1alpha1.InstanceService.CheckInstanceHealth.
func (c *instanceServiceClient) CheckInstanceHealth(ctx context.Context, req *connect.Request[v1alpha1.CheckInstanceHealthRequest]) (*connect.Response[v1alpha1.CheckInstanceHealthResponse], error) {
	return c.checkInstanceHealth.CallUnary(ctx, req)
}

// InstanceServiceHandler is an implementation of the querylane.console.v1alpha1.InstanceService
// service.
type InstanceServiceHandler interface {
	// Lists registered Instances.
	ListInstances(context.Context, *connect.Request[v1alpha1.ListInstancesRequest]) (*connect.Response[v1alpha1.ListInstancesResponse], error)
	// Gets the details of a registered Instance.
	GetInstance(context.Context, *connect.Request[v1alpha1.GetInstanceRequest]) (*connect.Response[v1alpha1.GetInstanceResponse], error)
	// Registers a new external database instance with the platform.
	// The platform will attempt to validate the connection details upon creation.
	CreateInstance(context.Context, *connect.Request[v1alpha1.CreateInstanceRequest]) (*connect.Response[v1alpha1.CreateInstanceResponse], error)
	// Tests PostgreSQL connection details without creating or updating an Instance.
	TestInstanceConnection(context.Context, *connect.Request[v1alpha1.TestInstanceConnectionRequest]) (*connect.Response[v1alpha1.TestInstanceConnectionResponse], error)
	// Updates the connection details for a registered Instance.
	UpdateInstance(context.Context, *connect.Request[v1alpha1.UpdateInstanceRequest]) (*connect.Response[v1alpha1.UpdateInstanceResponse], error)
	// De-registers an Instance, removing its connection record from the platform.
	// This does not affect the external database itself.
	DeleteInstance(context.Context, *connect.Request[v1alpha1.DeleteInstanceRequest]) (*connect.Response[v1alpha1.DeleteInstanceResponse], error)
	// Returns a live health overview for a PostgreSQL instance.
	// Metrics are queried directly from the instance and cached briefly.
	GetInstanceOverview(context.Context, *connect.Request[v1alpha1.GetInstanceOverviewRequest]) (*connect.Response[v1alpha1.GetInstanceOverviewResponse], error)
	// Checks live PostgreSQL health signals that are inexpensive and directly
	// observable from ordinary database views/settings.
	CheckInstanceHealth(context.Context, *connect.Request[v1alpha1.CheckInstanceHealthRequest]) (*connect.Response[v1alpha1.CheckInstanceHealthResponse], error)
}

// NewInstanceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInstanceServiceHandler(svc InstanceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	instanceServiceMethods := v1alpha1.File_querylane_console_v1alpha1_instance_proto.Services().ByName("InstanceService").Methods()
	instanceServiceListInstancesHandler := connect.NewUnaryHandler(
		InstanceServiceListInstancesProcedure,
		svc.ListInstances,
		connect.WithSchema(instanceServiceMethods.ByName("ListInstances")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceGetInstanceHandler := connect.NewUnaryHandler(
		InstanceServiceGetInstanceProcedure,
		svc.GetInstance,
		connect.WithSchema(instanceServiceMethods.ByName("GetInstance")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceCreateInstanceHandler := connect.NewUnaryHandler(
		InstanceServiceCreateInstanceProcedure,
		svc.CreateInstance,
		connect.WithSchema(instanceServiceMethods.ByName("CreateInstance")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceTestInstanceConnectionHandler := connect.NewUnaryHandler(
		InstanceServiceTestInstanceConnectionProcedure,
		svc.TestInstanceConnection,
		connect.WithSchema(instanceServiceMethods.ByName("TestInstanceConnection")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceUpdateInstanceHandler := connect.NewUnaryHandler(
		InstanceServiceUpdateInstanceProcedure,
		svc.UpdateInstance,
		connect.WithSchema(instanceServiceMethods.ByName("UpdateInstance")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceDeleteInstanceHandler := connect.NewUnaryHandler(
		InstanceServiceDeleteInstanceProcedure,
		svc.DeleteInstance,
		connect.WithSchema(instanceServiceMethods.ByName("DeleteInstance")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceGetInstanceOverviewHandler := connect.NewUnaryHandler(
		InstanceServiceGetInstanceOverviewProcedure,
		svc.GetInstanceOverview,
		connect.WithSchema(instanceServiceMethods.ByName("GetInstanceOverview")),
		connect.WithHandlerOptions(opts...),
	)
	instanceServiceCheckInstanceHealthHandler := connect.NewUnaryHandler(
		InstanceServiceCheckInstanceHealthProcedure,
		svc.CheckInstanceHealth,
		connect.WithSchema(instanceServiceMethods.ByName("CheckInstanceHealth")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.InstanceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InstanceServiceListInstancesProcedure:
			instanceServiceListInstancesHandler.ServeHTTP(w, r)
		case InstanceServiceGetInstanceProcedure:
			instanceServiceGetInstanceHandler.ServeHTTP(w, r)
		case InstanceServiceCreateInstanceProcedure:
			instanceServiceCreateInstanceHandler.ServeHTTP(w, r)
		case InstanceServiceTestInstanceConnectionProcedure:
			instanceServiceTestInstanceConnectionHandler.ServeHTTP(w, r)
		case InstanceServiceUpdateInstanceProcedure:
			instanceServiceUpdateInstanceHandler.ServeHTTP(w, r)
		case InstanceServiceDeleteInstanceProcedure:
			instanceServiceDeleteInstanceHandler.ServeHTTP(w, r)
		case InstanceServiceGetInstanceOverviewProcedure:
			instanceServiceGetInstanceOverviewHandler.ServeHTTP(w, r)
		case InstanceServiceCheckInstanceHealthProcedure:
			instanceServiceCheckInstanceHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInstanceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInstanceServiceHandler struct{}

func (UnimplementedInstanceServiceHandler) ListInstances(context.Context, *connect.Request[v1alpha1.ListInstancesRequest]) (*connect.Response[v1alpha1.ListInstancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.ListInstances is not implemented"))
}

func (UnimplementedInstanceServiceHandler) GetInstance(context.Context, *connect.Request[v1alpha1.GetInstanceRequest]) (*connect.Response[v1alpha1.GetInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.GetInstance is not implemented"))
}

func (UnimplementedInstanceServiceHandler) CreateInstance(context.Context, *connect.Request[v1alpha1.CreateInstanceRequest]) (*connect.Response[v1alpha1.CreateInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.CreateInstance is not implemented"))
}

func (UnimplementedInstanceServiceHandler) TestInstanceConnection(context.Context, *connect.Request[v1alpha1.TestInstanceConnectionRequest]) (*connect.Response[v1alpha1.TestInstanceConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.TestInstanceConnection is not implemented"))
}

func (UnimplementedInstanceServiceHandler) UpdateInstance(context.Context, *connect.Request[v1alpha1.UpdateInstanceRequest]) (*connect.Response[v1alpha1.UpdateInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.UpdateInstance is not implemented"))
}

func (UnimplementedInstanceServiceHandler) DeleteInstance(context.Context, *connect.Request[v1alpha1.DeleteInstanceRequest]) (*connect.Response[v1alpha1.DeleteInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.DeleteInstance is not implemented"))
}

func (UnimplementedInstanceServiceHandler) GetInstanceOverview(context.Context, *connect.Request[v1alpha1.GetInstanceOverviewRequest]) (*connect.Response[v1alpha1.GetInstanceOverviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.GetInstanceOverview is not implemented"))
}

func (UnimplementedInstanceServiceHandler) CheckInstanceHealth(context.Context, *connect.Request[v1alpha1.CheckInstanceHealthRequest]) (*connect.Response[v1alpha1.CheckInstanceHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.InstanceService.CheckInstanceHealth is not implemented"))
}
