// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/metrics.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MetricsServiceName is the fully-qualified name of the MetricsService service.
	MetricsServiceName = "querylane.console.v1alpha1.MetricsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MetricsServiceQueryMetricsProcedure is the fully-qualified name of the MetricsService's
	// QueryMetrics RPC.
	MetricsServiceQueryMetricsProcedure = "/querylane.console.v1alpha1.MetricsService/QueryMetrics"
)

// MetricsServiceClient is a client for the querylane.console.v1alpha1.MetricsService service.
type MetricsServiceClient interface {
	// QueryMetrics returns one time series per requested metric for a target
	// (an instance or a database) over a time window.
	QueryMetrics(context.Context, *connect.Request[v1alpha1.QueryMetricsRequest]) (*connect.Response[v1alpha1.QueryMetricsResponse], error)
}

// NewMetricsServiceClient constructs a client for the querylane.console.v1alpha1.MetricsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMetricsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MetricsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	metricsServiceMethods := v1alpha1.File_querylane_console_v1alpha1_metrics_proto.Services().ByName("MetricsService").Methods()
	return &metricsServiceClient{
		queryMetrics: connect.NewClient[v1alpha1.QueryMetricsRequest, v1alpha1.QueryMetricsResponse](
			httpClient,
			baseURL+MetricsServiceQueryMetricsProcedure,
			connect.WithSchema(metricsServiceMethods.ByName("QueryMetrics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// metricsServiceClient implements MetricsServiceClient.
type metricsServiceClient struct {
	queryMetrics *connect.Client[v1alpha1.QueryMetricsRequest, v1alpha1.QueryMetricsResponse]
}

// QueryMetrics calls querylane.console.v1alpha1.MetricsService.QueryMetrics.
func (c *metricsServiceClient) QueryMetrics(ctx context.Context, req *connect.Request[v1alpha1.QueryMetricsRequest]) (*connect.Response[v1alpha1.QueryMetricsResponse], error) {
	return c.queryMetrics.CallUnary(ctx, req)
}

// MetricsServiceHandler is an implementation of the querylane.console.v1alpha1.MetricsService
// service.
type MetricsServiceHandler interface {
	// QueryMetrics returns one time series per requested metric for a target
	// (an instance or a database) over a time window.
	QueryMetrics(context.Context, *connect.Request[v1alpha1.QueryMetricsRequest]) (*connect.Response[v1alpha1.QueryMetricsResponse], error)
}

// NewMetricsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMetricsServiceHandler(svc MetricsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	metricsServiceMethods := v1alpha1.File_querylane_console_v1alpha1_metrics_proto.Services().ByName("MetricsService").Methods()
	metricsServiceQueryMetricsHandler := connect.NewUnaryHandler(
		MetricsServiceQueryMetricsProcedure,
		svc.QueryMetrics,
		connect.WithSchema(metricsServiceMethods.ByName("QueryMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.MetricsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MetricsServiceQueryMetricsProcedure:
			metricsServiceQueryMetricsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMetricsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMetricsServiceHandler struct{}

func (UnimplementedMetricsServiceHandler) QueryMetrics(context.Context, *connect.Request[v1alpha1.QueryMetricsRequest]) (*connect.Response[v1alpha1.QueryMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.MetricsService.QueryMetrics is not implemented"))
}
