// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/role.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoleServiceName is the fully-qualified name of the RoleService service.
	RoleServiceName = "querylane.console.v1alpha1.RoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoleServiceListRolesProcedure is the fully-qualified name of the RoleService's ListRoles RPC.
	RoleServiceListRolesProcedure = "/querylane.console.v1alpha1.RoleService/ListRoles"
	// RoleServiceGetRoleProcedure is the fully-qualified name of the RoleService's GetRole RPC.
	RoleServiceGetRoleProcedure = "/querylane.console.v1alpha1.RoleService/GetRole"
	// RoleServiceListRoleGrantsProcedure is the fully-qualified name of the RoleService's
	// ListRoleGrants RPC.
	RoleServiceListRoleGrantsProcedure = "/querylane.console.v1alpha1.RoleService/ListRoleGrants"
	// RoleServiceListRoleOwnedObjectsProcedure is the fully-qualified name of the RoleService's
	// ListRoleOwnedObjects RPC.
	RoleServiceListRoleOwnedObjectsProcedure = "/querylane.console.v1alpha1.RoleService/ListRoleOwnedObjects"
	// RoleServiceListRoleDefaultPrivilegesProcedure is the fully-qualified name of the RoleService's
	// ListRoleDefaultPrivileges RPC.
	RoleServiceListRoleDefaultPrivilegesProcedure = "/querylane.console.v1alpha1.RoleService/ListRoleDefaultPrivileges"
	// RoleServiceListPublicGrantsProcedure is the fully-qualified name of the RoleService's
	// ListPublicGrants RPC.
	RoleServiceListPublicGrantsProcedure = "/querylane.console.v1alpha1.RoleService/ListPublicGrants"
)

// RoleServiceClient is a client for the querylane.console.v1alpha1.RoleService service.
type RoleServiceClient interface {
	// Lists server-level PostgreSQL roles available in a given Instance.
	ListRoles(context.Context, *connect.Request[v1alpha1.ListRolesRequest]) (*connect.Response[v1alpha1.ListRolesResponse], error)
	// Gets the details of a specific Role.
	GetRole(context.Context, *connect.Request[v1alpha1.GetRoleRequest]) (*connect.Response[v1alpha1.GetRoleResponse], error)
	// Lists the object-level privileges granted directly to a Role within a
	// specific Database (its rows in pg_database/pg_namespace/pg_class ACLs).
	ListRoleGrants(context.Context, *connect.Request[v1alpha1.ListRoleGrantsRequest]) (*connect.Response[v1alpha1.ListRoleGrantsResponse], error)
	// Lists the objects a Role owns within a specific Database. Owners hold every
	// privilege on their objects implicitly, so ownership is a primary source of
	// access that ListRoleGrants does not report.
	ListRoleOwnedObjects(context.Context, *connect.Request[v1alpha1.ListRoleOwnedObjectsRequest]) (*connect.Response[v1alpha1.ListRoleOwnedObjectsResponse], error)
	// Lists the default privileges (ALTER DEFAULT PRIVILEGES) that grant access
	// to a Role on objects created later by other roles, within a Database
	// (its rows in pg_default_acl).
	ListRoleDefaultPrivileges(context.Context, *connect.Request[v1alpha1.ListRoleDefaultPrivilegesRequest]) (*connect.Response[v1alpha1.ListRoleDefaultPrivilegesResponse], error)
	// Lists the privileges available to PUBLIC within a Database — privileges
	// every role implicitly holds regardless of its own grants. Returns the
	// effective database-level PUBLIC privileges (CONNECT/TEMPORARY, synthesized
	// from PostgreSQL defaults when datacl is unset) plus every explicit
	// "GRANT ... TO PUBLIC" ACL entry on schemas and objects. Categorical defaults
	// that are not per-object enumerable (EXECUTE on every function, the
	// public-schema USAGE default) are not returned as rows; the UI surfaces those
	// as guidance. Completes the "no direct grants does not mean no access" story.
	ListPublicGrants(context.Context, *connect.Request[v1alpha1.ListPublicGrantsRequest]) (*connect.Response[v1alpha1.ListPublicGrantsResponse], error)
}

// NewRoleServiceClient constructs a client for the querylane.console.v1alpha1.RoleService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roleServiceMethods := v1alpha1.File_querylane_console_v1alpha1_role_proto.Services().ByName("RoleService").Methods()
	return &roleServiceClient{
		listRoles: connect.NewClient[v1alpha1.ListRolesRequest, v1alpha1.ListRolesResponse](
			httpClient,
			baseURL+RoleServiceListRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		getRole: connect.NewClient[v1alpha1.GetRoleRequest, v1alpha1.GetRoleResponse](
			httpClient,
			baseURL+RoleServiceGetRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("GetRole")),
			connect.WithClientOptions(opts...),
		),
		listRoleGrants: connect.NewClient[v1alpha1.ListRoleGrantsRequest, v1alpha1.ListRoleGrantsResponse](
			httpClient,
			baseURL+RoleServiceListRoleGrantsProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoleGrants")),
			connect.WithClientOptions(opts...),
		),
		listRoleOwnedObjects: connect.NewClient[v1alpha1.ListRoleOwnedObjectsRequest, v1alpha1.ListRoleOwnedObjectsResponse](
			httpClient,
			baseURL+RoleServiceListRoleOwnedObjectsProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoleOwnedObjects")),
			connect.WithClientOptions(opts...),
		),
		listRoleDefaultPrivileges: connect.NewClient[v1alpha1.ListRoleDefaultPrivilegesRequest, v1alpha1.ListRoleDefaultPrivilegesResponse](
			httpClient,
			baseURL+RoleServiceListRoleDefaultPrivilegesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoleDefaultPrivileges")),
			connect.WithClientOptions(opts...),
		),
		listPublicGrants: connect.NewClient[v1alpha1.ListPublicGrantsRequest, v1alpha1.ListPublicGrantsResponse](
			httpClient,
			baseURL+RoleServiceListPublicGrantsProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListPublicGrants")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roleServiceClient implements RoleServiceClient.
type roleServiceClient struct {
	listRoles                 *connect.Client[v1alpha1.ListRolesRequest, v1alpha1.ListRolesResponse]
	getRole                   *connect.Client[v1alpha1.GetRoleRequest, v1alpha1.GetRoleResponse]
	listRoleGrants            *connect.Client[v1alpha1.ListRoleGrantsRequest, v1alpha1.ListRoleGrantsResponse]
	listRoleOwnedObjects      *connect.Client[v1alpha1.ListRoleOwnedObjectsRequest, v1alpha1.ListRoleOwnedObjectsResponse]
	listRoleDefaultPrivileges *connect.Client[v1alpha1.ListRoleDefaultPrivilegesRequest, v1alpha1.ListRoleDefaultPrivilegesResponse]
	listPublicGrants          *connect.Client[v1alpha1.ListPublicGrantsRequest, v1alpha1.ListPublicGrantsResponse]
}

// ListRoles calls querylane.console.v1alpha1.RoleService.ListRoles.
func (c *roleServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1alpha1.ListRolesRequest]) (*connect.Response[v1alpha1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// GetRole calls querylane.console.v1alpha1.RoleService.GetRole.
func (c *roleServiceClient) GetRole(ctx context.Context, req *connect.Request[v1alpha1.GetRoleRequest]) (*connect.Response[v1alpha1.GetRoleResponse], error) {
	return c.getRole.CallUnary(ctx, req)
}

// ListRoleGrants calls querylane.console.v1alpha1.RoleService.ListRoleGrants.
func (c *roleServiceClient) ListRoleGrants(ctx context.Context, req *connect.Request[v1alpha1.ListRoleGrantsRequest]) (*connect.Response[v1alpha1.ListRoleGrantsResponse], error) {
	return c.listRoleGrants.CallUnary(ctx, req)
}

// ListRoleOwnedObjects calls querylane.console.v1alpha1.RoleService.ListRoleOwnedObjects.
func (c *roleServiceClient) ListRoleOwnedObjects(ctx context.Context, req *connect.Request[v1alpha1.ListRoleOwnedObjectsRequest]) (*connect.Response[v1alpha1.ListRoleOwnedObjectsResponse], error) {
	return c.listRoleOwnedObjects.CallUnary(ctx, req)
}

// ListRoleDefaultPrivileges calls querylane.console.v1alpha1.RoleService.ListRoleDefaultPrivileges.
func (c *roleServiceClient) ListRoleDefaultPrivileges(ctx context.Context, req *connect.Request[v1alpha1.ListRoleDefaultPrivilegesRequest]) (*connect.Response[v1alpha1.ListRoleDefaultPrivilegesResponse], error) {
	return c.listRoleDefaultPrivileges.CallUnary(ctx, req)
}

// ListPublicGrants calls querylane.console.v1alpha1.RoleService.ListPublicGrants.
func (c *roleServiceClient) ListPublicGrants(ctx context.Context, req *connect.Request[v1alpha1.ListPublicGrantsRequest]) (*connect.Response[v1alpha1.ListPublicGrantsResponse], error) {
	return c.listPublicGrants.CallUnary(ctx, req)
}

// RoleServiceHandler is an implementation of the querylane.console.v1alpha1.RoleService service.
type RoleServiceHandler interface {
	// Lists server-level PostgreSQL roles available in a given Instance.
	ListRoles(context.Context, *connect.Request[v1alpha1.ListRolesRequest]) (*connect.Response[v1alpha1.ListRolesResponse], error)
	// Gets the details of a specific Role.
	GetRole(context.Context, *connect.Request[v1alpha1.GetRoleRequest]) (*connect.Response[v1alpha1.GetRoleResponse], error)
	// Lists the object-level privileges granted directly to a Role within a
	// specific Database (its rows in pg_database/pg_namespace/pg_class ACLs).
	ListRoleGrants(context.Context, *connect.Request[v1alpha1.ListRoleGrantsRequest]) (*connect.Response[v1alpha1.ListRoleGrantsResponse], error)
	// Lists the objects a Role owns within a specific Database. Owners hold every
	// privilege on their objects implicitly, so ownership is a primary source of
	// access that ListRoleGrants does not report.
	ListRoleOwnedObjects(context.Context, *connect.Request[v1alpha1.ListRoleOwnedObjectsRequest]) (*connect.Response[v1alpha1.ListRoleOwnedObjectsResponse], error)
	// Lists the default privileges (ALTER DEFAULT PRIVILEGES) that grant access
	// to a Role on objects created later by other roles, within a Database
	// (its rows in pg_default_acl).
	ListRoleDefaultPrivileges(context.Context, *connect.Request[v1alpha1.ListRoleDefaultPrivilegesRequest]) (*connect.Response[v1alpha1.ListRoleDefaultPrivilegesResponse], error)
	// Lists the privileges available to PUBLIC within a Database — privileges
	// every role implicitly holds regardless of its own grants. Returns the
	// effective database-level PUBLIC privileges (CONNECT/TEMPORARY, synthesized
	// from PostgreSQL defaults when datacl is unset) plus every explicit
	// "GRANT ... TO PUBLIC" ACL entry on schemas and objects. Categorical defaults
	// that are not per-object enumerable (EXECUTE on every function, the
	// public-schema USAGE default) are not returned as rows; the UI surfaces those
	// as guidance. Completes the "no direct grants does not mean no access" story.
	ListPublicGrants(context.Context, *connect.Request[v1alpha1.ListPublicGrantsRequest]) (*connect.Response[v1alpha1.ListPublicGrantsResponse], error)
}

// NewRoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoleServiceHandler(svc RoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roleServiceMethods := v1alpha1.File_querylane_console_v1alpha1_role_proto.Services().ByName("RoleService").Methods()
	roleServiceListRolesHandler := connect.NewUnaryHandler(
		RoleServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceGetRoleHandler := connect.NewUnaryHandler(
		RoleServiceGetRoleProcedure,
		svc.GetRole,
		connect.WithSchema(roleServiceMethods.ByName("GetRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceListRoleGrantsHandler := connect.NewUnaryHandler(
		RoleServiceListRoleGrantsProcedure,
		svc.ListRoleGrants,
		connect.WithSchema(roleServiceMethods.ByName("ListRoleGrants")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceListRoleOwnedObjectsHandler := connect.NewUnaryHandler(
		RoleServiceListRoleOwnedObjectsProcedure,
		svc.ListRoleOwnedObjects,
		connect.WithSchema(roleServiceMethods.ByName("ListRoleOwnedObjects")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceListRoleDefaultPrivilegesHandler := connect.NewUnaryHandler(
		RoleServiceListRoleDefaultPrivilegesProcedure,
		svc.ListRoleDefaultPrivileges,
		connect.WithSchema(roleServiceMethods.ByName("ListRoleDefaultPrivileges")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceListPublicGrantsHandler := connect.NewUnaryHandler(
		RoleServiceListPublicGrantsProcedure,
		svc.ListPublicGrants,
		connect.WithSchema(roleServiceMethods.ByName("ListPublicGrants")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.RoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoleServiceListRolesProcedure:
			roleServiceListRolesHandler.ServeHTTP(w, r)
		case RoleServiceGetRoleProcedure:
			roleServiceGetRoleHandler.ServeHTTP(w, r)
		case RoleServiceListRoleGrantsProcedure:
			roleServiceListRoleGrantsHandler.ServeHTTP(w, r)
		case RoleServiceListRoleOwnedObjectsProcedure:
			roleServiceListRoleOwnedObjectsHandler.ServeHTTP(w, r)
		case RoleServiceListRoleDefaultPrivilegesProcedure:
			roleServiceListRoleDefaultPrivilegesHandler.ServeHTTP(w, r)
		case RoleServiceListPublicGrantsProcedure:
			roleServiceListPublicGrantsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoleServiceHandler struct{}

func (UnimplementedRoleServiceHandler) ListRoles(context.Context, *connect.Request[v1alpha1.ListRolesRequest]) (*connect.Response[v1alpha1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.RoleService.ListRoles is not implemented"))
}

func (UnimplementedRoleServiceHandler) GetRole(context.Context, *connect.Request[v1alpha1.GetRoleRequest]) (*connect.Response[v1alpha1.GetRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.RoleService.GetRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) ListRoleGrants(context.Context, *connect.Request[v1alpha1.ListRoleGrantsRequest]) (*connect.Response[v1alpha1.ListRoleGrantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.RoleService.ListRoleGrants is not implemented"))
}

func (UnimplementedRoleServiceHandler) ListRoleOwnedObjects(context.Context, *connect.Request[v1alpha1.ListRoleOwnedObjectsRequest]) (*connect.Response[v1alpha1.ListRoleOwnedObjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.RoleService.ListRoleOwnedObjects is not implemented"))
}

func (UnimplementedRoleServiceHandler) ListRoleDefaultPrivileges(context.Context, *connect.Request[v1alpha1.ListRoleDefaultPrivilegesRequest]) (*connect.Response[v1alpha1.ListRoleDefaultPrivilegesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.RoleService.ListRoleDefaultPrivileges is not implemented"))
}

func (UnimplementedRoleServiceHandler) ListPublicGrants(context.Context, *connect.Request[v1alpha1.ListPublicGrantsRequest]) (*connect.Response[v1alpha1.ListPublicGrantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.RoleService.ListPublicGrants is not implemented"))
}
