// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/schema.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SchemaServiceName is the fully-qualified name of the SchemaService service.
	SchemaServiceName = "querylane.console.v1alpha1.SchemaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SchemaServiceListSchemasProcedure is the fully-qualified name of the SchemaService's ListSchemas
	// RPC.
	SchemaServiceListSchemasProcedure = "/querylane.console.v1alpha1.SchemaService/ListSchemas"
	// SchemaServiceGetSchemaProcedure is the fully-qualified name of the SchemaService's GetSchema RPC.
	SchemaServiceGetSchemaProcedure = "/querylane.console.v1alpha1.SchemaService/GetSchema"
)

// SchemaServiceClient is a client for the querylane.console.v1alpha1.SchemaService service.
type SchemaServiceClient interface {
	// Lists schemas available in a given Database.
	ListSchemas(context.Context, *connect.Request[v1alpha1.ListSchemasRequest]) (*connect.Response[v1alpha1.ListSchemasResponse], error)
	// Gets the details of a specific Schema.
	GetSchema(context.Context, *connect.Request[v1alpha1.GetSchemaRequest]) (*connect.Response[v1alpha1.GetSchemaResponse], error)
}

// NewSchemaServiceClient constructs a client for the querylane.console.v1alpha1.SchemaService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSchemaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SchemaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	schemaServiceMethods := v1alpha1.File_querylane_console_v1alpha1_schema_proto.Services().ByName("SchemaService").Methods()
	return &schemaServiceClient{
		listSchemas: connect.NewClient[v1alpha1.ListSchemasRequest, v1alpha1.ListSchemasResponse](
			httpClient,
			baseURL+SchemaServiceListSchemasProcedure,
			connect.WithSchema(schemaServiceMethods.ByName("ListSchemas")),
			connect.WithClientOptions(opts...),
		),
		getSchema: connect.NewClient[v1alpha1.GetSchemaRequest, v1alpha1.GetSchemaResponse](
			httpClient,
			baseURL+SchemaServiceGetSchemaProcedure,
			connect.WithSchema(schemaServiceMethods.ByName("GetSchema")),
			connect.WithClientOptions(opts...),
		),
	}
}

// schemaServiceClient implements SchemaServiceClient.
type schemaServiceClient struct {
	listSchemas *connect.Client[v1alpha1.ListSchemasRequest, v1alpha1.ListSchemasResponse]
	getSchema   *connect.Client[v1alpha1.GetSchemaRequest, v1alpha1.GetSchemaResponse]
}

// ListSchemas calls querylane.console.v1alpha1.SchemaService.ListSchemas.
func (c *schemaServiceClient) ListSchemas(ctx context.Context, req *connect.Request[v1alpha1.ListSchemasRequest]) (*connect.Response[v1alpha1.ListSchemasResponse], error) {
	return c.listSchemas.CallUnary(ctx, req)
}

// GetSchema calls querylane.console.v1alpha1.SchemaService.GetSchema.
func (c *schemaServiceClient) GetSchema(ctx context.Context, req *connect.Request[v1alpha1.GetSchemaRequest]) (*connect.Response[v1alpha1.GetSchemaResponse], error) {
	return c.getSchema.CallUnary(ctx, req)
}

// SchemaServiceHandler is an implementation of the querylane.console.v1alpha1.SchemaService
// service.
type SchemaServiceHandler interface {
	// Lists schemas available in a given Database.
	ListSchemas(context.Context, *connect.Request[v1alpha1.ListSchemasRequest]) (*connect.Response[v1alpha1.ListSchemasResponse], error)
	// Gets the details of a specific Schema.
	GetSchema(context.Context, *connect.Request[v1alpha1.GetSchemaRequest]) (*connect.Response[v1alpha1.GetSchemaResponse], error)
}

// NewSchemaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSchemaServiceHandler(svc SchemaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	schemaServiceMethods := v1alpha1.File_querylane_console_v1alpha1_schema_proto.Services().ByName("SchemaService").Methods()
	schemaServiceListSchemasHandler := connect.NewUnaryHandler(
		SchemaServiceListSchemasProcedure,
		svc.ListSchemas,
		connect.WithSchema(schemaServiceMethods.ByName("ListSchemas")),
		connect.WithHandlerOptions(opts...),
	)
	schemaServiceGetSchemaHandler := connect.NewUnaryHandler(
		SchemaServiceGetSchemaProcedure,
		svc.GetSchema,
		connect.WithSchema(schemaServiceMethods.ByName("GetSchema")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.SchemaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SchemaServiceListSchemasProcedure:
			schemaServiceListSchemasHandler.ServeHTTP(w, r)
		case SchemaServiceGetSchemaProcedure:
			schemaServiceGetSchemaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSchemaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSchemaServiceHandler struct{}

func (UnimplementedSchemaServiceHandler) ListSchemas(context.Context, *connect.Request[v1alpha1.ListSchemasRequest]) (*connect.Response[v1alpha1.ListSchemasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.SchemaService.ListSchemas is not implemented"))
}

func (UnimplementedSchemaServiceHandler) GetSchema(context.Context, *connect.Request[v1alpha1.GetSchemaRequest]) (*connect.Response[v1alpha1.GetSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.SchemaService.GetSchema is not implemented"))
}
