// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/sql.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SQLServiceName is the fully-qualified name of the SQLService service.
	SQLServiceName = "querylane.console.v1alpha1.SQLService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SQLServiceExecuteQueryProcedure is the fully-qualified name of the SQLService's ExecuteQuery RPC.
	SQLServiceExecuteQueryProcedure = "/querylane.console.v1alpha1.SQLService/ExecuteQuery"
	// SQLServiceExplainQueryProcedure is the fully-qualified name of the SQLService's ExplainQuery RPC.
	SQLServiceExplainQueryProcedure = "/querylane.console.v1alpha1.SQLService/ExplainQuery"
)

// SQLServiceClient is a client for the querylane.console.v1alpha1.SQLService service.
type SQLServiceClient interface {
	// Executes a single read-only SQL query and streams results in batches.
	ExecuteQuery(context.Context, *connect.Request[v1alpha1.ExecuteQueryRequest]) (*connect.ServerStreamForClient[v1alpha1.ExecuteQueryResponse], error)
	// Produces an EXPLAIN plan for a single query.
	ExplainQuery(context.Context, *connect.Request[v1alpha1.ExplainQueryRequest]) (*connect.Response[v1alpha1.ExplainQueryResponse], error)
}

// NewSQLServiceClient constructs a client for the querylane.console.v1alpha1.SQLService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSQLServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SQLServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sQLServiceMethods := v1alpha1.File_querylane_console_v1alpha1_sql_proto.Services().ByName("SQLService").Methods()
	return &sQLServiceClient{
		executeQuery: connect.NewClient[v1alpha1.ExecuteQueryRequest, v1alpha1.ExecuteQueryResponse](
			httpClient,
			baseURL+SQLServiceExecuteQueryProcedure,
			connect.WithSchema(sQLServiceMethods.ByName("ExecuteQuery")),
			connect.WithClientOptions(opts...),
		),
		explainQuery: connect.NewClient[v1alpha1.ExplainQueryRequest, v1alpha1.ExplainQueryResponse](
			httpClient,
			baseURL+SQLServiceExplainQueryProcedure,
			connect.WithSchema(sQLServiceMethods.ByName("ExplainQuery")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sQLServiceClient implements SQLServiceClient.
type sQLServiceClient struct {
	executeQuery *connect.Client[v1alpha1.ExecuteQueryRequest, v1alpha1.ExecuteQueryResponse]
	explainQuery *connect.Client[v1alpha1.ExplainQueryRequest, v1alpha1.ExplainQueryResponse]
}

// ExecuteQuery calls querylane.console.v1alpha1.SQLService.ExecuteQuery.
func (c *sQLServiceClient) ExecuteQuery(ctx context.Context, req *connect.Request[v1alpha1.ExecuteQueryRequest]) (*connect.ServerStreamForClient[v1alpha1.ExecuteQueryResponse], error) {
	return c.executeQuery.CallServerStream(ctx, req)
}

// ExplainQuery calls querylane.console.v1alpha1.SQLService.ExplainQuery.
func (c *sQLServiceClient) ExplainQuery(ctx context.Context, req *connect.Request[v1alpha1.ExplainQueryRequest]) (*connect.Response[v1alpha1.ExplainQueryResponse], error) {
	return c.explainQuery.CallUnary(ctx, req)
}

// SQLServiceHandler is an implementation of the querylane.console.v1alpha1.SQLService service.
type SQLServiceHandler interface {
	// Executes a single read-only SQL query and streams results in batches.
	ExecuteQuery(context.Context, *connect.Request[v1alpha1.ExecuteQueryRequest], *connect.ServerStream[v1alpha1.ExecuteQueryResponse]) error
	// Produces an EXPLAIN plan for a single query.
	ExplainQuery(context.Context, *connect.Request[v1alpha1.ExplainQueryRequest]) (*connect.Response[v1alpha1.ExplainQueryResponse], error)
}

// NewSQLServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSQLServiceHandler(svc SQLServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sQLServiceMethods := v1alpha1.File_querylane_console_v1alpha1_sql_proto.Services().ByName("SQLService").Methods()
	sQLServiceExecuteQueryHandler := connect.NewServerStreamHandler(
		SQLServiceExecuteQueryProcedure,
		svc.ExecuteQuery,
		connect.WithSchema(sQLServiceMethods.ByName("ExecuteQuery")),
		connect.WithHandlerOptions(opts...),
	)
	sQLServiceExplainQueryHandler := connect.NewUnaryHandler(
		SQLServiceExplainQueryProcedure,
		svc.ExplainQuery,
		connect.WithSchema(sQLServiceMethods.ByName("ExplainQuery")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.SQLService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SQLServiceExecuteQueryProcedure:
			sQLServiceExecuteQueryHandler.ServeHTTP(w, r)
		case SQLServiceExplainQueryProcedure:
			sQLServiceExplainQueryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSQLServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSQLServiceHandler struct{}

func (UnimplementedSQLServiceHandler) ExecuteQuery(context.Context, *connect.Request[v1alpha1.ExecuteQueryRequest], *connect.ServerStream[v1alpha1.ExecuteQueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.SQLService.ExecuteQuery is not implemented"))
}

func (UnimplementedSQLServiceHandler) ExplainQuery(context.Context, *connect.Request[v1alpha1.ExplainQueryRequest]) (*connect.Response[v1alpha1.ExplainQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.SQLService.ExplainQuery is not implemented"))
}
