// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/table.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TableServiceName is the fully-qualified name of the TableService service.
	TableServiceName = "querylane.console.v1alpha1.TableService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TableServiceListTablesProcedure is the fully-qualified name of the TableService's ListTables RPC.
	TableServiceListTablesProcedure = "/querylane.console.v1alpha1.TableService/ListTables"
	// TableServiceGetTableProcedure is the fully-qualified name of the TableService's GetTable RPC.
	TableServiceGetTableProcedure = "/querylane.console.v1alpha1.TableService/GetTable"
	// TableServiceGetTablePartitionMetadataProcedure is the fully-qualified name of the TableService's
	// GetTablePartitionMetadata RPC.
	TableServiceGetTablePartitionMetadataProcedure = "/querylane.console.v1alpha1.TableService/GetTablePartitionMetadata"
	// TableServiceListTableColumnsProcedure is the fully-qualified name of the TableService's
	// ListTableColumns RPC.
	TableServiceListTableColumnsProcedure = "/querylane.console.v1alpha1.TableService/ListTableColumns"
	// TableServiceListTableConstraintsProcedure is the fully-qualified name of the TableService's
	// ListTableConstraints RPC.
	TableServiceListTableConstraintsProcedure = "/querylane.console.v1alpha1.TableService/ListTableConstraints"
	// TableServiceListTableIndexesProcedure is the fully-qualified name of the TableService's
	// ListTableIndexes RPC.
	TableServiceListTableIndexesProcedure = "/querylane.console.v1alpha1.TableService/ListTableIndexes"
	// TableServiceListTablePoliciesProcedure is the fully-qualified name of the TableService's
	// ListTablePolicies RPC.
	TableServiceListTablePoliciesProcedure = "/querylane.console.v1alpha1.TableService/ListTablePolicies"
	// TableServiceListTableTriggersProcedure is the fully-qualified name of the TableService's
	// ListTableTriggers RPC.
	TableServiceListTableTriggersProcedure = "/querylane.console.v1alpha1.TableService/ListTableTriggers"
)

// TableServiceClient is a client for the querylane.console.v1alpha1.TableService service.
type TableServiceClient interface {
	// Lists tables available in a given Schema.
	ListTables(context.Context, *connect.Request[v1alpha1.ListTablesRequest]) (*connect.Response[v1alpha1.ListTablesResponse], error)
	// Gets the details of a specific Table.
	// Returns table information without column details.
	GetTable(context.Context, *connect.Request[v1alpha1.GetTableRequest]) (*connect.Response[v1alpha1.GetTableResponse], error)
	// Gets PostgreSQL partition metadata for a specific Table.
	GetTablePartitionMetadata(context.Context, *connect.Request[v1alpha1.GetTablePartitionMetadataRequest]) (*connect.Response[v1alpha1.GetTablePartitionMetadataResponse], error)
	// Lists columns for a specific Table.
	// Returns detailed column information including types, constraints, and metadata.
	ListTableColumns(context.Context, *connect.Request[v1alpha1.ListTableColumnsRequest]) (*connect.Response[v1alpha1.ListTableColumnsResponse], error)
	// Lists constraints (primary key, unique, foreign key, check, exclusion) for a table.
	ListTableConstraints(context.Context, *connect.Request[v1alpha1.ListTableConstraintsRequest]) (*connect.Response[v1alpha1.ListTableConstraintsResponse], error)
	// Lists indexes for a table.
	ListTableIndexes(context.Context, *connect.Request[v1alpha1.ListTableIndexesRequest]) (*connect.Response[v1alpha1.ListTableIndexesResponse], error)
	// Lists row-level security policies for a table.
	ListTablePolicies(context.Context, *connect.Request[v1alpha1.ListTablePoliciesRequest]) (*connect.Response[v1alpha1.ListTablePoliciesResponse], error)
	// Lists triggers for a table.
	ListTableTriggers(context.Context, *connect.Request[v1alpha1.ListTableTriggersRequest]) (*connect.Response[v1alpha1.ListTableTriggersResponse], error)
}

// NewTableServiceClient constructs a client for the querylane.console.v1alpha1.TableService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTableServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TableServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tableServiceMethods := v1alpha1.File_querylane_console_v1alpha1_table_proto.Services().ByName("TableService").Methods()
	return &tableServiceClient{
		listTables: connect.NewClient[v1alpha1.ListTablesRequest, v1alpha1.ListTablesResponse](
			httpClient,
			baseURL+TableServiceListTablesProcedure,
			connect.WithSchema(tableServiceMethods.ByName("ListTables")),
			connect.WithClientOptions(opts...),
		),
		getTable: connect.NewClient[v1alpha1.GetTableRequest, v1alpha1.GetTableResponse](
			httpClient,
			baseURL+TableServiceGetTableProcedure,
			connect.WithSchema(tableServiceMethods.ByName("GetTable")),
			connect.WithClientOptions(opts...),
		),
		getTablePartitionMetadata: connect.NewClient[v1alpha1.GetTablePartitionMetadataRequest, v1alpha1.GetTablePartitionMetadataResponse](
			httpClient,
			baseURL+TableServiceGetTablePartitionMetadataProcedure,
			connect.WithSchema(tableServiceMethods.ByName("GetTablePartitionMetadata")),
			connect.WithClientOptions(opts...),
		),
		listTableColumns: connect.NewClient[v1alpha1.ListTableColumnsRequest, v1alpha1.ListTableColumnsResponse](
			httpClient,
			baseURL+TableServiceListTableColumnsProcedure,
			connect.WithSchema(tableServiceMethods.ByName("ListTableColumns")),
			connect.WithClientOptions(opts...),
		),
		listTableConstraints: connect.NewClient[v1alpha1.ListTableConstraintsRequest, v1alpha1.ListTableConstraintsResponse](
			httpClient,
			baseURL+TableServiceListTableConstraintsProcedure,
			connect.WithSchema(tableServiceMethods.ByName("ListTableConstraints")),
			connect.WithClientOptions(opts...),
		),
		listTableIndexes: connect.NewClient[v1alpha1.ListTableIndexesRequest, v1alpha1.ListTableIndexesResponse](
			httpClient,
			baseURL+TableServiceListTableIndexesProcedure,
			connect.WithSchema(tableServiceMethods.ByName("ListTableIndexes")),
			connect.WithClientOptions(opts...),
		),
		listTablePolicies: connect.NewClient[v1alpha1.ListTablePoliciesRequest, v1alpha1.ListTablePoliciesResponse](
			httpClient,
			baseURL+TableServiceListTablePoliciesProcedure,
			connect.WithSchema(tableServiceMethods.ByName("ListTablePolicies")),
			connect.WithClientOptions(opts...),
		),
		listTableTriggers: connect.NewClient[v1alpha1.ListTableTriggersRequest, v1alpha1.ListTableTriggersResponse](
			httpClient,
			baseURL+TableServiceListTableTriggersProcedure,
			connect.WithSchema(tableServiceMethods.ByName("ListTableTriggers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tableServiceClient implements TableServiceClient.
type tableServiceClient struct {
	listTables                *connect.Client[v1alpha1.ListTablesRequest, v1alpha1.ListTablesResponse]
	getTable                  *connect.Client[v1alpha1.GetTableRequest, v1alpha1.GetTableResponse]
	getTablePartitionMetadata *connect.Client[v1alpha1.GetTablePartitionMetadataRequest, v1alpha1.GetTablePartitionMetadataResponse]
	listTableColumns          *connect.Client[v1alpha1.ListTableColumnsRequest, v1alpha1.ListTableColumnsResponse]
	listTableConstraints      *connect.Client[v1alpha1.ListTableConstraintsRequest, v1alpha1.ListTableConstraintsResponse]
	listTableIndexes          *connect.Client[v1alpha1.ListTableIndexesRequest, v1alpha1.ListTableIndexesResponse]
	listTablePolicies         *connect.Client[v1alpha1.ListTablePoliciesRequest, v1alpha1.ListTablePoliciesResponse]
	listTableTriggers         *connect.Client[v1alpha1.ListTableTriggersRequest, v1alpha1.ListTableTriggersResponse]
}

// ListTables calls querylane.console.v1alpha1.TableService.ListTables.
func (c *tableServiceClient) ListTables(ctx context.Context, req *connect.Request[v1alpha1.ListTablesRequest]) (*connect.Response[v1alpha1.ListTablesResponse], error) {
	return c.listTables.CallUnary(ctx, req)
}

// GetTable calls querylane.console.v1alpha1.TableService.GetTable.
func (c *tableServiceClient) GetTable(ctx context.Context, req *connect.Request[v1alpha1.GetTableRequest]) (*connect.Response[v1alpha1.GetTableResponse], error) {
	return c.getTable.CallUnary(ctx, req)
}

// GetTablePartitionMetadata calls
// querylane.console.v1alpha1.TableService.GetTablePartitionMetadata.
func (c *tableServiceClient) GetTablePartitionMetadata(ctx context.Context, req *connect.Request[v1alpha1.GetTablePartitionMetadataRequest]) (*connect.Response[v1alpha1.GetTablePartitionMetadataResponse], error) {
	return c.getTablePartitionMetadata.CallUnary(ctx, req)
}

// ListTableColumns calls querylane.console.v1alpha1.TableService.ListTableColumns.
func (c *tableServiceClient) ListTableColumns(ctx context.Context, req *connect.Request[v1alpha1.ListTableColumnsRequest]) (*connect.Response[v1alpha1.ListTableColumnsResponse], error) {
	return c.listTableColumns.CallUnary(ctx, req)
}

// ListTableConstraints calls querylane.console.v1alpha1.TableService.ListTableConstraints.
func (c *tableServiceClient) ListTableConstraints(ctx context.Context, req *connect.Request[v1alpha1.ListTableConstraintsRequest]) (*connect.Response[v1alpha1.ListTableConstraintsResponse], error) {
	return c.listTableConstraints.CallUnary(ctx, req)
}

// ListTableIndexes calls querylane.console.v1alpha1.TableService.ListTableIndexes.
func (c *tableServiceClient) ListTableIndexes(ctx context.Context, req *connect.Request[v1alpha1.ListTableIndexesRequest]) (*connect.Response[v1alpha1.ListTableIndexesResponse], error) {
	return c.listTableIndexes.CallUnary(ctx, req)
}

// ListTablePolicies calls querylane.console.v1alpha1.TableService.ListTablePolicies.
func (c *tableServiceClient) ListTablePolicies(ctx context.Context, req *connect.Request[v1alpha1.ListTablePoliciesRequest]) (*connect.Response[v1alpha1.ListTablePoliciesResponse], error) {
	return c.listTablePolicies.CallUnary(ctx, req)
}

// ListTableTriggers calls querylane.console.v1alpha1.TableService.ListTableTriggers.
func (c *tableServiceClient) ListTableTriggers(ctx context.Context, req *connect.Request[v1alpha1.ListTableTriggersRequest]) (*connect.Response[v1alpha1.ListTableTriggersResponse], error) {
	return c.listTableTriggers.CallUnary(ctx, req)
}

// TableServiceHandler is an implementation of the querylane.console.v1alpha1.TableService service.
type TableServiceHandler interface {
	// Lists tables available in a given Schema.
	ListTables(context.Context, *connect.Request[v1alpha1.ListTablesRequest]) (*connect.Response[v1alpha1.ListTablesResponse], error)
	// Gets the details of a specific Table.
	// Returns table information without column details.
	GetTable(context.Context, *connect.Request[v1alpha1.GetTableRequest]) (*connect.Response[v1alpha1.GetTableResponse], error)
	// Gets PostgreSQL partition metadata for a specific Table.
	GetTablePartitionMetadata(context.Context, *connect.Request[v1alpha1.GetTablePartitionMetadataRequest]) (*connect.Response[v1alpha1.GetTablePartitionMetadataResponse], error)
	// Lists columns for a specific Table.
	// Returns detailed column information including types, constraints, and metadata.
	ListTableColumns(context.Context, *connect.Request[v1alpha1.ListTableColumnsRequest]) (*connect.Response[v1alpha1.ListTableColumnsResponse], error)
	// Lists constraints (primary key, unique, foreign key, check, exclusion) for a table.
	ListTableConstraints(context.Context, *connect.Request[v1alpha1.ListTableConstraintsRequest]) (*connect.Response[v1alpha1.ListTableConstraintsResponse], error)
	// Lists indexes for a table.
	ListTableIndexes(context.Context, *connect.Request[v1alpha1.ListTableIndexesRequest]) (*connect.Response[v1alpha1.ListTableIndexesResponse], error)
	// Lists row-level security policies for a table.
	ListTablePolicies(context.Context, *connect.Request[v1alpha1.ListTablePoliciesRequest]) (*connect.Response[v1alpha1.ListTablePoliciesResponse], error)
	// Lists triggers for a table.
	ListTableTriggers(context.Context, *connect.Request[v1alpha1.ListTableTriggersRequest]) (*connect.Response[v1alpha1.ListTableTriggersResponse], error)
}

// NewTableServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTableServiceHandler(svc TableServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tableServiceMethods := v1alpha1.File_querylane_console_v1alpha1_table_proto.Services().ByName("TableService").Methods()
	tableServiceListTablesHandler := connect.NewUnaryHandler(
		TableServiceListTablesProcedure,
		svc.ListTables,
		connect.WithSchema(tableServiceMethods.ByName("ListTables")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceGetTableHandler := connect.NewUnaryHandler(
		TableServiceGetTableProcedure,
		svc.GetTable,
		connect.WithSchema(tableServiceMethods.ByName("GetTable")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceGetTablePartitionMetadataHandler := connect.NewUnaryHandler(
		TableServiceGetTablePartitionMetadataProcedure,
		svc.GetTablePartitionMetadata,
		connect.WithSchema(tableServiceMethods.ByName("GetTablePartitionMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceListTableColumnsHandler := connect.NewUnaryHandler(
		TableServiceListTableColumnsProcedure,
		svc.ListTableColumns,
		connect.WithSchema(tableServiceMethods.ByName("ListTableColumns")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceListTableConstraintsHandler := connect.NewUnaryHandler(
		TableServiceListTableConstraintsProcedure,
		svc.ListTableConstraints,
		connect.WithSchema(tableServiceMethods.ByName("ListTableConstraints")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceListTableIndexesHandler := connect.NewUnaryHandler(
		TableServiceListTableIndexesProcedure,
		svc.ListTableIndexes,
		connect.WithSchema(tableServiceMethods.ByName("ListTableIndexes")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceListTablePoliciesHandler := connect.NewUnaryHandler(
		TableServiceListTablePoliciesProcedure,
		svc.ListTablePolicies,
		connect.WithSchema(tableServiceMethods.ByName("ListTablePolicies")),
		connect.WithHandlerOptions(opts...),
	)
	tableServiceListTableTriggersHandler := connect.NewUnaryHandler(
		TableServiceListTableTriggersProcedure,
		svc.ListTableTriggers,
		connect.WithSchema(tableServiceMethods.ByName("ListTableTriggers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.TableService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TableServiceListTablesProcedure:
			tableServiceListTablesHandler.ServeHTTP(w, r)
		case TableServiceGetTableProcedure:
			tableServiceGetTableHandler.ServeHTTP(w, r)
		case TableServiceGetTablePartitionMetadataProcedure:
			tableServiceGetTablePartitionMetadataHandler.ServeHTTP(w, r)
		case TableServiceListTableColumnsProcedure:
			tableServiceListTableColumnsHandler.ServeHTTP(w, r)
		case TableServiceListTableConstraintsProcedure:
			tableServiceListTableConstraintsHandler.ServeHTTP(w, r)
		case TableServiceListTableIndexesProcedure:
			tableServiceListTableIndexesHandler.ServeHTTP(w, r)
		case TableServiceListTablePoliciesProcedure:
			tableServiceListTablePoliciesHandler.ServeHTTP(w, r)
		case TableServiceListTableTriggersProcedure:
			tableServiceListTableTriggersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTableServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTableServiceHandler struct{}

func (UnimplementedTableServiceHandler) ListTables(context.Context, *connect.Request[v1alpha1.ListTablesRequest]) (*connect.Response[v1alpha1.ListTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.ListTables is not implemented"))
}

func (UnimplementedTableServiceHandler) GetTable(context.Context, *connect.Request[v1alpha1.GetTableRequest]) (*connect.Response[v1alpha1.GetTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.GetTable is not implemented"))
}

func (UnimplementedTableServiceHandler) GetTablePartitionMetadata(context.Context, *connect.Request[v1alpha1.GetTablePartitionMetadataRequest]) (*connect.Response[v1alpha1.GetTablePartitionMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.GetTablePartitionMetadata is not implemented"))
}

func (UnimplementedTableServiceHandler) ListTableColumns(context.Context, *connect.Request[v1alpha1.ListTableColumnsRequest]) (*connect.Response[v1alpha1.ListTableColumnsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.ListTableColumns is not implemented"))
}

func (UnimplementedTableServiceHandler) ListTableConstraints(context.Context, *connect.Request[v1alpha1.ListTableConstraintsRequest]) (*connect.Response[v1alpha1.ListTableConstraintsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.ListTableConstraints is not implemented"))
}

func (UnimplementedTableServiceHandler) ListTableIndexes(context.Context, *connect.Request[v1alpha1.ListTableIndexesRequest]) (*connect.Response[v1alpha1.ListTableIndexesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.ListTableIndexes is not implemented"))
}

func (UnimplementedTableServiceHandler) ListTablePolicies(context.Context, *connect.Request[v1alpha1.ListTablePoliciesRequest]) (*connect.Response[v1alpha1.ListTablePoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.ListTablePolicies is not implemented"))
}

func (UnimplementedTableServiceHandler) ListTableTriggers(context.Context, *connect.Request[v1alpha1.ListTableTriggersRequest]) (*connect.Response[v1alpha1.ListTableTriggersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.TableService.ListTableTriggers is not implemented"))
}
