// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: querylane/console/v1alpha1/view.proto

package consolev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/querylane/querylane/backend/protogen/querylane/console/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ViewServiceName is the fully-qualified name of the ViewService service.
	ViewServiceName = "querylane.console.v1alpha1.ViewService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ViewServiceListViewsProcedure is the fully-qualified name of the ViewService's ListViews RPC.
	ViewServiceListViewsProcedure = "/querylane.console.v1alpha1.ViewService/ListViews"
	// ViewServiceGetViewProcedure is the fully-qualified name of the ViewService's GetView RPC.
	ViewServiceGetViewProcedure = "/querylane.console.v1alpha1.ViewService/GetView"
)

// ViewServiceClient is a client for the querylane.console.v1alpha1.ViewService service.
type ViewServiceClient interface {
	// Lists views and materialized views in a schema.
	ListViews(context.Context, *connect.Request[v1alpha1.ListViewsRequest]) (*connect.Response[v1alpha1.ListViewsResponse], error)
	// Gets a single view.
	GetView(context.Context, *connect.Request[v1alpha1.GetViewRequest]) (*connect.Response[v1alpha1.GetViewResponse], error)
}

// NewViewServiceClient constructs a client for the querylane.console.v1alpha1.ViewService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewViewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ViewServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	viewServiceMethods := v1alpha1.File_querylane_console_v1alpha1_view_proto.Services().ByName("ViewService").Methods()
	return &viewServiceClient{
		listViews: connect.NewClient[v1alpha1.ListViewsRequest, v1alpha1.ListViewsResponse](
			httpClient,
			baseURL+ViewServiceListViewsProcedure,
			connect.WithSchema(viewServiceMethods.ByName("ListViews")),
			connect.WithClientOptions(opts...),
		),
		getView: connect.NewClient[v1alpha1.GetViewRequest, v1alpha1.GetViewResponse](
			httpClient,
			baseURL+ViewServiceGetViewProcedure,
			connect.WithSchema(viewServiceMethods.ByName("GetView")),
			connect.WithClientOptions(opts...),
		),
	}
}

// viewServiceClient implements ViewServiceClient.
type viewServiceClient struct {
	listViews *connect.Client[v1alpha1.ListViewsRequest, v1alpha1.ListViewsResponse]
	getView   *connect.Client[v1alpha1.GetViewRequest, v1alpha1.GetViewResponse]
}

// ListViews calls querylane.console.v1alpha1.ViewService.ListViews.
func (c *viewServiceClient) ListViews(ctx context.Context, req *connect.Request[v1alpha1.ListViewsRequest]) (*connect.Response[v1alpha1.ListViewsResponse], error) {
	return c.listViews.CallUnary(ctx, req)
}

// GetView calls querylane.console.v1alpha1.ViewService.GetView.
func (c *viewServiceClient) GetView(ctx context.Context, req *connect.Request[v1alpha1.GetViewRequest]) (*connect.Response[v1alpha1.GetViewResponse], error) {
	return c.getView.CallUnary(ctx, req)
}

// ViewServiceHandler is an implementation of the querylane.console.v1alpha1.ViewService service.
type ViewServiceHandler interface {
	// Lists views and materialized views in a schema.
	ListViews(context.Context, *connect.Request[v1alpha1.ListViewsRequest]) (*connect.Response[v1alpha1.ListViewsResponse], error)
	// Gets a single view.
	GetView(context.Context, *connect.Request[v1alpha1.GetViewRequest]) (*connect.Response[v1alpha1.GetViewResponse], error)
}

// NewViewServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewViewServiceHandler(svc ViewServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	viewServiceMethods := v1alpha1.File_querylane_console_v1alpha1_view_proto.Services().ByName("ViewService").Methods()
	viewServiceListViewsHandler := connect.NewUnaryHandler(
		ViewServiceListViewsProcedure,
		svc.ListViews,
		connect.WithSchema(viewServiceMethods.ByName("ListViews")),
		connect.WithHandlerOptions(opts...),
	)
	viewServiceGetViewHandler := connect.NewUnaryHandler(
		ViewServiceGetViewProcedure,
		svc.GetView,
		connect.WithSchema(viewServiceMethods.ByName("GetView")),
		connect.WithHandlerOptions(opts...),
	)
	return "/querylane.console.v1alpha1.ViewService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ViewServiceListViewsProcedure:
			viewServiceListViewsHandler.ServeHTTP(w, r)
		case ViewServiceGetViewProcedure:
			viewServiceGetViewHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedViewServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedViewServiceHandler struct{}

func (UnimplementedViewServiceHandler) ListViews(context.Context, *connect.Request[v1alpha1.ListViewsRequest]) (*connect.Response[v1alpha1.ListViewsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.ViewService.ListViews is not implemented"))
}

func (UnimplementedViewServiceHandler) GetView(context.Context, *connect.Request[v1alpha1.GetViewRequest]) (*connect.Response[v1alpha1.GetViewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("querylane.console.v1alpha1.ViewService.GetView is not implemented"))
}
