// Generated by `bun run docs:api:generate`. Edit the protobuf source, not this file.
import { defineMeta } from "blume";

export default defineMeta({
	title: "API",
	icon: "braces",
	order: 4,
	pages: ["index", "admin", "console", "database", "extension", "instance", "metrics", "onboarding", "role", "runner", "schema", "sql", "table", "table-data", "view"],
});
