apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "querylane.fullname" . }}
  labels:
    {{- include "querylane.labels" . | nindent 4 }}
data:
  querylane.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
