{{- include "querylane.validate" . -}}
{{- $dsn := .Values.metadataDatabase.dsn -}}
{{- if .Values.devPostgres.enabled }}{{ $dsn = include "querylane.devPostgres.dsn" . }}{{ end -}}
{{- if or $dsn .Values.instanceSecretKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querylane.secretName" . }}
  labels:
    {{- include "querylane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $dsn }}
  dsn: {{ $dsn | quote }}
  {{- end }}
  {{- if .Values.instanceSecretKey.value }}
  instance-secret-key: {{ .Values.instanceSecretKey.value | quote }}
  {{- end }}
{{- end }}
