-- Sample tables with varied column types, constraints, and indexes.
-- Idempotent: all CREATE statements use IF NOT EXISTS.

-- =============================================================================
-- public schema
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.customers (
    id          serial       PRIMARY KEY,
    first_name  varchar(100) NOT NULL,
    last_name   varchar(100) NOT NULL,
    email       text         NOT NULL UNIQUE,
    phone       varchar(20),
    is_active   boolean      NOT NULL DEFAULT true,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.generated_identity_examples (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    always_id bigint GENERATED ALWAYS AS IDENTITY,
    email      text NOT NULL,
    email_lower text GENERATED ALWAYS AS (lower(email)) STORED
);

CREATE TABLE IF NOT EXISTS public.products (
    id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    name        text         NOT NULL,
    description text,
    price       numeric(10,2) NOT NULL CHECK (price >= 0),
    tags        text[]       DEFAULT '{}',
    metadata    jsonb        DEFAULT '{}',
    in_stock    boolean      NOT NULL DEFAULT true,
    created_at  timestamptz  NOT NULL DEFAULT now()
);

-- =============================================================================
-- sales schema
-- =============================================================================

DO $$ BEGIN
    CREATE TYPE sales.order_status AS ENUM ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS sales.orders (
    id            serial              PRIMARY KEY,
    customer_id   integer             NOT NULL REFERENCES public.customers(id),
    status        sales.order_status  NOT NULL DEFAULT 'pending',
    total_amount  numeric(12,2)       NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes         text,
    created_at    timestamptz         NOT NULL DEFAULT now(),
    updated_at    timestamptz         NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON sales.orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status      ON sales.orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at  ON sales.orders (created_at DESC);

CREATE TABLE IF NOT EXISTS sales.order_items (
    id          serial        PRIMARY KEY,
    order_id    integer       NOT NULL REFERENCES sales.orders(id),
    product_id  uuid          NOT NULL REFERENCES public.products(id),
    quantity    integer       NOT NULL CHECK (quantity > 0),
    unit_price  numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    created_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON sales.order_items (order_id);

-- =============================================================================
-- analytics schema
-- =============================================================================

CREATE TABLE IF NOT EXISTS analytics.page_views (
    id          bigserial    PRIMARY KEY,
    page_url    text         NOT NULL,
    visitor_ip  inet         NOT NULL,
    user_agent  text,
    referrer    text,
    viewed_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_page_views_viewed_at ON analytics.page_views (viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_page_views_page_url  ON analytics.page_views (page_url);

CREATE TABLE IF NOT EXISTS analytics.daily_stats (
    stat_date       date    PRIMARY KEY,
    total_orders    integer NOT NULL DEFAULT 0,
    total_revenue   numeric(14,2) NOT NULL DEFAULT 0,
    new_customers   integer NOT NULL DEFAULT 0,
    page_views      integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS analytics.events (
    id          bigserial   NOT NULL,
    occurred_at date        NOT NULL,
    payload     jsonb       NOT NULL DEFAULT '{}'
) PARTITION BY RANGE (occurred_at);

CREATE TABLE IF NOT EXISTS analytics.events_2024 PARTITION OF analytics.events
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

CREATE TABLE IF NOT EXISTS analytics.events_2025 PARTITION OF analytics.events
    FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
