// Generated route tree. Excluded from lint and format by Biome config.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SetupRouteImport } from './routes/setup';
import { Route as NewInstanceRouteImport } from './routes/new-instance';
import { Route as AccessDeniedRouteImport } from './routes/access-denied';
import { Route as IndexRouteImport } from './routes/index';
import { Route as InstancesInstanceIdRouteRouteImport } from './routes/instances/$instanceId/route';
import { Route as InstancesInstanceIdIndexRouteImport } from './routes/instances/$instanceId/index';
import { Route as InstancesInstanceIdConfigurationRouteImport } from './routes/instances/$instanceId/configuration';
import { Route as InstancesInstanceIdRolesRouteRouteImport } from './routes/instances/$instanceId/roles/route';
import { Route as InstancesInstanceIdDatabasesRouteRouteImport } from './routes/instances/$instanceId/databases/route';
import { Route as InstancesInstanceIdRolesIndexRouteImport } from './routes/instances/$instanceId/roles/index';
import { Route as InstancesInstanceIdRolesRoleIdRouteImport } from './routes/instances/$instanceId/roles/$roleId';
import { Route as InstancesInstanceIdDatabasesDatabaseIdIndexRouteImport } from './routes/instances/$instanceId/databases/$databaseId/index';
import { Route as InstancesInstanceIdDatabasesDatabaseIdExtensionsRouteImport } from './routes/instances/$instanceId/databases/$databaseId/extensions';
import { Route as InstancesInstanceIdDatabasesDatabaseIdExplorerRouteImport } from './routes/instances/$instanceId/databases/$databaseId/explorer';

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any);
const NewInstanceRoute = NewInstanceRouteImport.update({
  id: '/new-instance',
  path: '/new-instance',
  getParentRoute: () => rootRouteImport,
} as any);
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const InstancesInstanceIdRouteRoute =
  InstancesInstanceIdRouteRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any);
const InstancesInstanceIdIndexRoute =
  InstancesInstanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InstancesInstanceIdRouteRoute,
  } as any);
const InstancesInstanceIdConfigurationRoute =
  InstancesInstanceIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => InstancesInstanceIdRouteRoute,
  } as any);
const InstancesInstanceIdRolesRouteRoute =
  InstancesInstanceIdRolesRouteRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => InstancesInstanceIdRouteRoute,
  } as any);
const InstancesInstanceIdDatabasesRouteRoute =
  InstancesInstanceIdDatabasesRouteRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => InstancesInstanceIdRouteRoute,
  } as any);
const InstancesInstanceIdRolesIndexRoute =
  InstancesInstanceIdRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InstancesInstanceIdRolesRouteRoute,
  } as any);
const InstancesInstanceIdRolesRoleIdRoute =
  InstancesInstanceIdRolesRoleIdRouteImport.update({
    id: '/$roleId',
    path: '/$roleId',
    getParentRoute: () => InstancesInstanceIdRolesRouteRoute,
  } as any);
const InstancesInstanceIdDatabasesDatabaseIdIndexRoute =
  InstancesInstanceIdDatabasesDatabaseIdIndexRouteImport.update({
    id: '/$databaseId/',
    path: '/$databaseId/',
    getParentRoute: () => InstancesInstanceIdDatabasesRouteRoute,
  } as any);
const InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute =
  InstancesInstanceIdDatabasesDatabaseIdExtensionsRouteImport.update({
    id: '/$databaseId/extensions',
    path: '/$databaseId/extensions',
    getParentRoute: () => InstancesInstanceIdDatabasesRouteRoute,
  } as any);
const InstancesInstanceIdDatabasesDatabaseIdExplorerRoute =
  InstancesInstanceIdDatabasesDatabaseIdExplorerRouteImport.update({
    id: '/$databaseId/explorer',
    path: '/$databaseId/explorer',
    getParentRoute: () => InstancesInstanceIdDatabasesRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/access-denied': typeof AccessDeniedRoute;
  '/new-instance': typeof NewInstanceRoute;
  '/setup': typeof SetupRoute;
  '/instances/$instanceId': typeof InstancesInstanceIdRouteRouteWithChildren;
  '/instances/$instanceId/databases': typeof InstancesInstanceIdDatabasesRouteRouteWithChildren;
  '/instances/$instanceId/roles': typeof InstancesInstanceIdRolesRouteRouteWithChildren;
  '/instances/$instanceId/configuration': typeof InstancesInstanceIdConfigurationRoute;
  '/instances/$instanceId/': typeof InstancesInstanceIdIndexRoute;
  '/instances/$instanceId/roles/$roleId': typeof InstancesInstanceIdRolesRoleIdRoute;
  '/instances/$instanceId/roles/': typeof InstancesInstanceIdRolesIndexRoute;
  '/instances/$instanceId/databases/$databaseId/explorer': typeof InstancesInstanceIdDatabasesDatabaseIdExplorerRoute;
  '/instances/$instanceId/databases/$databaseId/extensions': typeof InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute;
  '/instances/$instanceId/databases/$databaseId/': typeof InstancesInstanceIdDatabasesDatabaseIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/access-denied': typeof AccessDeniedRoute;
  '/new-instance': typeof NewInstanceRoute;
  '/setup': typeof SetupRoute;
  '/instances/$instanceId/databases': typeof InstancesInstanceIdDatabasesRouteRouteWithChildren;
  '/instances/$instanceId/configuration': typeof InstancesInstanceIdConfigurationRoute;
  '/instances/$instanceId': typeof InstancesInstanceIdIndexRoute;
  '/instances/$instanceId/roles/$roleId': typeof InstancesInstanceIdRolesRoleIdRoute;
  '/instances/$instanceId/roles': typeof InstancesInstanceIdRolesIndexRoute;
  '/instances/$instanceId/databases/$databaseId/explorer': typeof InstancesInstanceIdDatabasesDatabaseIdExplorerRoute;
  '/instances/$instanceId/databases/$databaseId/extensions': typeof InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute;
  '/instances/$instanceId/databases/$databaseId': typeof InstancesInstanceIdDatabasesDatabaseIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/access-denied': typeof AccessDeniedRoute;
  '/new-instance': typeof NewInstanceRoute;
  '/setup': typeof SetupRoute;
  '/instances/$instanceId': typeof InstancesInstanceIdRouteRouteWithChildren;
  '/instances/$instanceId/databases': typeof InstancesInstanceIdDatabasesRouteRouteWithChildren;
  '/instances/$instanceId/roles': typeof InstancesInstanceIdRolesRouteRouteWithChildren;
  '/instances/$instanceId/configuration': typeof InstancesInstanceIdConfigurationRoute;
  '/instances/$instanceId/': typeof InstancesInstanceIdIndexRoute;
  '/instances/$instanceId/roles/$roleId': typeof InstancesInstanceIdRolesRoleIdRoute;
  '/instances/$instanceId/roles/': typeof InstancesInstanceIdRolesIndexRoute;
  '/instances/$instanceId/databases/$databaseId/explorer': typeof InstancesInstanceIdDatabasesDatabaseIdExplorerRoute;
  '/instances/$instanceId/databases/$databaseId/extensions': typeof InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute;
  '/instances/$instanceId/databases/$databaseId/': typeof InstancesInstanceIdDatabasesDatabaseIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/access-denied'
    | '/new-instance'
    | '/setup'
    | '/instances/$instanceId'
    | '/instances/$instanceId/databases'
    | '/instances/$instanceId/roles'
    | '/instances/$instanceId/configuration'
    | '/instances/$instanceId/'
    | '/instances/$instanceId/roles/$roleId'
    | '/instances/$instanceId/roles/'
    | '/instances/$instanceId/databases/$databaseId/explorer'
    | '/instances/$instanceId/databases/$databaseId/extensions'
    | '/instances/$instanceId/databases/$databaseId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/access-denied'
    | '/new-instance'
    | '/setup'
    | '/instances/$instanceId/databases'
    | '/instances/$instanceId/configuration'
    | '/instances/$instanceId'
    | '/instances/$instanceId/roles/$roleId'
    | '/instances/$instanceId/roles'
    | '/instances/$instanceId/databases/$databaseId/explorer'
    | '/instances/$instanceId/databases/$databaseId/extensions'
    | '/instances/$instanceId/databases/$databaseId';
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/new-instance'
    | '/setup'
    | '/instances/$instanceId'
    | '/instances/$instanceId/databases'
    | '/instances/$instanceId/roles'
    | '/instances/$instanceId/configuration'
    | '/instances/$instanceId/'
    | '/instances/$instanceId/roles/$roleId'
    | '/instances/$instanceId/roles/'
    | '/instances/$instanceId/databases/$databaseId/explorer'
    | '/instances/$instanceId/databases/$databaseId/extensions'
    | '/instances/$instanceId/databases/$databaseId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AccessDeniedRoute: typeof AccessDeniedRoute;
  NewInstanceRoute: typeof NewInstanceRoute;
  SetupRoute: typeof SetupRoute;
  InstancesInstanceIdRouteRoute: typeof InstancesInstanceIdRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup';
      path: '/setup';
      fullPath: '/setup';
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/new-instance': {
      id: '/new-instance';
      path: '/new-instance';
      fullPath: '/new-instance';
      preLoaderRoute: typeof NewInstanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/access-denied': {
      id: '/access-denied';
      path: '/access-denied';
      fullPath: '/access-denied';
      preLoaderRoute: typeof AccessDeniedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/instances/$instanceId': {
      id: '/instances/$instanceId';
      path: '/instances/$instanceId';
      fullPath: '/instances/$instanceId';
      preLoaderRoute: typeof InstancesInstanceIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/instances/$instanceId/': {
      id: '/instances/$instanceId/';
      path: '/';
      fullPath: '/instances/$instanceId/';
      preLoaderRoute: typeof InstancesInstanceIdIndexRouteImport;
      parentRoute: typeof InstancesInstanceIdRouteRoute;
    };
    '/instances/$instanceId/configuration': {
      id: '/instances/$instanceId/configuration';
      path: '/configuration';
      fullPath: '/instances/$instanceId/configuration';
      preLoaderRoute: typeof InstancesInstanceIdConfigurationRouteImport;
      parentRoute: typeof InstancesInstanceIdRouteRoute;
    };
    '/instances/$instanceId/roles': {
      id: '/instances/$instanceId/roles';
      path: '/roles';
      fullPath: '/instances/$instanceId/roles';
      preLoaderRoute: typeof InstancesInstanceIdRolesRouteRouteImport;
      parentRoute: typeof InstancesInstanceIdRouteRoute;
    };
    '/instances/$instanceId/databases': {
      id: '/instances/$instanceId/databases';
      path: '/databases';
      fullPath: '/instances/$instanceId/databases';
      preLoaderRoute: typeof InstancesInstanceIdDatabasesRouteRouteImport;
      parentRoute: typeof InstancesInstanceIdRouteRoute;
    };
    '/instances/$instanceId/roles/': {
      id: '/instances/$instanceId/roles/';
      path: '/';
      fullPath: '/instances/$instanceId/roles/';
      preLoaderRoute: typeof InstancesInstanceIdRolesIndexRouteImport;
      parentRoute: typeof InstancesInstanceIdRolesRouteRoute;
    };
    '/instances/$instanceId/roles/$roleId': {
      id: '/instances/$instanceId/roles/$roleId';
      path: '/$roleId';
      fullPath: '/instances/$instanceId/roles/$roleId';
      preLoaderRoute: typeof InstancesInstanceIdRolesRoleIdRouteImport;
      parentRoute: typeof InstancesInstanceIdRolesRouteRoute;
    };
    '/instances/$instanceId/databases/$databaseId/': {
      id: '/instances/$instanceId/databases/$databaseId/';
      path: '/$databaseId';
      fullPath: '/instances/$instanceId/databases/$databaseId/';
      preLoaderRoute: typeof InstancesInstanceIdDatabasesDatabaseIdIndexRouteImport;
      parentRoute: typeof InstancesInstanceIdDatabasesRouteRoute;
    };
    '/instances/$instanceId/databases/$databaseId/extensions': {
      id: '/instances/$instanceId/databases/$databaseId/extensions';
      path: '/$databaseId/extensions';
      fullPath: '/instances/$instanceId/databases/$databaseId/extensions';
      preLoaderRoute: typeof InstancesInstanceIdDatabasesDatabaseIdExtensionsRouteImport;
      parentRoute: typeof InstancesInstanceIdDatabasesRouteRoute;
    };
    '/instances/$instanceId/databases/$databaseId/explorer': {
      id: '/instances/$instanceId/databases/$databaseId/explorer';
      path: '/$databaseId/explorer';
      fullPath: '/instances/$instanceId/databases/$databaseId/explorer';
      preLoaderRoute: typeof InstancesInstanceIdDatabasesDatabaseIdExplorerRouteImport;
      parentRoute: typeof InstancesInstanceIdDatabasesRouteRoute;
    };
  }
}

interface InstancesInstanceIdDatabasesRouteRouteChildren {
  InstancesInstanceIdDatabasesDatabaseIdExplorerRoute: typeof InstancesInstanceIdDatabasesDatabaseIdExplorerRoute;
  InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute: typeof InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute;
  InstancesInstanceIdDatabasesDatabaseIdIndexRoute: typeof InstancesInstanceIdDatabasesDatabaseIdIndexRoute;
}

const InstancesInstanceIdDatabasesRouteRouteChildren: InstancesInstanceIdDatabasesRouteRouteChildren =
  {
    InstancesInstanceIdDatabasesDatabaseIdExplorerRoute:
      InstancesInstanceIdDatabasesDatabaseIdExplorerRoute,
    InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute:
      InstancesInstanceIdDatabasesDatabaseIdExtensionsRoute,
    InstancesInstanceIdDatabasesDatabaseIdIndexRoute:
      InstancesInstanceIdDatabasesDatabaseIdIndexRoute,
  };

const InstancesInstanceIdDatabasesRouteRouteWithChildren =
  InstancesInstanceIdDatabasesRouteRoute._addFileChildren(
    InstancesInstanceIdDatabasesRouteRouteChildren,
  );

interface InstancesInstanceIdRolesRouteRouteChildren {
  InstancesInstanceIdRolesRoleIdRoute: typeof InstancesInstanceIdRolesRoleIdRoute;
  InstancesInstanceIdRolesIndexRoute: typeof InstancesInstanceIdRolesIndexRoute;
}

const InstancesInstanceIdRolesRouteRouteChildren: InstancesInstanceIdRolesRouteRouteChildren =
  {
    InstancesInstanceIdRolesRoleIdRoute: InstancesInstanceIdRolesRoleIdRoute,
    InstancesInstanceIdRolesIndexRoute: InstancesInstanceIdRolesIndexRoute,
  };

const InstancesInstanceIdRolesRouteRouteWithChildren =
  InstancesInstanceIdRolesRouteRoute._addFileChildren(
    InstancesInstanceIdRolesRouteRouteChildren,
  );

interface InstancesInstanceIdRouteRouteChildren {
  InstancesInstanceIdDatabasesRouteRoute: typeof InstancesInstanceIdDatabasesRouteRouteWithChildren;
  InstancesInstanceIdRolesRouteRoute: typeof InstancesInstanceIdRolesRouteRouteWithChildren;
  InstancesInstanceIdConfigurationRoute: typeof InstancesInstanceIdConfigurationRoute;
  InstancesInstanceIdIndexRoute: typeof InstancesInstanceIdIndexRoute;
}

const InstancesInstanceIdRouteRouteChildren: InstancesInstanceIdRouteRouteChildren =
  {
    InstancesInstanceIdDatabasesRouteRoute:
      InstancesInstanceIdDatabasesRouteRouteWithChildren,
    InstancesInstanceIdRolesRouteRoute:
      InstancesInstanceIdRolesRouteRouteWithChildren,
    InstancesInstanceIdConfigurationRoute:
      InstancesInstanceIdConfigurationRoute,
    InstancesInstanceIdIndexRoute: InstancesInstanceIdIndexRoute,
  };

const InstancesInstanceIdRouteRouteWithChildren =
  InstancesInstanceIdRouteRoute._addFileChildren(
    InstancesInstanceIdRouteRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  NewInstanceRoute: NewInstanceRoute,
  SetupRoute: SetupRoute,
  InstancesInstanceIdRouteRoute: InstancesInstanceIdRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
